// Code generated by ent, DO NOT EDIT.

package memberstat

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the memberstat type in the database.
	Label = "member_stat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLogin holds the string denoting the login field in the database.
	FieldLogin = "login"
	// FieldTotalCommits holds the string denoting the total_commits field in the database.
	FieldTotalCommits = "total_commits"
	// FieldTotalPrCreated holds the string denoting the total_pr_created field in the database.
	FieldTotalPrCreated = "total_pr_created"
	// FieldTotalPrMerged holds the string denoting the total_pr_merged field in the database.
	FieldTotalPrMerged = "total_pr_merged"
	// FieldTotalIssues holds the string denoting the total_issues field in the database.
	FieldTotalIssues = "total_issues"
	// FieldTotalReviews holds the string denoting the total_reviews field in the database.
	FieldTotalReviews = "total_reviews"
	// FieldTotalAdditions holds the string denoting the total_additions field in the database.
	FieldTotalAdditions = "total_additions"
	// FieldTotalDeletions holds the string denoting the total_deletions field in the database.
	FieldTotalDeletions = "total_deletions"
	// FieldFirstActivityYear holds the string denoting the first_activity_year field in the database.
	FieldFirstActivityYear = "first_activity_year"
	// FieldPeakActivityYear holds the string denoting the peak_activity_year field in the database.
	FieldPeakActivityYear = "peak_activity_year"
	// FieldPeakActivityCommits holds the string denoting the peak_activity_commits field in the database.
	FieldPeakActivityCommits = "peak_activity_commits"
	// FieldPrToReviewRatio holds the string denoting the pr_to_review_ratio field in the database.
	FieldPrToReviewRatio = "pr_to_review_ratio"
	// EdgeSnapshot holds the string denoting the snapshot edge name in mutations.
	EdgeSnapshot = "snapshot"
	// Table holds the table name of the memberstat in the database.
	Table = "member_stats"
	// SnapshotTable is the table that holds the snapshot relation/edge.
	SnapshotTable = "member_stats"
	// SnapshotInverseTable is the table name for the Snapshot entity.
	// It exists in this package in order to avoid circular dependency with the "snapshot" package.
	SnapshotInverseTable = "snapshots"
	// SnapshotColumn is the table column denoting the snapshot relation/edge.
	SnapshotColumn = "snapshot_member_stats"
)

// Columns holds all SQL columns for memberstat fields.
var Columns = []string{
	FieldID,
	FieldLogin,
	FieldTotalCommits,
	FieldTotalPrCreated,
	FieldTotalPrMerged,
	FieldTotalIssues,
	FieldTotalReviews,
	FieldTotalAdditions,
	FieldTotalDeletions,
	FieldFirstActivityYear,
	FieldPeakActivityYear,
	FieldPeakActivityCommits,
	FieldPrToReviewRatio,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "member_stats"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"snapshot_member_stats",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// LoginValidator is a validator for the "login" field. It is called by the builders before save.
	LoginValidator func(string) error
	// DefaultTotalCommits holds the default value on creation for the "total_commits" field.
	DefaultTotalCommits int
	// DefaultTotalPrCreated holds the default value on creation for the "total_pr_created" field.
	DefaultTotalPrCreated int
	// DefaultTotalPrMerged holds the default value on creation for the "total_pr_merged" field.
	DefaultTotalPrMerged int
	// DefaultTotalIssues holds the default value on creation for the "total_issues" field.
	DefaultTotalIssues int
	// DefaultTotalReviews holds the default value on creation for the "total_reviews" field.
	DefaultTotalReviews int
	// DefaultTotalAdditions holds the default value on creation for the "total_additions" field.
	DefaultTotalAdditions int
	// DefaultTotalDeletions holds the default value on creation for the "total_deletions" field.
	DefaultTotalDeletions int
	// DefaultFirstActivityYear holds the default value on creation for the "first_activity_year" field.
	DefaultFirstActivityYear int
	// DefaultPeakActivityYear holds the default value on creation for the "peak_activity_year" field.
	DefaultPeakActivityYear int
	// DefaultPeakActivityCommits holds the default value on creation for the "peak_activity_commits" field.
	DefaultPeakActivityCommits int
	// DefaultPrToReviewRatio holds the default value on creation for the "pr_to_review_ratio" field.
	DefaultPrToReviewRatio float64
)

// OrderOption defines the ordering options for the MemberStat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLogin orders the results by the login field.
func ByLogin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogin, opts...).ToFunc()
}

// ByTotalCommits orders the results by the total_commits field.
func ByTotalCommits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCommits, opts...).ToFunc()
}

// ByTotalPrCreated orders the results by the total_pr_created field.
func ByTotalPrCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPrCreated, opts...).ToFunc()
}

// ByTotalPrMerged orders the results by the total_pr_merged field.
func ByTotalPrMerged(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPrMerged, opts...).ToFunc()
}

// ByTotalIssues orders the results by the total_issues field.
func ByTotalIssues(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalIssues, opts...).ToFunc()
}

// ByTotalReviews orders the results by the total_reviews field.
func ByTotalReviews(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalReviews, opts...).ToFunc()
}

// ByTotalAdditions orders the results by the total_additions field.
func ByTotalAdditions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalAdditions, opts...).ToFunc()
}

// ByTotalDeletions orders the results by the total_deletions field.
func ByTotalDeletions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalDeletions, opts...).ToFunc()
}

// ByFirstActivityYear orders the results by the first_activity_year field.
func ByFirstActivityYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstActivityYear, opts...).ToFunc()
}

// ByPeakActivityYear orders the results by the peak_activity_year field.
func ByPeakActivityYear(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeakActivityYear, opts...).ToFunc()
}

// ByPeakActivityCommits orders the results by the peak_activity_commits field.
func ByPeakActivityCommits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPeakActivityCommits, opts...).ToFunc()
}

// ByPrToReviewRatio orders the results by the pr_to_review_ratio field.
func ByPrToReviewRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrToReviewRatio, opts...).ToFunc()
}

// BySnapshotField orders the results by snapshot field.
func BySnapshotField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSnapshotStep(), sql.OrderByField(field, opts...))
	}
}
func newSnapshotStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SnapshotInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SnapshotTable, SnapshotColumn),
	)
}
