// Code generated by ent, DO NOT EDIT.

package memberstat

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldID, id))
}

// Login applies equality check predicate on the "login" field. It's identical to LoginEQ.
func Login(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldLogin, v))
}

// TotalCommits applies equality check predicate on the "total_commits" field. It's identical to TotalCommitsEQ.
func TotalCommits(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalCommits, v))
}

// TotalPrCreated applies equality check predicate on the "total_pr_created" field. It's identical to TotalPrCreatedEQ.
func TotalPrCreated(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalPrCreated, v))
}

// TotalPrMerged applies equality check predicate on the "total_pr_merged" field. It's identical to TotalPrMergedEQ.
func TotalPrMerged(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalPrMerged, v))
}

// TotalIssues applies equality check predicate on the "total_issues" field. It's identical to TotalIssuesEQ.
func TotalIssues(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalIssues, v))
}

// TotalReviews applies equality check predicate on the "total_reviews" field. It's identical to TotalReviewsEQ.
func TotalReviews(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalReviews, v))
}

// TotalAdditions applies equality check predicate on the "total_additions" field. It's identical to TotalAdditionsEQ.
func TotalAdditions(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalAdditions, v))
}

// TotalDeletions applies equality check predicate on the "total_deletions" field. It's identical to TotalDeletionsEQ.
func TotalDeletions(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalDeletions, v))
}

// FirstActivityYear applies equality check predicate on the "first_activity_year" field. It's identical to FirstActivityYearEQ.
func FirstActivityYear(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldFirstActivityYear, v))
}

// PeakActivityYear applies equality check predicate on the "peak_activity_year" field. It's identical to PeakActivityYearEQ.
func PeakActivityYear(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldPeakActivityYear, v))
}

// PeakActivityCommits applies equality check predicate on the "peak_activity_commits" field. It's identical to PeakActivityCommitsEQ.
func PeakActivityCommits(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldPeakActivityCommits, v))
}

// PrToReviewRatio applies equality check predicate on the "pr_to_review_ratio" field. It's identical to PrToReviewRatioEQ.
func PrToReviewRatio(v float64) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldPrToReviewRatio, v))
}

// LoginEQ applies the EQ predicate on the "login" field.
func LoginEQ(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldLogin, v))
}

// LoginNEQ applies the NEQ predicate on the "login" field.
func LoginNEQ(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldLogin, v))
}

// LoginIn applies the In predicate on the "login" field.
func LoginIn(vs ...string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldLogin, vs...))
}

// LoginNotIn applies the NotIn predicate on the "login" field.
func LoginNotIn(vs ...string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldLogin, vs...))
}

// LoginGT applies the GT predicate on the "login" field.
func LoginGT(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldLogin, v))
}

// LoginGTE applies the GTE predicate on the "login" field.
func LoginGTE(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldLogin, v))
}

// LoginLT applies the LT predicate on the "login" field.
func LoginLT(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldLogin, v))
}

// LoginLTE applies the LTE predicate on the "login" field.
func LoginLTE(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldLogin, v))
}

// LoginContains applies the Contains predicate on the "login" field.
func LoginContains(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldContains(FieldLogin, v))
}

// LoginHasPrefix applies the HasPrefix predicate on the "login" field.
func LoginHasPrefix(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldHasPrefix(FieldLogin, v))
}

// LoginHasSuffix applies the HasSuffix predicate on the "login" field.
func LoginHasSuffix(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldHasSuffix(FieldLogin, v))
}

// LoginEqualFold applies the EqualFold predicate on the "login" field.
func LoginEqualFold(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEqualFold(FieldLogin, v))
}

// LoginContainsFold applies the ContainsFold predicate on the "login" field.
func LoginContainsFold(v string) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldContainsFold(FieldLogin, v))
}

// TotalCommitsEQ applies the EQ predicate on the "total_commits" field.
func TotalCommitsEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalCommits, v))
}

// TotalCommitsNEQ applies the NEQ predicate on the "total_commits" field.
func TotalCommitsNEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldTotalCommits, v))
}

// TotalCommitsIn applies the In predicate on the "total_commits" field.
func TotalCommitsIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldTotalCommits, vs...))
}

// TotalCommitsNotIn applies the NotIn predicate on the "total_commits" field.
func TotalCommitsNotIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldTotalCommits, vs...))
}

// TotalCommitsGT applies the GT predicate on the "total_commits" field.
func TotalCommitsGT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldTotalCommits, v))
}

// TotalCommitsGTE applies the GTE predicate on the "total_commits" field.
func TotalCommitsGTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldTotalCommits, v))
}

// TotalCommitsLT applies the LT predicate on the "total_commits" field.
func TotalCommitsLT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldTotalCommits, v))
}

// TotalCommitsLTE applies the LTE predicate on the "total_commits" field.
func TotalCommitsLTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldTotalCommits, v))
}

// TotalPrCreatedEQ applies the EQ predicate on the "total_pr_created" field.
func TotalPrCreatedEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalPrCreated, v))
}

// TotalPrCreatedNEQ applies the NEQ predicate on the "total_pr_created" field.
func TotalPrCreatedNEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldTotalPrCreated, v))
}

// TotalPrCreatedIn applies the In predicate on the "total_pr_created" field.
func TotalPrCreatedIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldTotalPrCreated, vs...))
}

// TotalPrCreatedNotIn applies the NotIn predicate on the "total_pr_created" field.
func TotalPrCreatedNotIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldTotalPrCreated, vs...))
}

// TotalPrCreatedGT applies the GT predicate on the "total_pr_created" field.
func TotalPrCreatedGT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldTotalPrCreated, v))
}

// TotalPrCreatedGTE applies the GTE predicate on the "total_pr_created" field.
func TotalPrCreatedGTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldTotalPrCreated, v))
}

// TotalPrCreatedLT applies the LT predicate on the "total_pr_created" field.
func TotalPrCreatedLT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldTotalPrCreated, v))
}

// TotalPrCreatedLTE applies the LTE predicate on the "total_pr_created" field.
func TotalPrCreatedLTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldTotalPrCreated, v))
}

// TotalPrMergedEQ applies the EQ predicate on the "total_pr_merged" field.
func TotalPrMergedEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalPrMerged, v))
}

// TotalPrMergedNEQ applies the NEQ predicate on the "total_pr_merged" field.
func TotalPrMergedNEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldTotalPrMerged, v))
}

// TotalPrMergedIn applies the In predicate on the "total_pr_merged" field.
func TotalPrMergedIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldTotalPrMerged, vs...))
}

// TotalPrMergedNotIn applies the NotIn predicate on the "total_pr_merged" field.
func TotalPrMergedNotIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldTotalPrMerged, vs...))
}

// TotalPrMergedGT applies the GT predicate on the "total_pr_merged" field.
func TotalPrMergedGT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldTotalPrMerged, v))
}

// TotalPrMergedGTE applies the GTE predicate on the "total_pr_merged" field.
func TotalPrMergedGTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldTotalPrMerged, v))
}

// TotalPrMergedLT applies the LT predicate on the "total_pr_merged" field.
func TotalPrMergedLT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldTotalPrMerged, v))
}

// TotalPrMergedLTE applies the LTE predicate on the "total_pr_merged" field.
func TotalPrMergedLTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldTotalPrMerged, v))
}

// TotalIssuesEQ applies the EQ predicate on the "total_issues" field.
func TotalIssuesEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalIssues, v))
}

// TotalIssuesNEQ applies the NEQ predicate on the "total_issues" field.
func TotalIssuesNEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldTotalIssues, v))
}

// TotalIssuesIn applies the In predicate on the "total_issues" field.
func TotalIssuesIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldTotalIssues, vs...))
}

// TotalIssuesNotIn applies the NotIn predicate on the "total_issues" field.
func TotalIssuesNotIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldTotalIssues, vs...))
}

// TotalIssuesGT applies the GT predicate on the "total_issues" field.
func TotalIssuesGT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldTotalIssues, v))
}

// TotalIssuesGTE applies the GTE predicate on the "total_issues" field.
func TotalIssuesGTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldTotalIssues, v))
}

// TotalIssuesLT applies the LT predicate on the "total_issues" field.
func TotalIssuesLT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldTotalIssues, v))
}

// TotalIssuesLTE applies the LTE predicate on the "total_issues" field.
func TotalIssuesLTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldTotalIssues, v))
}

// TotalReviewsEQ applies the EQ predicate on the "total_reviews" field.
func TotalReviewsEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalReviews, v))
}

// TotalReviewsNEQ applies the NEQ predicate on the "total_reviews" field.
func TotalReviewsNEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldTotalReviews, v))
}

// TotalReviewsIn applies the In predicate on the "total_reviews" field.
func TotalReviewsIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldTotalReviews, vs...))
}

// TotalReviewsNotIn applies the NotIn predicate on the "total_reviews" field.
func TotalReviewsNotIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldTotalReviews, vs...))
}

// TotalReviewsGT applies the GT predicate on the "total_reviews" field.
func TotalReviewsGT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldTotalReviews, v))
}

// TotalReviewsGTE applies the GTE predicate on the "total_reviews" field.
func TotalReviewsGTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldTotalReviews, v))
}

// TotalReviewsLT applies the LT predicate on the "total_reviews" field.
func TotalReviewsLT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldTotalReviews, v))
}

// TotalReviewsLTE applies the LTE predicate on the "total_reviews" field.
func TotalReviewsLTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldTotalReviews, v))
}

// TotalAdditionsEQ applies the EQ predicate on the "total_additions" field.
func TotalAdditionsEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalAdditions, v))
}

// TotalAdditionsNEQ applies the NEQ predicate on the "total_additions" field.
func TotalAdditionsNEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldTotalAdditions, v))
}

// TotalAdditionsIn applies the In predicate on the "total_additions" field.
func TotalAdditionsIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldTotalAdditions, vs...))
}

// TotalAdditionsNotIn applies the NotIn predicate on the "total_additions" field.
func TotalAdditionsNotIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldTotalAdditions, vs...))
}

// TotalAdditionsGT applies the GT predicate on the "total_additions" field.
func TotalAdditionsGT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldTotalAdditions, v))
}

// TotalAdditionsGTE applies the GTE predicate on the "total_additions" field.
func TotalAdditionsGTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldTotalAdditions, v))
}

// TotalAdditionsLT applies the LT predicate on the "total_additions" field.
func TotalAdditionsLT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldTotalAdditions, v))
}

// TotalAdditionsLTE applies the LTE predicate on the "total_additions" field.
func TotalAdditionsLTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldTotalAdditions, v))
}

// TotalDeletionsEQ applies the EQ predicate on the "total_deletions" field.
func TotalDeletionsEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldTotalDeletions, v))
}

// TotalDeletionsNEQ applies the NEQ predicate on the "total_deletions" field.
func TotalDeletionsNEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldTotalDeletions, v))
}

// TotalDeletionsIn applies the In predicate on the "total_deletions" field.
func TotalDeletionsIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldTotalDeletions, vs...))
}

// TotalDeletionsNotIn applies the NotIn predicate on the "total_deletions" field.
func TotalDeletionsNotIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldTotalDeletions, vs...))
}

// TotalDeletionsGT applies the GT predicate on the "total_deletions" field.
func TotalDeletionsGT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldTotalDeletions, v))
}

// TotalDeletionsGTE applies the GTE predicate on the "total_deletions" field.
func TotalDeletionsGTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldTotalDeletions, v))
}

// TotalDeletionsLT applies the LT predicate on the "total_deletions" field.
func TotalDeletionsLT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldTotalDeletions, v))
}

// TotalDeletionsLTE applies the LTE predicate on the "total_deletions" field.
func TotalDeletionsLTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldTotalDeletions, v))
}

// FirstActivityYearEQ applies the EQ predicate on the "first_activity_year" field.
func FirstActivityYearEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldFirstActivityYear, v))
}

// FirstActivityYearNEQ applies the NEQ predicate on the "first_activity_year" field.
func FirstActivityYearNEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldFirstActivityYear, v))
}

// FirstActivityYearIn applies the In predicate on the "first_activity_year" field.
func FirstActivityYearIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldFirstActivityYear, vs...))
}

// FirstActivityYearNotIn applies the NotIn predicate on the "first_activity_year" field.
func FirstActivityYearNotIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldFirstActivityYear, vs...))
}

// FirstActivityYearGT applies the GT predicate on the "first_activity_year" field.
func FirstActivityYearGT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldFirstActivityYear, v))
}

// FirstActivityYearGTE applies the GTE predicate on the "first_activity_year" field.
func FirstActivityYearGTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldFirstActivityYear, v))
}

// FirstActivityYearLT applies the LT predicate on the "first_activity_year" field.
func FirstActivityYearLT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldFirstActivityYear, v))
}

// FirstActivityYearLTE applies the LTE predicate on the "first_activity_year" field.
func FirstActivityYearLTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldFirstActivityYear, v))
}

// PeakActivityYearEQ applies the EQ predicate on the "peak_activity_year" field.
func PeakActivityYearEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldPeakActivityYear, v))
}

// PeakActivityYearNEQ applies the NEQ predicate on the "peak_activity_year" field.
func PeakActivityYearNEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldPeakActivityYear, v))
}

// PeakActivityYearIn applies the In predicate on the "peak_activity_year" field.
func PeakActivityYearIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldPeakActivityYear, vs...))
}

// PeakActivityYearNotIn applies the NotIn predicate on the "peak_activity_year" field.
func PeakActivityYearNotIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldPeakActivityYear, vs...))
}

// PeakActivityYearGT applies the GT predicate on the "peak_activity_year" field.
func PeakActivityYearGT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldPeakActivityYear, v))
}

// PeakActivityYearGTE applies the GTE predicate on the "peak_activity_year" field.
func PeakActivityYearGTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldPeakActivityYear, v))
}

// PeakActivityYearLT applies the LT predicate on the "peak_activity_year" field.
func PeakActivityYearLT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldPeakActivityYear, v))
}

// PeakActivityYearLTE applies the LTE predicate on the "peak_activity_year" field.
func PeakActivityYearLTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldPeakActivityYear, v))
}

// PeakActivityCommitsEQ applies the EQ predicate on the "peak_activity_commits" field.
func PeakActivityCommitsEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldPeakActivityCommits, v))
}

// PeakActivityCommitsNEQ applies the NEQ predicate on the "peak_activity_commits" field.
func PeakActivityCommitsNEQ(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldPeakActivityCommits, v))
}

// PeakActivityCommitsIn applies the In predicate on the "peak_activity_commits" field.
func PeakActivityCommitsIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldPeakActivityCommits, vs...))
}

// PeakActivityCommitsNotIn applies the NotIn predicate on the "peak_activity_commits" field.
func PeakActivityCommitsNotIn(vs ...int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldPeakActivityCommits, vs...))
}

// PeakActivityCommitsGT applies the GT predicate on the "peak_activity_commits" field.
func PeakActivityCommitsGT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldPeakActivityCommits, v))
}

// PeakActivityCommitsGTE applies the GTE predicate on the "peak_activity_commits" field.
func PeakActivityCommitsGTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldPeakActivityCommits, v))
}

// PeakActivityCommitsLT applies the LT predicate on the "peak_activity_commits" field.
func PeakActivityCommitsLT(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldPeakActivityCommits, v))
}

// PeakActivityCommitsLTE applies the LTE predicate on the "peak_activity_commits" field.
func PeakActivityCommitsLTE(v int) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldPeakActivityCommits, v))
}

// PrToReviewRatioEQ applies the EQ predicate on the "pr_to_review_ratio" field.
func PrToReviewRatioEQ(v float64) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldEQ(FieldPrToReviewRatio, v))
}

// PrToReviewRatioNEQ applies the NEQ predicate on the "pr_to_review_ratio" field.
func PrToReviewRatioNEQ(v float64) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNEQ(FieldPrToReviewRatio, v))
}

// PrToReviewRatioIn applies the In predicate on the "pr_to_review_ratio" field.
func PrToReviewRatioIn(vs ...float64) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldIn(FieldPrToReviewRatio, vs...))
}

// PrToReviewRatioNotIn applies the NotIn predicate on the "pr_to_review_ratio" field.
func PrToReviewRatioNotIn(vs ...float64) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldNotIn(FieldPrToReviewRatio, vs...))
}

// PrToReviewRatioGT applies the GT predicate on the "pr_to_review_ratio" field.
func PrToReviewRatioGT(v float64) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGT(FieldPrToReviewRatio, v))
}

// PrToReviewRatioGTE applies the GTE predicate on the "pr_to_review_ratio" field.
func PrToReviewRatioGTE(v float64) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldGTE(FieldPrToReviewRatio, v))
}

// PrToReviewRatioLT applies the LT predicate on the "pr_to_review_ratio" field.
func PrToReviewRatioLT(v float64) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLT(FieldPrToReviewRatio, v))
}

// PrToReviewRatioLTE applies the LTE predicate on the "pr_to_review_ratio" field.
func PrToReviewRatioLTE(v float64) predicate.MemberStat {
	return predicate.MemberStat(sql.FieldLTE(FieldPrToReviewRatio, v))
}

// HasSnapshot applies the HasEdge predicate on the "snapshot" edge.
func HasSnapshot() predicate.MemberStat {
	return predicate.MemberStat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SnapshotTable, SnapshotColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSnapshotWith applies the HasEdge predicate on the "snapshot" edge with a given conditions (other predicates).
func HasSnapshotWith(preds ...predicate.Snapshot) predicate.MemberStat {
	return predicate.MemberStat(func(s *sql.Selector) {
		step := newSnapshotStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemberStat) predicate.MemberStat {
	return predicate.MemberStat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemberStat) predicate.MemberStat {
	return predicate.MemberStat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemberStat) predicate.MemberStat {
	return predicate.MemberStat(sql.NotPredicates(p))
}
