// Code generated by ent, DO NOT EDIT.

package repometa

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the repometa type in the database.
	Label = "repo_meta"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNameWithOwner holds the string denoting the name_with_owner field in the database.
	FieldNameWithOwner = "name_with_owner"
	// FieldOwner holds the string denoting the owner field in the database.
	FieldOwner = "owner"
	// FieldOwnerType holds the string denoting the owner_type field in the database.
	FieldOwnerType = "owner_type"
	// EdgeSnapshot holds the string denoting the snapshot edge name in mutations.
	EdgeSnapshot = "snapshot"
	// Table holds the table name of the repometa in the database.
	Table = "repo_meta"
	// SnapshotTable is the table that holds the snapshot relation/edge.
	SnapshotTable = "repo_meta"
	// SnapshotInverseTable is the table name for the Snapshot entity.
	// It exists in this package in order to avoid circular dependency with the "snapshot" package.
	SnapshotInverseTable = "snapshots"
	// SnapshotColumn is the table column denoting the snapshot relation/edge.
	SnapshotColumn = "snapshot_repo_metas"
)

// Columns holds all SQL columns for repometa fields.
var Columns = []string{
	FieldID,
	FieldNameWithOwner,
	FieldOwner,
	FieldOwnerType,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "repo_meta"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"snapshot_repo_metas",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameWithOwnerValidator is a validator for the "name_with_owner" field. It is called by the builders before save.
	NameWithOwnerValidator func(string) error
	// OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	OwnerValidator func(string) error
	// DefaultOwnerType holds the default value on creation for the "owner_type" field.
	DefaultOwnerType string
)

// OrderOption defines the ordering options for the RepoMeta queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNameWithOwner orders the results by the name_with_owner field.
func ByNameWithOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameWithOwner, opts...).ToFunc()
}

// ByOwner orders the results by the owner field.
func ByOwner(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwner, opts...).ToFunc()
}

// ByOwnerType orders the results by the owner_type field.
func ByOwnerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerType, opts...).ToFunc()
}

// BySnapshotField orders the results by snapshot field.
func BySnapshotField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSnapshotStep(), sql.OrderByField(field, opts...))
	}
}
func newSnapshotStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SnapshotInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SnapshotTable, SnapshotColumn),
	)
}
