// Code generated by ent, DO NOT EDIT.

package snapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the snapshot type in the database.
	Label = "snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// EdgeMemberStats holds the string denoting the member_stats edge name in mutations.
	EdgeMemberStats = "member_stats"
	// EdgeMemberYearStats holds the string denoting the member_year_stats edge name in mutations.
	EdgeMemberYearStats = "member_year_stats"
	// EdgeMemberDayStats holds the string denoting the member_day_stats edge name in mutations.
	EdgeMemberDayStats = "member_day_stats"
	// EdgeMemberRepoStats holds the string denoting the member_repo_stats edge name in mutations.
	EdgeMemberRepoStats = "member_repo_stats"
	// EdgeMemberRepoDayStats holds the string denoting the member_repo_day_stats edge name in mutations.
	EdgeMemberRepoDayStats = "member_repo_day_stats"
	// EdgeRepoMetas holds the string denoting the repo_metas edge name in mutations.
	EdgeRepoMetas = "repo_metas"
	// Table holds the table name of the snapshot in the database.
	Table = "snapshots"
	// MemberStatsTable is the table that holds the member_stats relation/edge.
	MemberStatsTable = "member_stats"
	// MemberStatsInverseTable is the table name for the MemberStat entity.
	// It exists in this package in order to avoid circular dependency with the "memberstat" package.
	MemberStatsInverseTable = "member_stats"
	// MemberStatsColumn is the table column denoting the member_stats relation/edge.
	MemberStatsColumn = "snapshot_member_stats"
	// MemberYearStatsTable is the table that holds the member_year_stats relation/edge.
	MemberYearStatsTable = "member_year_stats"
	// MemberYearStatsInverseTable is the table name for the MemberYearStat entity.
	// It exists in this package in order to avoid circular dependency with the "memberyearstat" package.
	MemberYearStatsInverseTable = "member_year_stats"
	// MemberYearStatsColumn is the table column denoting the member_year_stats relation/edge.
	MemberYearStatsColumn = "snapshot_member_year_stats"
	// MemberDayStatsTable is the table that holds the member_day_stats relation/edge.
	MemberDayStatsTable = "member_day_stats"
	// MemberDayStatsInverseTable is the table name for the MemberDayStat entity.
	// It exists in this package in order to avoid circular dependency with the "memberdaystat" package.
	MemberDayStatsInverseTable = "member_day_stats"
	// MemberDayStatsColumn is the table column denoting the member_day_stats relation/edge.
	MemberDayStatsColumn = "snapshot_member_day_stats"
	// MemberRepoStatsTable is the table that holds the member_repo_stats relation/edge.
	MemberRepoStatsTable = "member_repo_stats"
	// MemberRepoStatsInverseTable is the table name for the MemberRepoStat entity.
	// It exists in this package in order to avoid circular dependency with the "memberrepostat" package.
	MemberRepoStatsInverseTable = "member_repo_stats"
	// MemberRepoStatsColumn is the table column denoting the member_repo_stats relation/edge.
	MemberRepoStatsColumn = "snapshot_member_repo_stats"
	// MemberRepoDayStatsTable is the table that holds the member_repo_day_stats relation/edge.
	MemberRepoDayStatsTable = "member_repo_day_stats"
	// MemberRepoDayStatsInverseTable is the table name for the MemberRepoDayStat entity.
	// It exists in this package in order to avoid circular dependency with the "memberrepodaystat" package.
	MemberRepoDayStatsInverseTable = "member_repo_day_stats"
	// MemberRepoDayStatsColumn is the table column denoting the member_repo_day_stats relation/edge.
	MemberRepoDayStatsColumn = "snapshot_member_repo_day_stats"
	// RepoMetasTable is the table that holds the repo_metas relation/edge.
	RepoMetasTable = "repo_meta"
	// RepoMetasInverseTable is the table name for the RepoMeta entity.
	// It exists in this package in order to avoid circular dependency with the "repometa" package.
	RepoMetasInverseTable = "repo_meta"
	// RepoMetasColumn is the table column denoting the repo_metas relation/edge.
	RepoMetasColumn = "snapshot_repo_metas"
)

// Columns holds all SQL columns for snapshot fields.
var Columns = []string{
	FieldID,
	FieldCapturedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCapturedAt holds the default value on creation for the "captured_at" field.
	DefaultCapturedAt func() time.Time
)

// OrderOption defines the ordering options for the Snapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}

// ByMemberStatsCount orders the results by member_stats count.
func ByMemberStatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMemberStatsStep(), opts...)
	}
}

// ByMemberStats orders the results by member_stats terms.
func ByMemberStats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMemberStatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMemberYearStatsCount orders the results by member_year_stats count.
func ByMemberYearStatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMemberYearStatsStep(), opts...)
	}
}

// ByMemberYearStats orders the results by member_year_stats terms.
func ByMemberYearStats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMemberYearStatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMemberDayStatsCount orders the results by member_day_stats count.
func ByMemberDayStatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMemberDayStatsStep(), opts...)
	}
}

// ByMemberDayStats orders the results by member_day_stats terms.
func ByMemberDayStats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMemberDayStatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMemberRepoStatsCount orders the results by member_repo_stats count.
func ByMemberRepoStatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMemberRepoStatsStep(), opts...)
	}
}

// ByMemberRepoStats orders the results by member_repo_stats terms.
func ByMemberRepoStats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMemberRepoStatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMemberRepoDayStatsCount orders the results by member_repo_day_stats count.
func ByMemberRepoDayStatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMemberRepoDayStatsStep(), opts...)
	}
}

// ByMemberRepoDayStats orders the results by member_repo_day_stats terms.
func ByMemberRepoDayStats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMemberRepoDayStatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRepoMetasCount orders the results by repo_metas count.
func ByRepoMetasCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRepoMetasStep(), opts...)
	}
}

// ByRepoMetas orders the results by repo_metas terms.
func ByRepoMetas(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRepoMetasStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMemberStatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MemberStatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MemberStatsTable, MemberStatsColumn),
	)
}
func newMemberYearStatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MemberYearStatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MemberYearStatsTable, MemberYearStatsColumn),
	)
}
func newMemberDayStatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MemberDayStatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MemberDayStatsTable, MemberDayStatsColumn),
	)
}
func newMemberRepoStatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MemberRepoStatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MemberRepoStatsTable, MemberRepoStatsColumn),
	)
}
func newMemberRepoDayStatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MemberRepoDayStatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MemberRepoDayStatsTable, MemberRepoDayStatsColumn),
	)
}
func newRepoMetasStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RepoMetasInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RepoMetasTable, RepoMetasColumn),
	)
}
