// Code generated by ent, DO NOT EDIT.

package snapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLTE(FieldID, id))
}

// CapturedAt applies equality check predicate on the "captured_at" field. It's identical to CapturedAtEQ.
func CapturedAt(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldCapturedAt, v))
}

// CapturedAtEQ applies the EQ predicate on the "captured_at" field.
func CapturedAtEQ(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldEQ(FieldCapturedAt, v))
}

// CapturedAtNEQ applies the NEQ predicate on the "captured_at" field.
func CapturedAtNEQ(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNEQ(FieldCapturedAt, v))
}

// CapturedAtIn applies the In predicate on the "captured_at" field.
func CapturedAtIn(vs ...time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldIn(FieldCapturedAt, vs...))
}

// CapturedAtNotIn applies the NotIn predicate on the "captured_at" field.
func CapturedAtNotIn(vs ...time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldNotIn(FieldCapturedAt, vs...))
}

// CapturedAtGT applies the GT predicate on the "captured_at" field.
func CapturedAtGT(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGT(FieldCapturedAt, v))
}

// CapturedAtGTE applies the GTE predicate on the "captured_at" field.
func CapturedAtGTE(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldGTE(FieldCapturedAt, v))
}

// CapturedAtLT applies the LT predicate on the "captured_at" field.
func CapturedAtLT(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLT(FieldCapturedAt, v))
}

// CapturedAtLTE applies the LTE predicate on the "captured_at" field.
func CapturedAtLTE(v time.Time) predicate.Snapshot {
	return predicate.Snapshot(sql.FieldLTE(FieldCapturedAt, v))
}

// HasMemberStats applies the HasEdge predicate on the "member_stats" edge.
func HasMemberStats() predicate.Snapshot {
	return predicate.Snapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MemberStatsTable, MemberStatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberStatsWith applies the HasEdge predicate on the "member_stats" edge with a given conditions (other predicates).
func HasMemberStatsWith(preds ...predicate.MemberStat) predicate.Snapshot {
	return predicate.Snapshot(func(s *sql.Selector) {
		step := newMemberStatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMemberYearStats applies the HasEdge predicate on the "member_year_stats" edge.
func HasMemberYearStats() predicate.Snapshot {
	return predicate.Snapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MemberYearStatsTable, MemberYearStatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberYearStatsWith applies the HasEdge predicate on the "member_year_stats" edge with a given conditions (other predicates).
func HasMemberYearStatsWith(preds ...predicate.MemberYearStat) predicate.Snapshot {
	return predicate.Snapshot(func(s *sql.Selector) {
		step := newMemberYearStatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMemberRepoStats applies the HasEdge predicate on the "member_repo_stats" edge.
func HasMemberRepoStats() predicate.Snapshot {
	return predicate.Snapshot(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MemberRepoStatsTable, MemberRepoStatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberRepoStatsWith applies the HasEdge predicate on the "member_repo_stats" edge with a given conditions (other predicates).
func HasMemberRepoStatsWith(preds ...predicate.MemberRepoStat) predicate.Snapshot {
	return predicate.Snapshot(func(s *sql.Selector) {
		step := newMemberRepoStatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Snapshot) predicate.Snapshot {
	return predicate.Snapshot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Snapshot) predicate.Snapshot {
	return predicate.Snapshot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Snapshot) predicate.Snapshot {
	return predicate.Snapshot(sql.NotPredicates(p))
}
