// Code generated by ent, DO NOT EDIT.

package memberyearstat

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLTE(FieldID, id))
}

// Login applies equality check predicate on the "login" field. It's identical to LoginEQ.
func Login(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldLogin, v))
}

// Year applies equality check predicate on the "year" field. It's identical to YearEQ.
func Year(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldYear, v))
}

// CommitCount applies equality check predicate on the "commit_count" field. It's identical to CommitCountEQ.
func CommitCount(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldCommitCount, v))
}

// PrCreated applies equality check predicate on the "pr_created" field. It's identical to PrCreatedEQ.
func PrCreated(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldPrCreated, v))
}

// PrMerged applies equality check predicate on the "pr_merged" field. It's identical to PrMergedEQ.
func PrMerged(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldPrMerged, v))
}

// IssueCount applies equality check predicate on the "issue_count" field. It's identical to IssueCountEQ.
func IssueCount(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldIssueCount, v))
}

// ReviewCount applies equality check predicate on the "review_count" field. It's identical to ReviewCountEQ.
func ReviewCount(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldReviewCount, v))
}

// Additions applies equality check predicate on the "additions" field. It's identical to AdditionsEQ.
func Additions(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldAdditions, v))
}

// Deletions applies equality check predicate on the "deletions" field. It's identical to DeletionsEQ.
func Deletions(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldDeletions, v))
}

// LoginEQ applies the EQ predicate on the "login" field.
func LoginEQ(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldLogin, v))
}

// LoginNEQ applies the NEQ predicate on the "login" field.
func LoginNEQ(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNEQ(FieldLogin, v))
}

// LoginIn applies the In predicate on the "login" field.
func LoginIn(vs ...string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldIn(FieldLogin, vs...))
}

// LoginNotIn applies the NotIn predicate on the "login" field.
func LoginNotIn(vs ...string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNotIn(FieldLogin, vs...))
}

// LoginGT applies the GT predicate on the "login" field.
func LoginGT(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGT(FieldLogin, v))
}

// LoginGTE applies the GTE predicate on the "login" field.
func LoginGTE(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGTE(FieldLogin, v))
}

// LoginLT applies the LT predicate on the "login" field.
func LoginLT(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLT(FieldLogin, v))
}

// LoginLTE applies the LTE predicate on the "login" field.
func LoginLTE(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLTE(FieldLogin, v))
}

// LoginContains applies the Contains predicate on the "login" field.
func LoginContains(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldContains(FieldLogin, v))
}

// LoginHasPrefix applies the HasPrefix predicate on the "login" field.
func LoginHasPrefix(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldHasPrefix(FieldLogin, v))
}

// LoginHasSuffix applies the HasSuffix predicate on the "login" field.
func LoginHasSuffix(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldHasSuffix(FieldLogin, v))
}

// LoginEqualFold applies the EqualFold predicate on the "login" field.
func LoginEqualFold(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEqualFold(FieldLogin, v))
}

// LoginContainsFold applies the ContainsFold predicate on the "login" field.
func LoginContainsFold(v string) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldContainsFold(FieldLogin, v))
}

// YearEQ applies the EQ predicate on the "year" field.
func YearEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldYear, v))
}

// YearNEQ applies the NEQ predicate on the "year" field.
func YearNEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNEQ(FieldYear, v))
}

// YearIn applies the In predicate on the "year" field.
func YearIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldIn(FieldYear, vs...))
}

// YearNotIn applies the NotIn predicate on the "year" field.
func YearNotIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNotIn(FieldYear, vs...))
}

// YearGT applies the GT predicate on the "year" field.
func YearGT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGT(FieldYear, v))
}

// YearGTE applies the GTE predicate on the "year" field.
func YearGTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGTE(FieldYear, v))
}

// YearLT applies the LT predicate on the "year" field.
func YearLT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLT(FieldYear, v))
}

// YearLTE applies the LTE predicate on the "year" field.
func YearLTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLTE(FieldYear, v))
}

// CommitCountEQ applies the EQ predicate on the "commit_count" field.
func CommitCountEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldCommitCount, v))
}

// CommitCountNEQ applies the NEQ predicate on the "commit_count" field.
func CommitCountNEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNEQ(FieldCommitCount, v))
}

// CommitCountIn applies the In predicate on the "commit_count" field.
func CommitCountIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldIn(FieldCommitCount, vs...))
}

// CommitCountNotIn applies the NotIn predicate on the "commit_count" field.
func CommitCountNotIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNotIn(FieldCommitCount, vs...))
}

// CommitCountGT applies the GT predicate on the "commit_count" field.
func CommitCountGT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGT(FieldCommitCount, v))
}

// CommitCountGTE applies the GTE predicate on the "commit_count" field.
func CommitCountGTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGTE(FieldCommitCount, v))
}

// CommitCountLT applies the LT predicate on the "commit_count" field.
func CommitCountLT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLT(FieldCommitCount, v))
}

// CommitCountLTE applies the LTE predicate on the "commit_count" field.
func CommitCountLTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLTE(FieldCommitCount, v))
}

// PrCreatedEQ applies the EQ predicate on the "pr_created" field.
func PrCreatedEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldPrCreated, v))
}

// PrCreatedNEQ applies the NEQ predicate on the "pr_created" field.
func PrCreatedNEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNEQ(FieldPrCreated, v))
}

// PrCreatedIn applies the In predicate on the "pr_created" field.
func PrCreatedIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldIn(FieldPrCreated, vs...))
}

// PrCreatedNotIn applies the NotIn predicate on the "pr_created" field.
func PrCreatedNotIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNotIn(FieldPrCreated, vs...))
}

// PrCreatedGT applies the GT predicate on the "pr_created" field.
func PrCreatedGT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGT(FieldPrCreated, v))
}

// PrCreatedGTE applies the GTE predicate on the "pr_created" field.
func PrCreatedGTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGTE(FieldPrCreated, v))
}

// PrCreatedLT applies the LT predicate on the "pr_created" field.
func PrCreatedLT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLT(FieldPrCreated, v))
}

// PrCreatedLTE applies the LTE predicate on the "pr_created" field.
func PrCreatedLTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLTE(FieldPrCreated, v))
}

// PrMergedEQ applies the EQ predicate on the "pr_merged" field.
func PrMergedEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldPrMerged, v))
}

// PrMergedNEQ applies the NEQ predicate on the "pr_merged" field.
func PrMergedNEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNEQ(FieldPrMerged, v))
}

// PrMergedIn applies the In predicate on the "pr_merged" field.
func PrMergedIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldIn(FieldPrMerged, vs...))
}

// PrMergedNotIn applies the NotIn predicate on the "pr_merged" field.
func PrMergedNotIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNotIn(FieldPrMerged, vs...))
}

// PrMergedGT applies the GT predicate on the "pr_merged" field.
func PrMergedGT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGT(FieldPrMerged, v))
}

// PrMergedGTE applies the GTE predicate on the "pr_merged" field.
func PrMergedGTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGTE(FieldPrMerged, v))
}

// PrMergedLT applies the LT predicate on the "pr_merged" field.
func PrMergedLT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLT(FieldPrMerged, v))
}

// PrMergedLTE applies the LTE predicate on the "pr_merged" field.
func PrMergedLTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLTE(FieldPrMerged, v))
}

// IssueCountEQ applies the EQ predicate on the "issue_count" field.
func IssueCountEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldIssueCount, v))
}

// IssueCountNEQ applies the NEQ predicate on the "issue_count" field.
func IssueCountNEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNEQ(FieldIssueCount, v))
}

// IssueCountIn applies the In predicate on the "issue_count" field.
func IssueCountIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldIn(FieldIssueCount, vs...))
}

// IssueCountNotIn applies the NotIn predicate on the "issue_count" field.
func IssueCountNotIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNotIn(FieldIssueCount, vs...))
}

// IssueCountGT applies the GT predicate on the "issue_count" field.
func IssueCountGT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGT(FieldIssueCount, v))
}

// IssueCountGTE applies the GTE predicate on the "issue_count" field.
func IssueCountGTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGTE(FieldIssueCount, v))
}

// IssueCountLT applies the LT predicate on the "issue_count" field.
func IssueCountLT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLT(FieldIssueCount, v))
}

// IssueCountLTE applies the LTE predicate on the "issue_count" field.
func IssueCountLTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLTE(FieldIssueCount, v))
}

// ReviewCountEQ applies the EQ predicate on the "review_count" field.
func ReviewCountEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldReviewCount, v))
}

// ReviewCountNEQ applies the NEQ predicate on the "review_count" field.
func ReviewCountNEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNEQ(FieldReviewCount, v))
}

// ReviewCountIn applies the In predicate on the "review_count" field.
func ReviewCountIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldIn(FieldReviewCount, vs...))
}

// ReviewCountNotIn applies the NotIn predicate on the "review_count" field.
func ReviewCountNotIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNotIn(FieldReviewCount, vs...))
}

// ReviewCountGT applies the GT predicate on the "review_count" field.
func ReviewCountGT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGT(FieldReviewCount, v))
}

// ReviewCountGTE applies the GTE predicate on the "review_count" field.
func ReviewCountGTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGTE(FieldReviewCount, v))
}

// ReviewCountLT applies the LT predicate on the "review_count" field.
func ReviewCountLT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLT(FieldReviewCount, v))
}

// ReviewCountLTE applies the LTE predicate on the "review_count" field.
func ReviewCountLTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLTE(FieldReviewCount, v))
}

// AdditionsEQ applies the EQ predicate on the "additions" field.
func AdditionsEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldAdditions, v))
}

// AdditionsNEQ applies the NEQ predicate on the "additions" field.
func AdditionsNEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNEQ(FieldAdditions, v))
}

// AdditionsIn applies the In predicate on the "additions" field.
func AdditionsIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldIn(FieldAdditions, vs...))
}

// AdditionsNotIn applies the NotIn predicate on the "additions" field.
func AdditionsNotIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNotIn(FieldAdditions, vs...))
}

// AdditionsGT applies the GT predicate on the "additions" field.
func AdditionsGT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGT(FieldAdditions, v))
}

// AdditionsGTE applies the GTE predicate on the "additions" field.
func AdditionsGTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGTE(FieldAdditions, v))
}

// AdditionsLT applies the LT predicate on the "additions" field.
func AdditionsLT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLT(FieldAdditions, v))
}

// AdditionsLTE applies the LTE predicate on the "additions" field.
func AdditionsLTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLTE(FieldAdditions, v))
}

// DeletionsEQ applies the EQ predicate on the "deletions" field.
func DeletionsEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldEQ(FieldDeletions, v))
}

// DeletionsNEQ applies the NEQ predicate on the "deletions" field.
func DeletionsNEQ(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNEQ(FieldDeletions, v))
}

// DeletionsIn applies the In predicate on the "deletions" field.
func DeletionsIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldIn(FieldDeletions, vs...))
}

// DeletionsNotIn applies the NotIn predicate on the "deletions" field.
func DeletionsNotIn(vs ...int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldNotIn(FieldDeletions, vs...))
}

// DeletionsGT applies the GT predicate on the "deletions" field.
func DeletionsGT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGT(FieldDeletions, v))
}

// DeletionsGTE applies the GTE predicate on the "deletions" field.
func DeletionsGTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldGTE(FieldDeletions, v))
}

// DeletionsLT applies the LT predicate on the "deletions" field.
func DeletionsLT(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLT(FieldDeletions, v))
}

// DeletionsLTE applies the LTE predicate on the "deletions" field.
func DeletionsLTE(v int) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.FieldLTE(FieldDeletions, v))
}

// HasSnapshot applies the HasEdge predicate on the "snapshot" edge.
func HasSnapshot() predicate.MemberYearStat {
	return predicate.MemberYearStat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SnapshotTable, SnapshotColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSnapshotWith applies the HasEdge predicate on the "snapshot" edge with a given conditions (other predicates).
func HasSnapshotWith(preds ...predicate.Snapshot) predicate.MemberYearStat {
	return predicate.MemberYearStat(func(s *sql.Selector) {
		step := newSnapshotStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemberYearStat) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemberYearStat) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemberYearStat) predicate.MemberYearStat {
	return predicate.MemberYearStat(sql.NotPredicates(p))
}
