// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberrepostat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// MemberRepoStat is the model entity for the MemberRepoStat schema.
type MemberRepoStat struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Login holds the value of the "login" field.
	Login string `json:"login,omitempty"`
	// NameWithOwner holds the value of the "name_with_owner" field.
	NameWithOwner string `json:"name_with_owner,omitempty"`
	// CommitCount holds the value of the "commit_count" field.
	CommitCount int `json:"commit_count,omitempty"`
	// PrCreated holds the value of the "pr_created" field.
	PrCreated int `json:"pr_created,omitempty"`
	// PrMerged holds the value of the "pr_merged" field.
	PrMerged int `json:"pr_merged,omitempty"`
	// IssueCount holds the value of the "issue_count" field.
	IssueCount int `json:"issue_count,omitempty"`
	// ReviewCount holds the value of the "review_count" field.
	ReviewCount int `json:"review_count,omitempty"`
	// Additions holds the value of the "additions" field.
	Additions int `json:"additions,omitempty"`
	// Deletions holds the value of the "deletions" field.
	Deletions int `json:"deletions,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MemberRepoStatQuery when eager-loading is set.
	Edges                      MemberRepoStatEdges `json:"edges"`
	snapshot_member_repo_stats *int
	selectValues               sql.SelectValues
}

// MemberRepoStatEdges holds the relations/edges for other nodes in the graph.
type MemberRepoStatEdges struct {
	// Snapshot holds the value of the snapshot edge.
	Snapshot *Snapshot `json:"snapshot,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SnapshotOrErr returns the Snapshot value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MemberRepoStatEdges) SnapshotOrErr() (*Snapshot, error) {
	if e.Snapshot != nil {
		return e.Snapshot, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: snapshot.Label}
	}
	return nil, &NotLoadedError{edge: "snapshot"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemberRepoStat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case memberrepostat.FieldID, memberrepostat.FieldCommitCount, memberrepostat.FieldPrCreated, memberrepostat.FieldPrMerged, memberrepostat.FieldIssueCount, memberrepostat.FieldReviewCount, memberrepostat.FieldAdditions, memberrepostat.FieldDeletions:
			values[i] = new(sql.NullInt64)
		case memberrepostat.FieldLogin, memberrepostat.FieldNameWithOwner:
			values[i] = new(sql.NullString)
		case memberrepostat.ForeignKeys[0]: // snapshot_member_repo_stats
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemberRepoStat fields.
func (_m *MemberRepoStat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case memberrepostat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case memberrepostat.FieldLogin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field login", values[i])
			} else if value.Valid {
				_m.Login = value.String
			}
		case memberrepostat.FieldNameWithOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_with_owner", values[i])
			} else if value.Valid {
				_m.NameWithOwner = value.String
			}
		case memberrepostat.FieldCommitCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field commit_count", values[i])
			} else if value.Valid {
				_m.CommitCount = int(value.Int64)
			}
		case memberrepostat.FieldPrCreated:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pr_created", values[i])
			} else if value.Valid {
				_m.PrCreated = int(value.Int64)
			}
		case memberrepostat.FieldPrMerged:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pr_merged", values[i])
			} else if value.Valid {
				_m.PrMerged = int(value.Int64)
			}
		case memberrepostat.FieldIssueCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field issue_count", values[i])
			} else if value.Valid {
				_m.IssueCount = int(value.Int64)
			}
		case memberrepostat.FieldReviewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field review_count", values[i])
			} else if value.Valid {
				_m.ReviewCount = int(value.Int64)
			}
		case memberrepostat.FieldAdditions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field additions", values[i])
			} else if value.Valid {
				_m.Additions = int(value.Int64)
			}
		case memberrepostat.FieldDeletions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deletions", values[i])
			} else if value.Valid {
				_m.Deletions = int(value.Int64)
			}
		case memberrepostat.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field snapshot_member_repo_stats", value)
			} else if value.Valid {
				_m.snapshot_member_repo_stats = new(int)
				*_m.snapshot_member_repo_stats = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemberRepoStat.
// This includes values selected through modifiers, order, etc.
func (_m *MemberRepoStat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySnapshot queries the "snapshot" edge of the MemberRepoStat entity.
func (_m *MemberRepoStat) QuerySnapshot() *SnapshotQuery {
	return NewMemberRepoStatClient(_m.config).QuerySnapshot(_m)
}

// Update returns a builder for updating this MemberRepoStat.
// Note that you need to call MemberRepoStat.Unwrap() before calling this method if this MemberRepoStat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MemberRepoStat) Update() *MemberRepoStatUpdateOne {
	return NewMemberRepoStatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MemberRepoStat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MemberRepoStat) Unwrap() *MemberRepoStat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemberRepoStat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MemberRepoStat) String() string {
	var builder strings.Builder
	builder.WriteString("MemberRepoStat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("login=")
	builder.WriteString(_m.Login)
	builder.WriteString(", ")
	builder.WriteString("name_with_owner=")
	builder.WriteString(_m.NameWithOwner)
	builder.WriteString(", ")
	builder.WriteString("commit_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommitCount))
	builder.WriteString(", ")
	builder.WriteString("pr_created=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrCreated))
	builder.WriteString(", ")
	builder.WriteString("pr_merged=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrMerged))
	builder.WriteString(", ")
	builder.WriteString("issue_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.IssueCount))
	builder.WriteString(", ")
	builder.WriteString("review_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewCount))
	builder.WriteString(", ")
	builder.WriteString("additions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Additions))
	builder.WriteString(", ")
	builder.WriteString("deletions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Deletions))
	builder.WriteByte(')')
	return builder.String()
}

// MemberRepoStats is a parsable slice of MemberRepoStat.
type MemberRepoStats []*MemberRepoStat
