// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// MemberStatQuery is the builder for querying MemberStat entities.
type MemberStatQuery struct {
	config
	ctx          *QueryContext
	order        []memberstat.OrderOption
	inters       []Interceptor
	predicates   []predicate.MemberStat
	withSnapshot *SnapshotQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MemberStatQuery builder.
func (_q *MemberStatQuery) Where(ps ...predicate.MemberStat) *MemberStatQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *MemberStatQuery) Limit(limit int) *MemberStatQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *MemberStatQuery) Offset(offset int) *MemberStatQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *MemberStatQuery) Unique(unique bool) *MemberStatQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *MemberStatQuery) Order(o ...memberstat.OrderOption) *MemberStatQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySnapshot chains the current query on the "snapshot" edge.
func (_q *MemberStatQuery) QuerySnapshot() *SnapshotQuery {
	query := (&SnapshotClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(memberstat.Table, memberstat.FieldID, selector),
			sqlgraph.To(snapshot.Table, snapshot.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, memberstat.SnapshotTable, memberstat.SnapshotColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MemberStat entity from the query.
// Returns a *NotFoundError when no MemberStat was found.
func (_q *MemberStatQuery) First(ctx context.Context) (*MemberStat, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{memberstat.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *MemberStatQuery) FirstX(ctx context.Context) *MemberStat {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MemberStat ID from the query.
// Returns a *NotFoundError when no MemberStat ID was found.
func (_q *MemberStatQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{memberstat.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *MemberStatQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MemberStat entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MemberStat entity is found.
// Returns a *NotFoundError when no MemberStat entities are found.
func (_q *MemberStatQuery) Only(ctx context.Context) (*MemberStat, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{memberstat.Label}
	default:
		return nil, &NotSingularError{memberstat.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *MemberStatQuery) OnlyX(ctx context.Context) *MemberStat {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MemberStat ID in the query.
// Returns a *NotSingularError when more than one MemberStat ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *MemberStatQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{memberstat.Label}
	default:
		err = &NotSingularError{memberstat.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *MemberStatQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MemberStats.
func (_q *MemberStatQuery) All(ctx context.Context) ([]*MemberStat, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MemberStat, *MemberStatQuery]()
	return withInterceptors[[]*MemberStat](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *MemberStatQuery) AllX(ctx context.Context) []*MemberStat {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MemberStat IDs.
func (_q *MemberStatQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(memberstat.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *MemberStatQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *MemberStatQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*MemberStatQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *MemberStatQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *MemberStatQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *MemberStatQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MemberStatQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *MemberStatQuery) Clone() *MemberStatQuery {
	if _q == nil {
		return nil
	}
	return &MemberStatQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]memberstat.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.MemberStat{}, _q.predicates...),
		withSnapshot: _q.withSnapshot.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSnapshot tells the query-builder to eager-load the nodes that are connected to
// the "snapshot" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *MemberStatQuery) WithSnapshot(opts ...func(*SnapshotQuery)) *MemberStatQuery {
	query := (&SnapshotClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSnapshot = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Login string `json:"login,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MemberStat.Query().
//		GroupBy(memberstat.FieldLogin).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *MemberStatQuery) GroupBy(field string, fields ...string) *MemberStatGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MemberStatGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = memberstat.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Login string `json:"login,omitempty"`
//	}
//
//	client.MemberStat.Query().
//		Select(memberstat.FieldLogin).
//		Scan(ctx, &v)
func (_q *MemberStatQuery) Select(fields ...string) *MemberStatSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &MemberStatSelect{MemberStatQuery: _q}
	sbuild.label = memberstat.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MemberStatSelect configured with the given aggregations.
func (_q *MemberStatQuery) Aggregate(fns ...AggregateFunc) *MemberStatSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *MemberStatQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !memberstat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *MemberStatQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MemberStat, error) {
	var (
		nodes       = []*MemberStat{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withSnapshot != nil,
		}
	)
	if _q.withSnapshot != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, memberstat.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MemberStat).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MemberStat{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSnapshot; query != nil {
		if err := _q.loadSnapshot(ctx, query, nodes, nil,
			func(n *MemberStat, e *Snapshot) { n.Edges.Snapshot = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *MemberStatQuery) loadSnapshot(ctx context.Context, query *SnapshotQuery, nodes []*MemberStat, init func(*MemberStat), assign func(*MemberStat, *Snapshot)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MemberStat)
	for i := range nodes {
		if nodes[i].snapshot_member_stats == nil {
			continue
		}
		fk := *nodes[i].snapshot_member_stats
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(snapshot.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "snapshot_member_stats" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *MemberStatQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *MemberStatQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(memberstat.Table, memberstat.Columns, sqlgraph.NewFieldSpec(memberstat.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberstat.FieldID)
		for i := range fields {
			if fields[i] != memberstat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *MemberStatQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(memberstat.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = memberstat.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MemberStatGroupBy is the group-by builder for MemberStat entities.
type MemberStatGroupBy struct {
	selector
	build *MemberStatQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *MemberStatGroupBy) Aggregate(fns ...AggregateFunc) *MemberStatGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *MemberStatGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemberStatQuery, *MemberStatGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *MemberStatGroupBy) sqlScan(ctx context.Context, root *MemberStatQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MemberStatSelect is the builder for selecting fields of MemberStat entities.
type MemberStatSelect struct {
	*MemberStatQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *MemberStatSelect) Aggregate(fns ...AggregateFunc) *MemberStatSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *MemberStatSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemberStatQuery, *MemberStatSelect](ctx, _s.MemberStatQuery, _s, _s.inters, v)
}

func (_s *MemberStatSelect) sqlScan(ctx context.Context, root *MemberStatQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
