// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberrepodaystat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
)

// MemberRepoDayStatDelete is the builder for deleting a MemberRepoDayStat entity.
type MemberRepoDayStatDelete struct {
	config
	hooks    []Hook
	mutation *MemberRepoDayStatMutation
}

// Where appends a list predicates to the MemberRepoDayStatDelete builder.
func (_d *MemberRepoDayStatDelete) Where(ps ...predicate.MemberRepoDayStat) *MemberRepoDayStatDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MemberRepoDayStatDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemberRepoDayStatDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MemberRepoDayStatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(memberrepodaystat.Table, sqlgraph.NewFieldSpec(memberrepodaystat.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MemberRepoDayStatDeleteOne is the builder for deleting a single MemberRepoDayStat entity.
type MemberRepoDayStatDeleteOne struct {
	_d *MemberRepoDayStatDelete
}

// Where appends a list predicates to the MemberRepoDayStatDelete builder.
func (_d *MemberRepoDayStatDeleteOne) Where(ps ...predicate.MemberRepoDayStat) *MemberRepoDayStatDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MemberRepoDayStatDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{memberrepodaystat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemberRepoDayStatDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
