// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberdaystat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// MemberDayStat is the model entity for the MemberDayStat schema.
type MemberDayStat struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Login holds the value of the "login" field.
	Login string `json:"login,omitempty"`
	// Day holds the value of the "day" field.
	Day string `json:"day,omitempty"`
	// CommitCount holds the value of the "commit_count" field.
	CommitCount int `json:"commit_count,omitempty"`
	// PrCreated holds the value of the "pr_created" field.
	PrCreated int `json:"pr_created,omitempty"`
	// PrMerged holds the value of the "pr_merged" field.
	PrMerged int `json:"pr_merged,omitempty"`
	// IssueCount holds the value of the "issue_count" field.
	IssueCount int `json:"issue_count,omitempty"`
	// ReviewCount holds the value of the "review_count" field.
	ReviewCount int `json:"review_count,omitempty"`
	// Additions holds the value of the "additions" field.
	Additions int `json:"additions,omitempty"`
	// Deletions holds the value of the "deletions" field.
	Deletions int `json:"deletions,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MemberDayStatQuery when eager-loading is set.
	Edges                     MemberDayStatEdges `json:"edges"`
	snapshot_member_day_stats *int
	selectValues              sql.SelectValues
}

// MemberDayStatEdges holds the relations/edges for other nodes in the graph.
type MemberDayStatEdges struct {
	// Snapshot holds the value of the snapshot edge.
	Snapshot *Snapshot `json:"snapshot,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SnapshotOrErr returns the Snapshot value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MemberDayStatEdges) SnapshotOrErr() (*Snapshot, error) {
	if e.Snapshot != nil {
		return e.Snapshot, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: snapshot.Label}
	}
	return nil, &NotLoadedError{edge: "snapshot"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemberDayStat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case memberdaystat.FieldID, memberdaystat.FieldCommitCount, memberdaystat.FieldPrCreated, memberdaystat.FieldPrMerged, memberdaystat.FieldIssueCount, memberdaystat.FieldReviewCount, memberdaystat.FieldAdditions, memberdaystat.FieldDeletions:
			values[i] = new(sql.NullInt64)
		case memberdaystat.FieldLogin, memberdaystat.FieldDay:
			values[i] = new(sql.NullString)
		case memberdaystat.ForeignKeys[0]: // snapshot_member_day_stats
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemberDayStat fields.
func (_m *MemberDayStat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case memberdaystat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case memberdaystat.FieldLogin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field login", values[i])
			} else if value.Valid {
				_m.Login = value.String
			}
		case memberdaystat.FieldDay:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field day", values[i])
			} else if value.Valid {
				_m.Day = value.String
			}
		case memberdaystat.FieldCommitCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field commit_count", values[i])
			} else if value.Valid {
				_m.CommitCount = int(value.Int64)
			}
		case memberdaystat.FieldPrCreated:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pr_created", values[i])
			} else if value.Valid {
				_m.PrCreated = int(value.Int64)
			}
		case memberdaystat.FieldPrMerged:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pr_merged", values[i])
			} else if value.Valid {
				_m.PrMerged = int(value.Int64)
			}
		case memberdaystat.FieldIssueCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field issue_count", values[i])
			} else if value.Valid {
				_m.IssueCount = int(value.Int64)
			}
		case memberdaystat.FieldReviewCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field review_count", values[i])
			} else if value.Valid {
				_m.ReviewCount = int(value.Int64)
			}
		case memberdaystat.FieldAdditions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field additions", values[i])
			} else if value.Valid {
				_m.Additions = int(value.Int64)
			}
		case memberdaystat.FieldDeletions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deletions", values[i])
			} else if value.Valid {
				_m.Deletions = int(value.Int64)
			}
		case memberdaystat.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field snapshot_member_day_stats", value)
			} else if value.Valid {
				_m.snapshot_member_day_stats = new(int)
				*_m.snapshot_member_day_stats = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemberDayStat.
// This includes values selected through modifiers, order, etc.
func (_m *MemberDayStat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySnapshot queries the "snapshot" edge of the MemberDayStat entity.
func (_m *MemberDayStat) QuerySnapshot() *SnapshotQuery {
	return NewMemberDayStatClient(_m.config).QuerySnapshot(_m)
}

// Update returns a builder for updating this MemberDayStat.
// Note that you need to call MemberDayStat.Unwrap() before calling this method if this MemberDayStat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MemberDayStat) Update() *MemberDayStatUpdateOne {
	return NewMemberDayStatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MemberDayStat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MemberDayStat) Unwrap() *MemberDayStat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemberDayStat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MemberDayStat) String() string {
	var builder strings.Builder
	builder.WriteString("MemberDayStat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("login=")
	builder.WriteString(_m.Login)
	builder.WriteString(", ")
	builder.WriteString("day=")
	builder.WriteString(_m.Day)
	builder.WriteString(", ")
	builder.WriteString("commit_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommitCount))
	builder.WriteString(", ")
	builder.WriteString("pr_created=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrCreated))
	builder.WriteString(", ")
	builder.WriteString("pr_merged=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrMerged))
	builder.WriteString(", ")
	builder.WriteString("issue_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.IssueCount))
	builder.WriteString(", ")
	builder.WriteString("review_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReviewCount))
	builder.WriteString(", ")
	builder.WriteString("additions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Additions))
	builder.WriteString(", ")
	builder.WriteString("deletions=")
	builder.WriteString(fmt.Sprintf("%v", _m.Deletions))
	builder.WriteByte(')')
	return builder.String()
}

// MemberDayStats is a parsable slice of MemberDayStat.
type MemberDayStats []*MemberDayStat
