// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// MemberStatUpdate is the builder for updating MemberStat entities.
type MemberStatUpdate struct {
	config
	hooks    []Hook
	mutation *MemberStatMutation
}

// Where appends a list predicates to the MemberStatUpdate builder.
func (_u *MemberStatUpdate) Where(ps ...predicate.MemberStat) *MemberStatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLogin sets the "login" field.
func (_u *MemberStatUpdate) SetLogin(v string) *MemberStatUpdate {
	_u.mutation.SetLogin(v)
	return _u
}

// SetNillableLogin sets the "login" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillableLogin(v *string) *MemberStatUpdate {
	if v != nil {
		_u.SetLogin(*v)
	}
	return _u
}

// SetTotalCommits sets the "total_commits" field.
func (_u *MemberStatUpdate) SetTotalCommits(v int) *MemberStatUpdate {
	_u.mutation.ResetTotalCommits()
	_u.mutation.SetTotalCommits(v)
	return _u
}

// SetNillableTotalCommits sets the "total_commits" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillableTotalCommits(v *int) *MemberStatUpdate {
	if v != nil {
		_u.SetTotalCommits(*v)
	}
	return _u
}

// AddTotalCommits adds value to the "total_commits" field.
func (_u *MemberStatUpdate) AddTotalCommits(v int) *MemberStatUpdate {
	_u.mutation.AddTotalCommits(v)
	return _u
}

// SetTotalPrCreated sets the "total_pr_created" field.
func (_u *MemberStatUpdate) SetTotalPrCreated(v int) *MemberStatUpdate {
	_u.mutation.ResetTotalPrCreated()
	_u.mutation.SetTotalPrCreated(v)
	return _u
}

// SetNillableTotalPrCreated sets the "total_pr_created" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillableTotalPrCreated(v *int) *MemberStatUpdate {
	if v != nil {
		_u.SetTotalPrCreated(*v)
	}
	return _u
}

// AddTotalPrCreated adds value to the "total_pr_created" field.
func (_u *MemberStatUpdate) AddTotalPrCreated(v int) *MemberStatUpdate {
	_u.mutation.AddTotalPrCreated(v)
	return _u
}

// SetTotalPrMerged sets the "total_pr_merged" field.
func (_u *MemberStatUpdate) SetTotalPrMerged(v int) *MemberStatUpdate {
	_u.mutation.ResetTotalPrMerged()
	_u.mutation.SetTotalPrMerged(v)
	return _u
}

// SetNillableTotalPrMerged sets the "total_pr_merged" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillableTotalPrMerged(v *int) *MemberStatUpdate {
	if v != nil {
		_u.SetTotalPrMerged(*v)
	}
	return _u
}

// AddTotalPrMerged adds value to the "total_pr_merged" field.
func (_u *MemberStatUpdate) AddTotalPrMerged(v int) *MemberStatUpdate {
	_u.mutation.AddTotalPrMerged(v)
	return _u
}

// SetTotalIssues sets the "total_issues" field.
func (_u *MemberStatUpdate) SetTotalIssues(v int) *MemberStatUpdate {
	_u.mutation.ResetTotalIssues()
	_u.mutation.SetTotalIssues(v)
	return _u
}

// SetNillableTotalIssues sets the "total_issues" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillableTotalIssues(v *int) *MemberStatUpdate {
	if v != nil {
		_u.SetTotalIssues(*v)
	}
	return _u
}

// AddTotalIssues adds value to the "total_issues" field.
func (_u *MemberStatUpdate) AddTotalIssues(v int) *MemberStatUpdate {
	_u.mutation.AddTotalIssues(v)
	return _u
}

// SetTotalReviews sets the "total_reviews" field.
func (_u *MemberStatUpdate) SetTotalReviews(v int) *MemberStatUpdate {
	_u.mutation.ResetTotalReviews()
	_u.mutation.SetTotalReviews(v)
	return _u
}

// SetNillableTotalReviews sets the "total_reviews" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillableTotalReviews(v *int) *MemberStatUpdate {
	if v != nil {
		_u.SetTotalReviews(*v)
	}
	return _u
}

// AddTotalReviews adds value to the "total_reviews" field.
func (_u *MemberStatUpdate) AddTotalReviews(v int) *MemberStatUpdate {
	_u.mutation.AddTotalReviews(v)
	return _u
}

// SetTotalAdditions sets the "total_additions" field.
func (_u *MemberStatUpdate) SetTotalAdditions(v int) *MemberStatUpdate {
	_u.mutation.ResetTotalAdditions()
	_u.mutation.SetTotalAdditions(v)
	return _u
}

// SetNillableTotalAdditions sets the "total_additions" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillableTotalAdditions(v *int) *MemberStatUpdate {
	if v != nil {
		_u.SetTotalAdditions(*v)
	}
	return _u
}

// AddTotalAdditions adds value to the "total_additions" field.
func (_u *MemberStatUpdate) AddTotalAdditions(v int) *MemberStatUpdate {
	_u.mutation.AddTotalAdditions(v)
	return _u
}

// SetTotalDeletions sets the "total_deletions" field.
func (_u *MemberStatUpdate) SetTotalDeletions(v int) *MemberStatUpdate {
	_u.mutation.ResetTotalDeletions()
	_u.mutation.SetTotalDeletions(v)
	return _u
}

// SetNillableTotalDeletions sets the "total_deletions" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillableTotalDeletions(v *int) *MemberStatUpdate {
	if v != nil {
		_u.SetTotalDeletions(*v)
	}
	return _u
}

// AddTotalDeletions adds value to the "total_deletions" field.
func (_u *MemberStatUpdate) AddTotalDeletions(v int) *MemberStatUpdate {
	_u.mutation.AddTotalDeletions(v)
	return _u
}

// SetFirstActivityYear sets the "first_activity_year" field.
func (_u *MemberStatUpdate) SetFirstActivityYear(v int) *MemberStatUpdate {
	_u.mutation.ResetFirstActivityYear()
	_u.mutation.SetFirstActivityYear(v)
	return _u
}

// SetNillableFirstActivityYear sets the "first_activity_year" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillableFirstActivityYear(v *int) *MemberStatUpdate {
	if v != nil {
		_u.SetFirstActivityYear(*v)
	}
	return _u
}

// AddFirstActivityYear adds value to the "first_activity_year" field.
func (_u *MemberStatUpdate) AddFirstActivityYear(v int) *MemberStatUpdate {
	_u.mutation.AddFirstActivityYear(v)
	return _u
}

// SetPeakActivityYear sets the "peak_activity_year" field.
func (_u *MemberStatUpdate) SetPeakActivityYear(v int) *MemberStatUpdate {
	_u.mutation.ResetPeakActivityYear()
	_u.mutation.SetPeakActivityYear(v)
	return _u
}

// SetNillablePeakActivityYear sets the "peak_activity_year" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillablePeakActivityYear(v *int) *MemberStatUpdate {
	if v != nil {
		_u.SetPeakActivityYear(*v)
	}
	return _u
}

// AddPeakActivityYear adds value to the "peak_activity_year" field.
func (_u *MemberStatUpdate) AddPeakActivityYear(v int) *MemberStatUpdate {
	_u.mutation.AddPeakActivityYear(v)
	return _u
}

// SetPeakActivityCommits sets the "peak_activity_commits" field.
func (_u *MemberStatUpdate) SetPeakActivityCommits(v int) *MemberStatUpdate {
	_u.mutation.ResetPeakActivityCommits()
	_u.mutation.SetPeakActivityCommits(v)
	return _u
}

// SetNillablePeakActivityCommits sets the "peak_activity_commits" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillablePeakActivityCommits(v *int) *MemberStatUpdate {
	if v != nil {
		_u.SetPeakActivityCommits(*v)
	}
	return _u
}

// AddPeakActivityCommits adds value to the "peak_activity_commits" field.
func (_u *MemberStatUpdate) AddPeakActivityCommits(v int) *MemberStatUpdate {
	_u.mutation.AddPeakActivityCommits(v)
	return _u
}

// SetPrToReviewRatio sets the "pr_to_review_ratio" field.
func (_u *MemberStatUpdate) SetPrToReviewRatio(v float64) *MemberStatUpdate {
	_u.mutation.ResetPrToReviewRatio()
	_u.mutation.SetPrToReviewRatio(v)
	return _u
}

// SetNillablePrToReviewRatio sets the "pr_to_review_ratio" field if the given value is not nil.
func (_u *MemberStatUpdate) SetNillablePrToReviewRatio(v *float64) *MemberStatUpdate {
	if v != nil {
		_u.SetPrToReviewRatio(*v)
	}
	return _u
}

// AddPrToReviewRatio adds value to the "pr_to_review_ratio" field.
func (_u *MemberStatUpdate) AddPrToReviewRatio(v float64) *MemberStatUpdate {
	_u.mutation.AddPrToReviewRatio(v)
	return _u
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_u *MemberStatUpdate) SetSnapshotID(id int) *MemberStatUpdate {
	_u.mutation.SetSnapshotID(id)
	return _u
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_u *MemberStatUpdate) SetSnapshot(v *Snapshot) *MemberStatUpdate {
	return _u.SetSnapshotID(v.ID)
}

// Mutation returns the MemberStatMutation object of the builder.
func (_u *MemberStatUpdate) Mutation() *MemberStatMutation {
	return _u.mutation
}

// ClearSnapshot clears the "snapshot" edge to the Snapshot entity.
func (_u *MemberStatUpdate) ClearSnapshot() *MemberStatUpdate {
	_u.mutation.ClearSnapshot()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberStatUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberStatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberStatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberStatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberStatUpdate) check() error {
	if v, ok := _u.mutation.Login(); ok {
		if err := memberstat.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "MemberStat.login": %w`, err)}
		}
	}
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberStat.snapshot"`)
	}
	return nil
}

func (_u *MemberStatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberstat.Table, memberstat.Columns, sqlgraph.NewFieldSpec(memberstat.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Login(); ok {
		_spec.SetField(memberstat.FieldLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalCommits(); ok {
		_spec.SetField(memberstat.FieldTotalCommits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCommits(); ok {
		_spec.AddField(memberstat.FieldTotalCommits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalPrCreated(); ok {
		_spec.SetField(memberstat.FieldTotalPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalPrCreated(); ok {
		_spec.AddField(memberstat.FieldTotalPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalPrMerged(); ok {
		_spec.SetField(memberstat.FieldTotalPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalPrMerged(); ok {
		_spec.AddField(memberstat.FieldTotalPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalIssues(); ok {
		_spec.SetField(memberstat.FieldTotalIssues, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalIssues(); ok {
		_spec.AddField(memberstat.FieldTotalIssues, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalReviews(); ok {
		_spec.SetField(memberstat.FieldTotalReviews, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalReviews(); ok {
		_spec.AddField(memberstat.FieldTotalReviews, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalAdditions(); ok {
		_spec.SetField(memberstat.FieldTotalAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalAdditions(); ok {
		_spec.AddField(memberstat.FieldTotalAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalDeletions(); ok {
		_spec.SetField(memberstat.FieldTotalDeletions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalDeletions(); ok {
		_spec.AddField(memberstat.FieldTotalDeletions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FirstActivityYear(); ok {
		_spec.SetField(memberstat.FieldFirstActivityYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFirstActivityYear(); ok {
		_spec.AddField(memberstat.FieldFirstActivityYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PeakActivityYear(); ok {
		_spec.SetField(memberstat.FieldPeakActivityYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakActivityYear(); ok {
		_spec.AddField(memberstat.FieldPeakActivityYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PeakActivityCommits(); ok {
		_spec.SetField(memberstat.FieldPeakActivityCommits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakActivityCommits(); ok {
		_spec.AddField(memberstat.FieldPeakActivityCommits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrToReviewRatio(); ok {
		_spec.SetField(memberstat.FieldPrToReviewRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrToReviewRatio(); ok {
		_spec.AddField(memberstat.FieldPrToReviewRatio, field.TypeFloat64, value)
	}
	if _u.mutation.SnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberstat.SnapshotTable,
			Columns: []string{memberstat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberstat.SnapshotTable,
			Columns: []string{memberstat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberstat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberStatUpdateOne is the builder for updating a single MemberStat entity.
type MemberStatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberStatMutation
}

// SetLogin sets the "login" field.
func (_u *MemberStatUpdateOne) SetLogin(v string) *MemberStatUpdateOne {
	_u.mutation.SetLogin(v)
	return _u
}

// SetNillableLogin sets the "login" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillableLogin(v *string) *MemberStatUpdateOne {
	if v != nil {
		_u.SetLogin(*v)
	}
	return _u
}

// SetTotalCommits sets the "total_commits" field.
func (_u *MemberStatUpdateOne) SetTotalCommits(v int) *MemberStatUpdateOne {
	_u.mutation.ResetTotalCommits()
	_u.mutation.SetTotalCommits(v)
	return _u
}

// SetNillableTotalCommits sets the "total_commits" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillableTotalCommits(v *int) *MemberStatUpdateOne {
	if v != nil {
		_u.SetTotalCommits(*v)
	}
	return _u
}

// AddTotalCommits adds value to the "total_commits" field.
func (_u *MemberStatUpdateOne) AddTotalCommits(v int) *MemberStatUpdateOne {
	_u.mutation.AddTotalCommits(v)
	return _u
}

// SetTotalPrCreated sets the "total_pr_created" field.
func (_u *MemberStatUpdateOne) SetTotalPrCreated(v int) *MemberStatUpdateOne {
	_u.mutation.ResetTotalPrCreated()
	_u.mutation.SetTotalPrCreated(v)
	return _u
}

// SetNillableTotalPrCreated sets the "total_pr_created" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillableTotalPrCreated(v *int) *MemberStatUpdateOne {
	if v != nil {
		_u.SetTotalPrCreated(*v)
	}
	return _u
}

// AddTotalPrCreated adds value to the "total_pr_created" field.
func (_u *MemberStatUpdateOne) AddTotalPrCreated(v int) *MemberStatUpdateOne {
	_u.mutation.AddTotalPrCreated(v)
	return _u
}

// SetTotalPrMerged sets the "total_pr_merged" field.
func (_u *MemberStatUpdateOne) SetTotalPrMerged(v int) *MemberStatUpdateOne {
	_u.mutation.ResetTotalPrMerged()
	_u.mutation.SetTotalPrMerged(v)
	return _u
}

// SetNillableTotalPrMerged sets the "total_pr_merged" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillableTotalPrMerged(v *int) *MemberStatUpdateOne {
	if v != nil {
		_u.SetTotalPrMerged(*v)
	}
	return _u
}

// AddTotalPrMerged adds value to the "total_pr_merged" field.
func (_u *MemberStatUpdateOne) AddTotalPrMerged(v int) *MemberStatUpdateOne {
	_u.mutation.AddTotalPrMerged(v)
	return _u
}

// SetTotalIssues sets the "total_issues" field.
func (_u *MemberStatUpdateOne) SetTotalIssues(v int) *MemberStatUpdateOne {
	_u.mutation.ResetTotalIssues()
	_u.mutation.SetTotalIssues(v)
	return _u
}

// SetNillableTotalIssues sets the "total_issues" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillableTotalIssues(v *int) *MemberStatUpdateOne {
	if v != nil {
		_u.SetTotalIssues(*v)
	}
	return _u
}

// AddTotalIssues adds value to the "total_issues" field.
func (_u *MemberStatUpdateOne) AddTotalIssues(v int) *MemberStatUpdateOne {
	_u.mutation.AddTotalIssues(v)
	return _u
}

// SetTotalReviews sets the "total_reviews" field.
func (_u *MemberStatUpdateOne) SetTotalReviews(v int) *MemberStatUpdateOne {
	_u.mutation.ResetTotalReviews()
	_u.mutation.SetTotalReviews(v)
	return _u
}

// SetNillableTotalReviews sets the "total_reviews" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillableTotalReviews(v *int) *MemberStatUpdateOne {
	if v != nil {
		_u.SetTotalReviews(*v)
	}
	return _u
}

// AddTotalReviews adds value to the "total_reviews" field.
func (_u *MemberStatUpdateOne) AddTotalReviews(v int) *MemberStatUpdateOne {
	_u.mutation.AddTotalReviews(v)
	return _u
}

// SetTotalAdditions sets the "total_additions" field.
func (_u *MemberStatUpdateOne) SetTotalAdditions(v int) *MemberStatUpdateOne {
	_u.mutation.ResetTotalAdditions()
	_u.mutation.SetTotalAdditions(v)
	return _u
}

// SetNillableTotalAdditions sets the "total_additions" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillableTotalAdditions(v *int) *MemberStatUpdateOne {
	if v != nil {
		_u.SetTotalAdditions(*v)
	}
	return _u
}

// AddTotalAdditions adds value to the "total_additions" field.
func (_u *MemberStatUpdateOne) AddTotalAdditions(v int) *MemberStatUpdateOne {
	_u.mutation.AddTotalAdditions(v)
	return _u
}

// SetTotalDeletions sets the "total_deletions" field.
func (_u *MemberStatUpdateOne) SetTotalDeletions(v int) *MemberStatUpdateOne {
	_u.mutation.ResetTotalDeletions()
	_u.mutation.SetTotalDeletions(v)
	return _u
}

// SetNillableTotalDeletions sets the "total_deletions" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillableTotalDeletions(v *int) *MemberStatUpdateOne {
	if v != nil {
		_u.SetTotalDeletions(*v)
	}
	return _u
}

// AddTotalDeletions adds value to the "total_deletions" field.
func (_u *MemberStatUpdateOne) AddTotalDeletions(v int) *MemberStatUpdateOne {
	_u.mutation.AddTotalDeletions(v)
	return _u
}

// SetFirstActivityYear sets the "first_activity_year" field.
func (_u *MemberStatUpdateOne) SetFirstActivityYear(v int) *MemberStatUpdateOne {
	_u.mutation.ResetFirstActivityYear()
	_u.mutation.SetFirstActivityYear(v)
	return _u
}

// SetNillableFirstActivityYear sets the "first_activity_year" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillableFirstActivityYear(v *int) *MemberStatUpdateOne {
	if v != nil {
		_u.SetFirstActivityYear(*v)
	}
	return _u
}

// AddFirstActivityYear adds value to the "first_activity_year" field.
func (_u *MemberStatUpdateOne) AddFirstActivityYear(v int) *MemberStatUpdateOne {
	_u.mutation.AddFirstActivityYear(v)
	return _u
}

// SetPeakActivityYear sets the "peak_activity_year" field.
func (_u *MemberStatUpdateOne) SetPeakActivityYear(v int) *MemberStatUpdateOne {
	_u.mutation.ResetPeakActivityYear()
	_u.mutation.SetPeakActivityYear(v)
	return _u
}

// SetNillablePeakActivityYear sets the "peak_activity_year" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillablePeakActivityYear(v *int) *MemberStatUpdateOne {
	if v != nil {
		_u.SetPeakActivityYear(*v)
	}
	return _u
}

// AddPeakActivityYear adds value to the "peak_activity_year" field.
func (_u *MemberStatUpdateOne) AddPeakActivityYear(v int) *MemberStatUpdateOne {
	_u.mutation.AddPeakActivityYear(v)
	return _u
}

// SetPeakActivityCommits sets the "peak_activity_commits" field.
func (_u *MemberStatUpdateOne) SetPeakActivityCommits(v int) *MemberStatUpdateOne {
	_u.mutation.ResetPeakActivityCommits()
	_u.mutation.SetPeakActivityCommits(v)
	return _u
}

// SetNillablePeakActivityCommits sets the "peak_activity_commits" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillablePeakActivityCommits(v *int) *MemberStatUpdateOne {
	if v != nil {
		_u.SetPeakActivityCommits(*v)
	}
	return _u
}

// AddPeakActivityCommits adds value to the "peak_activity_commits" field.
func (_u *MemberStatUpdateOne) AddPeakActivityCommits(v int) *MemberStatUpdateOne {
	_u.mutation.AddPeakActivityCommits(v)
	return _u
}

// SetPrToReviewRatio sets the "pr_to_review_ratio" field.
func (_u *MemberStatUpdateOne) SetPrToReviewRatio(v float64) *MemberStatUpdateOne {
	_u.mutation.ResetPrToReviewRatio()
	_u.mutation.SetPrToReviewRatio(v)
	return _u
}

// SetNillablePrToReviewRatio sets the "pr_to_review_ratio" field if the given value is not nil.
func (_u *MemberStatUpdateOne) SetNillablePrToReviewRatio(v *float64) *MemberStatUpdateOne {
	if v != nil {
		_u.SetPrToReviewRatio(*v)
	}
	return _u
}

// AddPrToReviewRatio adds value to the "pr_to_review_ratio" field.
func (_u *MemberStatUpdateOne) AddPrToReviewRatio(v float64) *MemberStatUpdateOne {
	_u.mutation.AddPrToReviewRatio(v)
	return _u
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_u *MemberStatUpdateOne) SetSnapshotID(id int) *MemberStatUpdateOne {
	_u.mutation.SetSnapshotID(id)
	return _u
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_u *MemberStatUpdateOne) SetSnapshot(v *Snapshot) *MemberStatUpdateOne {
	return _u.SetSnapshotID(v.ID)
}

// Mutation returns the MemberStatMutation object of the builder.
func (_u *MemberStatUpdateOne) Mutation() *MemberStatMutation {
	return _u.mutation
}

// ClearSnapshot clears the "snapshot" edge to the Snapshot entity.
func (_u *MemberStatUpdateOne) ClearSnapshot() *MemberStatUpdateOne {
	_u.mutation.ClearSnapshot()
	return _u
}

// Where appends a list predicates to the MemberStatUpdate builder.
func (_u *MemberStatUpdateOne) Where(ps ...predicate.MemberStat) *MemberStatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberStatUpdateOne) Select(field string, fields ...string) *MemberStatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemberStat entity.
func (_u *MemberStatUpdateOne) Save(ctx context.Context) (*MemberStat, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberStatUpdateOne) SaveX(ctx context.Context) *MemberStat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberStatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberStatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberStatUpdateOne) check() error {
	if v, ok := _u.mutation.Login(); ok {
		if err := memberstat.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "MemberStat.login": %w`, err)}
		}
	}
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberStat.snapshot"`)
	}
	return nil
}

func (_u *MemberStatUpdateOne) sqlSave(ctx context.Context) (_node *MemberStat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberstat.Table, memberstat.Columns, sqlgraph.NewFieldSpec(memberstat.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemberStat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberstat.FieldID)
		for _, f := range fields {
			if !memberstat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memberstat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Login(); ok {
		_spec.SetField(memberstat.FieldLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalCommits(); ok {
		_spec.SetField(memberstat.FieldTotalCommits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCommits(); ok {
		_spec.AddField(memberstat.FieldTotalCommits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalPrCreated(); ok {
		_spec.SetField(memberstat.FieldTotalPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalPrCreated(); ok {
		_spec.AddField(memberstat.FieldTotalPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalPrMerged(); ok {
		_spec.SetField(memberstat.FieldTotalPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalPrMerged(); ok {
		_spec.AddField(memberstat.FieldTotalPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalIssues(); ok {
		_spec.SetField(memberstat.FieldTotalIssues, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalIssues(); ok {
		_spec.AddField(memberstat.FieldTotalIssues, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalReviews(); ok {
		_spec.SetField(memberstat.FieldTotalReviews, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalReviews(); ok {
		_spec.AddField(memberstat.FieldTotalReviews, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalAdditions(); ok {
		_spec.SetField(memberstat.FieldTotalAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalAdditions(); ok {
		_spec.AddField(memberstat.FieldTotalAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TotalDeletions(); ok {
		_spec.SetField(memberstat.FieldTotalDeletions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalDeletions(); ok {
		_spec.AddField(memberstat.FieldTotalDeletions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FirstActivityYear(); ok {
		_spec.SetField(memberstat.FieldFirstActivityYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFirstActivityYear(); ok {
		_spec.AddField(memberstat.FieldFirstActivityYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PeakActivityYear(); ok {
		_spec.SetField(memberstat.FieldPeakActivityYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakActivityYear(); ok {
		_spec.AddField(memberstat.FieldPeakActivityYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PeakActivityCommits(); ok {
		_spec.SetField(memberstat.FieldPeakActivityCommits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakActivityCommits(); ok {
		_spec.AddField(memberstat.FieldPeakActivityCommits, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrToReviewRatio(); ok {
		_spec.SetField(memberstat.FieldPrToReviewRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrToReviewRatio(); ok {
		_spec.AddField(memberstat.FieldPrToReviewRatio, field.TypeFloat64, value)
	}
	if _u.mutation.SnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberstat.SnapshotTable,
			Columns: []string{memberstat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberstat.SnapshotTable,
			Columns: []string{memberstat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MemberStat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberstat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
