// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// MemberStat is the model entity for the MemberStat schema.
type MemberStat struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Login holds the value of the "login" field.
	Login string `json:"login,omitempty"`
	// TotalCommits holds the value of the "total_commits" field.
	TotalCommits int `json:"total_commits,omitempty"`
	// TotalPrCreated holds the value of the "total_pr_created" field.
	TotalPrCreated int `json:"total_pr_created,omitempty"`
	// TotalPrMerged holds the value of the "total_pr_merged" field.
	TotalPrMerged int `json:"total_pr_merged,omitempty"`
	// TotalIssues holds the value of the "total_issues" field.
	TotalIssues int `json:"total_issues,omitempty"`
	// TotalReviews holds the value of the "total_reviews" field.
	TotalReviews int `json:"total_reviews,omitempty"`
	// TotalAdditions holds the value of the "total_additions" field.
	TotalAdditions int `json:"total_additions,omitempty"`
	// TotalDeletions holds the value of the "total_deletions" field.
	TotalDeletions int `json:"total_deletions,omitempty"`
	// FirstActivityYear holds the value of the "first_activity_year" field.
	FirstActivityYear int `json:"first_activity_year,omitempty"`
	// PeakActivityYear holds the value of the "peak_activity_year" field.
	PeakActivityYear int `json:"peak_activity_year,omitempty"`
	// PeakActivityCommits holds the value of the "peak_activity_commits" field.
	PeakActivityCommits int `json:"peak_activity_commits,omitempty"`
	// PrToReviewRatio holds the value of the "pr_to_review_ratio" field.
	PrToReviewRatio float64 `json:"pr_to_review_ratio,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MemberStatQuery when eager-loading is set.
	Edges                 MemberStatEdges `json:"edges"`
	snapshot_member_stats *int
	selectValues          sql.SelectValues
}

// MemberStatEdges holds the relations/edges for other nodes in the graph.
type MemberStatEdges struct {
	// Snapshot holds the value of the snapshot edge.
	Snapshot *Snapshot `json:"snapshot,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SnapshotOrErr returns the Snapshot value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MemberStatEdges) SnapshotOrErr() (*Snapshot, error) {
	if e.Snapshot != nil {
		return e.Snapshot, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: snapshot.Label}
	}
	return nil, &NotLoadedError{edge: "snapshot"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemberStat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case memberstat.FieldPrToReviewRatio:
			values[i] = new(sql.NullFloat64)
		case memberstat.FieldID, memberstat.FieldTotalCommits, memberstat.FieldTotalPrCreated, memberstat.FieldTotalPrMerged, memberstat.FieldTotalIssues, memberstat.FieldTotalReviews, memberstat.FieldTotalAdditions, memberstat.FieldTotalDeletions, memberstat.FieldFirstActivityYear, memberstat.FieldPeakActivityYear, memberstat.FieldPeakActivityCommits:
			values[i] = new(sql.NullInt64)
		case memberstat.FieldLogin:
			values[i] = new(sql.NullString)
		case memberstat.ForeignKeys[0]: // snapshot_member_stats
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemberStat fields.
func (_m *MemberStat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case memberstat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case memberstat.FieldLogin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field login", values[i])
			} else if value.Valid {
				_m.Login = value.String
			}
		case memberstat.FieldTotalCommits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_commits", values[i])
			} else if value.Valid {
				_m.TotalCommits = int(value.Int64)
			}
		case memberstat.FieldTotalPrCreated:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_pr_created", values[i])
			} else if value.Valid {
				_m.TotalPrCreated = int(value.Int64)
			}
		case memberstat.FieldTotalPrMerged:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_pr_merged", values[i])
			} else if value.Valid {
				_m.TotalPrMerged = int(value.Int64)
			}
		case memberstat.FieldTotalIssues:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_issues", values[i])
			} else if value.Valid {
				_m.TotalIssues = int(value.Int64)
			}
		case memberstat.FieldTotalReviews:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_reviews", values[i])
			} else if value.Valid {
				_m.TotalReviews = int(value.Int64)
			}
		case memberstat.FieldTotalAdditions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_additions", values[i])
			} else if value.Valid {
				_m.TotalAdditions = int(value.Int64)
			}
		case memberstat.FieldTotalDeletions:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_deletions", values[i])
			} else if value.Valid {
				_m.TotalDeletions = int(value.Int64)
			}
		case memberstat.FieldFirstActivityYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field first_activity_year", values[i])
			} else if value.Valid {
				_m.FirstActivityYear = int(value.Int64)
			}
		case memberstat.FieldPeakActivityYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field peak_activity_year", values[i])
			} else if value.Valid {
				_m.PeakActivityYear = int(value.Int64)
			}
		case memberstat.FieldPeakActivityCommits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field peak_activity_commits", values[i])
			} else if value.Valid {
				_m.PeakActivityCommits = int(value.Int64)
			}
		case memberstat.FieldPrToReviewRatio:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pr_to_review_ratio", values[i])
			} else if value.Valid {
				_m.PrToReviewRatio = value.Float64
			}
		case memberstat.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field snapshot_member_stats", value)
			} else if value.Valid {
				_m.snapshot_member_stats = new(int)
				*_m.snapshot_member_stats = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemberStat.
// This includes values selected through modifiers, order, etc.
func (_m *MemberStat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySnapshot queries the "snapshot" edge of the MemberStat entity.
func (_m *MemberStat) QuerySnapshot() *SnapshotQuery {
	return NewMemberStatClient(_m.config).QuerySnapshot(_m)
}

// Update returns a builder for updating this MemberStat.
// Note that you need to call MemberStat.Unwrap() before calling this method if this MemberStat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MemberStat) Update() *MemberStatUpdateOne {
	return NewMemberStatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MemberStat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MemberStat) Unwrap() *MemberStat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemberStat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MemberStat) String() string {
	var builder strings.Builder
	builder.WriteString("MemberStat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("login=")
	builder.WriteString(_m.Login)
	builder.WriteString(", ")
	builder.WriteString("total_commits=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCommits))
	builder.WriteString(", ")
	builder.WriteString("total_pr_created=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalPrCreated))
	builder.WriteString(", ")
	builder.WriteString("total_pr_merged=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalPrMerged))
	builder.WriteString(", ")
	builder.WriteString("total_issues=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalIssues))
	builder.WriteString(", ")
	builder.WriteString("total_reviews=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalReviews))
	builder.WriteString(", ")
	builder.WriteString("total_additions=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalAdditions))
	builder.WriteString(", ")
	builder.WriteString("total_deletions=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalDeletions))
	builder.WriteString(", ")
	builder.WriteString("first_activity_year=")
	builder.WriteString(fmt.Sprintf("%v", _m.FirstActivityYear))
	builder.WriteString(", ")
	builder.WriteString("peak_activity_year=")
	builder.WriteString(fmt.Sprintf("%v", _m.PeakActivityYear))
	builder.WriteString(", ")
	builder.WriteString("peak_activity_commits=")
	builder.WriteString(fmt.Sprintf("%v", _m.PeakActivityCommits))
	builder.WriteString(", ")
	builder.WriteString("pr_to_review_ratio=")
	builder.WriteString(fmt.Sprintf("%v", _m.PrToReviewRatio))
	builder.WriteByte(')')
	return builder.String()
}

// MemberStats is a parsable slice of MemberStat.
type MemberStats []*MemberStat
