// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberyearstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// MemberYearStatCreate is the builder for creating a MemberYearStat entity.
type MemberYearStatCreate struct {
	config
	mutation *MemberYearStatMutation
	hooks    []Hook
}

// SetLogin sets the "login" field.
func (_c *MemberYearStatCreate) SetLogin(v string) *MemberYearStatCreate {
	_c.mutation.SetLogin(v)
	return _c
}

// SetYear sets the "year" field.
func (_c *MemberYearStatCreate) SetYear(v int) *MemberYearStatCreate {
	_c.mutation.SetYear(v)
	return _c
}

// SetCommitCount sets the "commit_count" field.
func (_c *MemberYearStatCreate) SetCommitCount(v int) *MemberYearStatCreate {
	_c.mutation.SetCommitCount(v)
	return _c
}

// SetNillableCommitCount sets the "commit_count" field if the given value is not nil.
func (_c *MemberYearStatCreate) SetNillableCommitCount(v *int) *MemberYearStatCreate {
	if v != nil {
		_c.SetCommitCount(*v)
	}
	return _c
}

// SetPrCreated sets the "pr_created" field.
func (_c *MemberYearStatCreate) SetPrCreated(v int) *MemberYearStatCreate {
	_c.mutation.SetPrCreated(v)
	return _c
}

// SetNillablePrCreated sets the "pr_created" field if the given value is not nil.
func (_c *MemberYearStatCreate) SetNillablePrCreated(v *int) *MemberYearStatCreate {
	if v != nil {
		_c.SetPrCreated(*v)
	}
	return _c
}

// SetPrMerged sets the "pr_merged" field.
func (_c *MemberYearStatCreate) SetPrMerged(v int) *MemberYearStatCreate {
	_c.mutation.SetPrMerged(v)
	return _c
}

// SetNillablePrMerged sets the "pr_merged" field if the given value is not nil.
func (_c *MemberYearStatCreate) SetNillablePrMerged(v *int) *MemberYearStatCreate {
	if v != nil {
		_c.SetPrMerged(*v)
	}
	return _c
}

// SetIssueCount sets the "issue_count" field.
func (_c *MemberYearStatCreate) SetIssueCount(v int) *MemberYearStatCreate {
	_c.mutation.SetIssueCount(v)
	return _c
}

// SetNillableIssueCount sets the "issue_count" field if the given value is not nil.
func (_c *MemberYearStatCreate) SetNillableIssueCount(v *int) *MemberYearStatCreate {
	if v != nil {
		_c.SetIssueCount(*v)
	}
	return _c
}

// SetReviewCount sets the "review_count" field.
func (_c *MemberYearStatCreate) SetReviewCount(v int) *MemberYearStatCreate {
	_c.mutation.SetReviewCount(v)
	return _c
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_c *MemberYearStatCreate) SetNillableReviewCount(v *int) *MemberYearStatCreate {
	if v != nil {
		_c.SetReviewCount(*v)
	}
	return _c
}

// SetAdditions sets the "additions" field.
func (_c *MemberYearStatCreate) SetAdditions(v int) *MemberYearStatCreate {
	_c.mutation.SetAdditions(v)
	return _c
}

// SetNillableAdditions sets the "additions" field if the given value is not nil.
func (_c *MemberYearStatCreate) SetNillableAdditions(v *int) *MemberYearStatCreate {
	if v != nil {
		_c.SetAdditions(*v)
	}
	return _c
}

// SetDeletions sets the "deletions" field.
func (_c *MemberYearStatCreate) SetDeletions(v int) *MemberYearStatCreate {
	_c.mutation.SetDeletions(v)
	return _c
}

// SetNillableDeletions sets the "deletions" field if the given value is not nil.
func (_c *MemberYearStatCreate) SetNillableDeletions(v *int) *MemberYearStatCreate {
	if v != nil {
		_c.SetDeletions(*v)
	}
	return _c
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_c *MemberYearStatCreate) SetSnapshotID(id int) *MemberYearStatCreate {
	_c.mutation.SetSnapshotID(id)
	return _c
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_c *MemberYearStatCreate) SetSnapshot(v *Snapshot) *MemberYearStatCreate {
	return _c.SetSnapshotID(v.ID)
}

// Mutation returns the MemberYearStatMutation object of the builder.
func (_c *MemberYearStatCreate) Mutation() *MemberYearStatMutation {
	return _c.mutation
}

// Save creates the MemberYearStat in the database.
func (_c *MemberYearStatCreate) Save(ctx context.Context) (*MemberYearStat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemberYearStatCreate) SaveX(ctx context.Context) *MemberYearStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberYearStatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberYearStatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemberYearStatCreate) defaults() {
	if _, ok := _c.mutation.CommitCount(); !ok {
		v := memberyearstat.DefaultCommitCount
		_c.mutation.SetCommitCount(v)
	}
	if _, ok := _c.mutation.PrCreated(); !ok {
		v := memberyearstat.DefaultPrCreated
		_c.mutation.SetPrCreated(v)
	}
	if _, ok := _c.mutation.PrMerged(); !ok {
		v := memberyearstat.DefaultPrMerged
		_c.mutation.SetPrMerged(v)
	}
	if _, ok := _c.mutation.IssueCount(); !ok {
		v := memberyearstat.DefaultIssueCount
		_c.mutation.SetIssueCount(v)
	}
	if _, ok := _c.mutation.ReviewCount(); !ok {
		v := memberyearstat.DefaultReviewCount
		_c.mutation.SetReviewCount(v)
	}
	if _, ok := _c.mutation.Additions(); !ok {
		v := memberyearstat.DefaultAdditions
		_c.mutation.SetAdditions(v)
	}
	if _, ok := _c.mutation.Deletions(); !ok {
		v := memberyearstat.DefaultDeletions
		_c.mutation.SetDeletions(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemberYearStatCreate) check() error {
	if _, ok := _c.mutation.Login(); !ok {
		return &ValidationError{Name: "login", err: errors.New(`ent: missing required field "MemberYearStat.login"`)}
	}
	if v, ok := _c.mutation.Login(); ok {
		if err := memberyearstat.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "MemberYearStat.login": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Year(); !ok {
		return &ValidationError{Name: "year", err: errors.New(`ent: missing required field "MemberYearStat.year"`)}
	}
	if _, ok := _c.mutation.CommitCount(); !ok {
		return &ValidationError{Name: "commit_count", err: errors.New(`ent: missing required field "MemberYearStat.commit_count"`)}
	}
	if _, ok := _c.mutation.PrCreated(); !ok {
		return &ValidationError{Name: "pr_created", err: errors.New(`ent: missing required field "MemberYearStat.pr_created"`)}
	}
	if _, ok := _c.mutation.PrMerged(); !ok {
		return &ValidationError{Name: "pr_merged", err: errors.New(`ent: missing required field "MemberYearStat.pr_merged"`)}
	}
	if _, ok := _c.mutation.IssueCount(); !ok {
		return &ValidationError{Name: "issue_count", err: errors.New(`ent: missing required field "MemberYearStat.issue_count"`)}
	}
	if _, ok := _c.mutation.ReviewCount(); !ok {
		return &ValidationError{Name: "review_count", err: errors.New(`ent: missing required field "MemberYearStat.review_count"`)}
	}
	if _, ok := _c.mutation.Additions(); !ok {
		return &ValidationError{Name: "additions", err: errors.New(`ent: missing required field "MemberYearStat.additions"`)}
	}
	if _, ok := _c.mutation.Deletions(); !ok {
		return &ValidationError{Name: "deletions", err: errors.New(`ent: missing required field "MemberYearStat.deletions"`)}
	}
	if len(_c.mutation.SnapshotIDs()) == 0 {
		return &ValidationError{Name: "snapshot", err: errors.New(`ent: missing required edge "MemberYearStat.snapshot"`)}
	}
	return nil
}

func (_c *MemberYearStatCreate) sqlSave(ctx context.Context) (*MemberYearStat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemberYearStatCreate) createSpec() (*MemberYearStat, *sqlgraph.CreateSpec) {
	var (
		_node = &MemberYearStat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memberyearstat.Table, sqlgraph.NewFieldSpec(memberyearstat.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Login(); ok {
		_spec.SetField(memberyearstat.FieldLogin, field.TypeString, value)
		_node.Login = value
	}
	if value, ok := _c.mutation.Year(); ok {
		_spec.SetField(memberyearstat.FieldYear, field.TypeInt, value)
		_node.Year = value
	}
	if value, ok := _c.mutation.CommitCount(); ok {
		_spec.SetField(memberyearstat.FieldCommitCount, field.TypeInt, value)
		_node.CommitCount = value
	}
	if value, ok := _c.mutation.PrCreated(); ok {
		_spec.SetField(memberyearstat.FieldPrCreated, field.TypeInt, value)
		_node.PrCreated = value
	}
	if value, ok := _c.mutation.PrMerged(); ok {
		_spec.SetField(memberyearstat.FieldPrMerged, field.TypeInt, value)
		_node.PrMerged = value
	}
	if value, ok := _c.mutation.IssueCount(); ok {
		_spec.SetField(memberyearstat.FieldIssueCount, field.TypeInt, value)
		_node.IssueCount = value
	}
	if value, ok := _c.mutation.ReviewCount(); ok {
		_spec.SetField(memberyearstat.FieldReviewCount, field.TypeInt, value)
		_node.ReviewCount = value
	}
	if value, ok := _c.mutation.Additions(); ok {
		_spec.SetField(memberyearstat.FieldAdditions, field.TypeInt, value)
		_node.Additions = value
	}
	if value, ok := _c.mutation.Deletions(); ok {
		_spec.SetField(memberyearstat.FieldDeletions, field.TypeInt, value)
		_node.Deletions = value
	}
	if nodes := _c.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberyearstat.SnapshotTable,
			Columns: []string{memberyearstat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.snapshot_member_year_stats = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemberYearStatCreateBulk is the builder for creating many MemberYearStat entities in bulk.
type MemberYearStatCreateBulk struct {
	config
	err      error
	builders []*MemberYearStatCreate
}

// Save creates the MemberYearStat entities in the database.
func (_c *MemberYearStatCreateBulk) Save(ctx context.Context) ([]*MemberYearStat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemberYearStat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberYearStatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemberYearStatCreateBulk) SaveX(ctx context.Context) []*MemberYearStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberYearStatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberYearStatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
