// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberrepostat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// MemberRepoStatUpdate is the builder for updating MemberRepoStat entities.
type MemberRepoStatUpdate struct {
	config
	hooks    []Hook
	mutation *MemberRepoStatMutation
}

// Where appends a list predicates to the MemberRepoStatUpdate builder.
func (_u *MemberRepoStatUpdate) Where(ps ...predicate.MemberRepoStat) *MemberRepoStatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLogin sets the "login" field.
func (_u *MemberRepoStatUpdate) SetLogin(v string) *MemberRepoStatUpdate {
	_u.mutation.SetLogin(v)
	return _u
}

// SetNillableLogin sets the "login" field if the given value is not nil.
func (_u *MemberRepoStatUpdate) SetNillableLogin(v *string) *MemberRepoStatUpdate {
	if v != nil {
		_u.SetLogin(*v)
	}
	return _u
}

// SetNameWithOwner sets the "name_with_owner" field.
func (_u *MemberRepoStatUpdate) SetNameWithOwner(v string) *MemberRepoStatUpdate {
	_u.mutation.SetNameWithOwner(v)
	return _u
}

// SetNillableNameWithOwner sets the "name_with_owner" field if the given value is not nil.
func (_u *MemberRepoStatUpdate) SetNillableNameWithOwner(v *string) *MemberRepoStatUpdate {
	if v != nil {
		_u.SetNameWithOwner(*v)
	}
	return _u
}

// SetCommitCount sets the "commit_count" field.
func (_u *MemberRepoStatUpdate) SetCommitCount(v int) *MemberRepoStatUpdate {
	_u.mutation.ResetCommitCount()
	_u.mutation.SetCommitCount(v)
	return _u
}

// SetNillableCommitCount sets the "commit_count" field if the given value is not nil.
func (_u *MemberRepoStatUpdate) SetNillableCommitCount(v *int) *MemberRepoStatUpdate {
	if v != nil {
		_u.SetCommitCount(*v)
	}
	return _u
}

// AddCommitCount adds value to the "commit_count" field.
func (_u *MemberRepoStatUpdate) AddCommitCount(v int) *MemberRepoStatUpdate {
	_u.mutation.AddCommitCount(v)
	return _u
}

// SetPrCreated sets the "pr_created" field.
func (_u *MemberRepoStatUpdate) SetPrCreated(v int) *MemberRepoStatUpdate {
	_u.mutation.ResetPrCreated()
	_u.mutation.SetPrCreated(v)
	return _u
}

// SetNillablePrCreated sets the "pr_created" field if the given value is not nil.
func (_u *MemberRepoStatUpdate) SetNillablePrCreated(v *int) *MemberRepoStatUpdate {
	if v != nil {
		_u.SetPrCreated(*v)
	}
	return _u
}

// AddPrCreated adds value to the "pr_created" field.
func (_u *MemberRepoStatUpdate) AddPrCreated(v int) *MemberRepoStatUpdate {
	_u.mutation.AddPrCreated(v)
	return _u
}

// SetPrMerged sets the "pr_merged" field.
func (_u *MemberRepoStatUpdate) SetPrMerged(v int) *MemberRepoStatUpdate {
	_u.mutation.ResetPrMerged()
	_u.mutation.SetPrMerged(v)
	return _u
}

// SetNillablePrMerged sets the "pr_merged" field if the given value is not nil.
func (_u *MemberRepoStatUpdate) SetNillablePrMerged(v *int) *MemberRepoStatUpdate {
	if v != nil {
		_u.SetPrMerged(*v)
	}
	return _u
}

// AddPrMerged adds value to the "pr_merged" field.
func (_u *MemberRepoStatUpdate) AddPrMerged(v int) *MemberRepoStatUpdate {
	_u.mutation.AddPrMerged(v)
	return _u
}

// SetIssueCount sets the "issue_count" field.
func (_u *MemberRepoStatUpdate) SetIssueCount(v int) *MemberRepoStatUpdate {
	_u.mutation.ResetIssueCount()
	_u.mutation.SetIssueCount(v)
	return _u
}

// SetNillableIssueCount sets the "issue_count" field if the given value is not nil.
func (_u *MemberRepoStatUpdate) SetNillableIssueCount(v *int) *MemberRepoStatUpdate {
	if v != nil {
		_u.SetIssueCount(*v)
	}
	return _u
}

// AddIssueCount adds value to the "issue_count" field.
func (_u *MemberRepoStatUpdate) AddIssueCount(v int) *MemberRepoStatUpdate {
	_u.mutation.AddIssueCount(v)
	return _u
}

// SetReviewCount sets the "review_count" field.
func (_u *MemberRepoStatUpdate) SetReviewCount(v int) *MemberRepoStatUpdate {
	_u.mutation.ResetReviewCount()
	_u.mutation.SetReviewCount(v)
	return _u
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_u *MemberRepoStatUpdate) SetNillableReviewCount(v *int) *MemberRepoStatUpdate {
	if v != nil {
		_u.SetReviewCount(*v)
	}
	return _u
}

// AddReviewCount adds value to the "review_count" field.
func (_u *MemberRepoStatUpdate) AddReviewCount(v int) *MemberRepoStatUpdate {
	_u.mutation.AddReviewCount(v)
	return _u
}

// SetAdditions sets the "additions" field.
func (_u *MemberRepoStatUpdate) SetAdditions(v int) *MemberRepoStatUpdate {
	_u.mutation.ResetAdditions()
	_u.mutation.SetAdditions(v)
	return _u
}

// SetNillableAdditions sets the "additions" field if the given value is not nil.
func (_u *MemberRepoStatUpdate) SetNillableAdditions(v *int) *MemberRepoStatUpdate {
	if v != nil {
		_u.SetAdditions(*v)
	}
	return _u
}

// AddAdditions adds value to the "additions" field.
func (_u *MemberRepoStatUpdate) AddAdditions(v int) *MemberRepoStatUpdate {
	_u.mutation.AddAdditions(v)
	return _u
}

// SetDeletions sets the "deletions" field.
func (_u *MemberRepoStatUpdate) SetDeletions(v int) *MemberRepoStatUpdate {
	_u.mutation.ResetDeletions()
	_u.mutation.SetDeletions(v)
	return _u
}

// SetNillableDeletions sets the "deletions" field if the given value is not nil.
func (_u *MemberRepoStatUpdate) SetNillableDeletions(v *int) *MemberRepoStatUpdate {
	if v != nil {
		_u.SetDeletions(*v)
	}
	return _u
}

// AddDeletions adds value to the "deletions" field.
func (_u *MemberRepoStatUpdate) AddDeletions(v int) *MemberRepoStatUpdate {
	_u.mutation.AddDeletions(v)
	return _u
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_u *MemberRepoStatUpdate) SetSnapshotID(id int) *MemberRepoStatUpdate {
	_u.mutation.SetSnapshotID(id)
	return _u
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_u *MemberRepoStatUpdate) SetSnapshot(v *Snapshot) *MemberRepoStatUpdate {
	return _u.SetSnapshotID(v.ID)
}

// Mutation returns the MemberRepoStatMutation object of the builder.
func (_u *MemberRepoStatUpdate) Mutation() *MemberRepoStatMutation {
	return _u.mutation
}

// ClearSnapshot clears the "snapshot" edge to the Snapshot entity.
func (_u *MemberRepoStatUpdate) ClearSnapshot() *MemberRepoStatUpdate {
	_u.mutation.ClearSnapshot()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberRepoStatUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberRepoStatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberRepoStatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberRepoStatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberRepoStatUpdate) check() error {
	if v, ok := _u.mutation.Login(); ok {
		if err := memberrepostat.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "MemberRepoStat.login": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameWithOwner(); ok {
		if err := memberrepostat.NameWithOwnerValidator(v); err != nil {
			return &ValidationError{Name: "name_with_owner", err: fmt.Errorf(`ent: validator failed for field "MemberRepoStat.name_with_owner": %w`, err)}
		}
	}
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberRepoStat.snapshot"`)
	}
	return nil
}

func (_u *MemberRepoStatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberrepostat.Table, memberrepostat.Columns, sqlgraph.NewFieldSpec(memberrepostat.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Login(); ok {
		_spec.SetField(memberrepostat.FieldLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameWithOwner(); ok {
		_spec.SetField(memberrepostat.FieldNameWithOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommitCount(); ok {
		_spec.SetField(memberrepostat.FieldCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommitCount(); ok {
		_spec.AddField(memberrepostat.FieldCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrCreated(); ok {
		_spec.SetField(memberrepostat.FieldPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrCreated(); ok {
		_spec.AddField(memberrepostat.FieldPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrMerged(); ok {
		_spec.SetField(memberrepostat.FieldPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrMerged(); ok {
		_spec.AddField(memberrepostat.FieldPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IssueCount(); ok {
		_spec.SetField(memberrepostat.FieldIssueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIssueCount(); ok {
		_spec.AddField(memberrepostat.FieldIssueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReviewCount(); ok {
		_spec.SetField(memberrepostat.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewCount(); ok {
		_spec.AddField(memberrepostat.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Additions(); ok {
		_spec.SetField(memberrepostat.FieldAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdditions(); ok {
		_spec.AddField(memberrepostat.FieldAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Deletions(); ok {
		_spec.SetField(memberrepostat.FieldDeletions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletions(); ok {
		_spec.AddField(memberrepostat.FieldDeletions, field.TypeInt, value)
	}
	if _u.mutation.SnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberrepostat.SnapshotTable,
			Columns: []string{memberrepostat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberrepostat.SnapshotTable,
			Columns: []string{memberrepostat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberrepostat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberRepoStatUpdateOne is the builder for updating a single MemberRepoStat entity.
type MemberRepoStatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberRepoStatMutation
}

// SetLogin sets the "login" field.
func (_u *MemberRepoStatUpdateOne) SetLogin(v string) *MemberRepoStatUpdateOne {
	_u.mutation.SetLogin(v)
	return _u
}

// SetNillableLogin sets the "login" field if the given value is not nil.
func (_u *MemberRepoStatUpdateOne) SetNillableLogin(v *string) *MemberRepoStatUpdateOne {
	if v != nil {
		_u.SetLogin(*v)
	}
	return _u
}

// SetNameWithOwner sets the "name_with_owner" field.
func (_u *MemberRepoStatUpdateOne) SetNameWithOwner(v string) *MemberRepoStatUpdateOne {
	_u.mutation.SetNameWithOwner(v)
	return _u
}

// SetNillableNameWithOwner sets the "name_with_owner" field if the given value is not nil.
func (_u *MemberRepoStatUpdateOne) SetNillableNameWithOwner(v *string) *MemberRepoStatUpdateOne {
	if v != nil {
		_u.SetNameWithOwner(*v)
	}
	return _u
}

// SetCommitCount sets the "commit_count" field.
func (_u *MemberRepoStatUpdateOne) SetCommitCount(v int) *MemberRepoStatUpdateOne {
	_u.mutation.ResetCommitCount()
	_u.mutation.SetCommitCount(v)
	return _u
}

// SetNillableCommitCount sets the "commit_count" field if the given value is not nil.
func (_u *MemberRepoStatUpdateOne) SetNillableCommitCount(v *int) *MemberRepoStatUpdateOne {
	if v != nil {
		_u.SetCommitCount(*v)
	}
	return _u
}

// AddCommitCount adds value to the "commit_count" field.
func (_u *MemberRepoStatUpdateOne) AddCommitCount(v int) *MemberRepoStatUpdateOne {
	_u.mutation.AddCommitCount(v)
	return _u
}

// SetPrCreated sets the "pr_created" field.
func (_u *MemberRepoStatUpdateOne) SetPrCreated(v int) *MemberRepoStatUpdateOne {
	_u.mutation.ResetPrCreated()
	_u.mutation.SetPrCreated(v)
	return _u
}

// SetNillablePrCreated sets the "pr_created" field if the given value is not nil.
func (_u *MemberRepoStatUpdateOne) SetNillablePrCreated(v *int) *MemberRepoStatUpdateOne {
	if v != nil {
		_u.SetPrCreated(*v)
	}
	return _u
}

// AddPrCreated adds value to the "pr_created" field.
func (_u *MemberRepoStatUpdateOne) AddPrCreated(v int) *MemberRepoStatUpdateOne {
	_u.mutation.AddPrCreated(v)
	return _u
}

// SetPrMerged sets the "pr_merged" field.
func (_u *MemberRepoStatUpdateOne) SetPrMerged(v int) *MemberRepoStatUpdateOne {
	_u.mutation.ResetPrMerged()
	_u.mutation.SetPrMerged(v)
	return _u
}

// SetNillablePrMerged sets the "pr_merged" field if the given value is not nil.
func (_u *MemberRepoStatUpdateOne) SetNillablePrMerged(v *int) *MemberRepoStatUpdateOne {
	if v != nil {
		_u.SetPrMerged(*v)
	}
	return _u
}

// AddPrMerged adds value to the "pr_merged" field.
func (_u *MemberRepoStatUpdateOne) AddPrMerged(v int) *MemberRepoStatUpdateOne {
	_u.mutation.AddPrMerged(v)
	return _u
}

// SetIssueCount sets the "issue_count" field.
func (_u *MemberRepoStatUpdateOne) SetIssueCount(v int) *MemberRepoStatUpdateOne {
	_u.mutation.ResetIssueCount()
	_u.mutation.SetIssueCount(v)
	return _u
}

// SetNillableIssueCount sets the "issue_count" field if the given value is not nil.
func (_u *MemberRepoStatUpdateOne) SetNillableIssueCount(v *int) *MemberRepoStatUpdateOne {
	if v != nil {
		_u.SetIssueCount(*v)
	}
	return _u
}

// AddIssueCount adds value to the "issue_count" field.
func (_u *MemberRepoStatUpdateOne) AddIssueCount(v int) *MemberRepoStatUpdateOne {
	_u.mutation.AddIssueCount(v)
	return _u
}

// SetReviewCount sets the "review_count" field.
func (_u *MemberRepoStatUpdateOne) SetReviewCount(v int) *MemberRepoStatUpdateOne {
	_u.mutation.ResetReviewCount()
	_u.mutation.SetReviewCount(v)
	return _u
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_u *MemberRepoStatUpdateOne) SetNillableReviewCount(v *int) *MemberRepoStatUpdateOne {
	if v != nil {
		_u.SetReviewCount(*v)
	}
	return _u
}

// AddReviewCount adds value to the "review_count" field.
func (_u *MemberRepoStatUpdateOne) AddReviewCount(v int) *MemberRepoStatUpdateOne {
	_u.mutation.AddReviewCount(v)
	return _u
}

// SetAdditions sets the "additions" field.
func (_u *MemberRepoStatUpdateOne) SetAdditions(v int) *MemberRepoStatUpdateOne {
	_u.mutation.ResetAdditions()
	_u.mutation.SetAdditions(v)
	return _u
}

// SetNillableAdditions sets the "additions" field if the given value is not nil.
func (_u *MemberRepoStatUpdateOne) SetNillableAdditions(v *int) *MemberRepoStatUpdateOne {
	if v != nil {
		_u.SetAdditions(*v)
	}
	return _u
}

// AddAdditions adds value to the "additions" field.
func (_u *MemberRepoStatUpdateOne) AddAdditions(v int) *MemberRepoStatUpdateOne {
	_u.mutation.AddAdditions(v)
	return _u
}

// SetDeletions sets the "deletions" field.
func (_u *MemberRepoStatUpdateOne) SetDeletions(v int) *MemberRepoStatUpdateOne {
	_u.mutation.ResetDeletions()
	_u.mutation.SetDeletions(v)
	return _u
}

// SetNillableDeletions sets the "deletions" field if the given value is not nil.
func (_u *MemberRepoStatUpdateOne) SetNillableDeletions(v *int) *MemberRepoStatUpdateOne {
	if v != nil {
		_u.SetDeletions(*v)
	}
	return _u
}

// AddDeletions adds value to the "deletions" field.
func (_u *MemberRepoStatUpdateOne) AddDeletions(v int) *MemberRepoStatUpdateOne {
	_u.mutation.AddDeletions(v)
	return _u
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_u *MemberRepoStatUpdateOne) SetSnapshotID(id int) *MemberRepoStatUpdateOne {
	_u.mutation.SetSnapshotID(id)
	return _u
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_u *MemberRepoStatUpdateOne) SetSnapshot(v *Snapshot) *MemberRepoStatUpdateOne {
	return _u.SetSnapshotID(v.ID)
}

// Mutation returns the MemberRepoStatMutation object of the builder.
func (_u *MemberRepoStatUpdateOne) Mutation() *MemberRepoStatMutation {
	return _u.mutation
}

// ClearSnapshot clears the "snapshot" edge to the Snapshot entity.
func (_u *MemberRepoStatUpdateOne) ClearSnapshot() *MemberRepoStatUpdateOne {
	_u.mutation.ClearSnapshot()
	return _u
}

// Where appends a list predicates to the MemberRepoStatUpdate builder.
func (_u *MemberRepoStatUpdateOne) Where(ps ...predicate.MemberRepoStat) *MemberRepoStatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberRepoStatUpdateOne) Select(field string, fields ...string) *MemberRepoStatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemberRepoStat entity.
func (_u *MemberRepoStatUpdateOne) Save(ctx context.Context) (*MemberRepoStat, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberRepoStatUpdateOne) SaveX(ctx context.Context) *MemberRepoStat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberRepoStatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberRepoStatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberRepoStatUpdateOne) check() error {
	if v, ok := _u.mutation.Login(); ok {
		if err := memberrepostat.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "MemberRepoStat.login": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NameWithOwner(); ok {
		if err := memberrepostat.NameWithOwnerValidator(v); err != nil {
			return &ValidationError{Name: "name_with_owner", err: fmt.Errorf(`ent: validator failed for field "MemberRepoStat.name_with_owner": %w`, err)}
		}
	}
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberRepoStat.snapshot"`)
	}
	return nil
}

func (_u *MemberRepoStatUpdateOne) sqlSave(ctx context.Context) (_node *MemberRepoStat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberrepostat.Table, memberrepostat.Columns, sqlgraph.NewFieldSpec(memberrepostat.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemberRepoStat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberrepostat.FieldID)
		for _, f := range fields {
			if !memberrepostat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memberrepostat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Login(); ok {
		_spec.SetField(memberrepostat.FieldLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.NameWithOwner(); ok {
		_spec.SetField(memberrepostat.FieldNameWithOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommitCount(); ok {
		_spec.SetField(memberrepostat.FieldCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommitCount(); ok {
		_spec.AddField(memberrepostat.FieldCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrCreated(); ok {
		_spec.SetField(memberrepostat.FieldPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrCreated(); ok {
		_spec.AddField(memberrepostat.FieldPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrMerged(); ok {
		_spec.SetField(memberrepostat.FieldPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrMerged(); ok {
		_spec.AddField(memberrepostat.FieldPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IssueCount(); ok {
		_spec.SetField(memberrepostat.FieldIssueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIssueCount(); ok {
		_spec.AddField(memberrepostat.FieldIssueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReviewCount(); ok {
		_spec.SetField(memberrepostat.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewCount(); ok {
		_spec.AddField(memberrepostat.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Additions(); ok {
		_spec.SetField(memberrepostat.FieldAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdditions(); ok {
		_spec.AddField(memberrepostat.FieldAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Deletions(); ok {
		_spec.SetField(memberrepostat.FieldDeletions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletions(); ok {
		_spec.AddField(memberrepostat.FieldDeletions, field.TypeInt, value)
	}
	if _u.mutation.SnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberrepostat.SnapshotTable,
			Columns: []string{memberrepostat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberrepostat.SnapshotTable,
			Columns: []string{memberrepostat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MemberRepoStat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberrepostat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
