// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberdaystat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
)

// MemberDayStatDelete is the builder for deleting a MemberDayStat entity.
type MemberDayStatDelete struct {
	config
	hooks    []Hook
	mutation *MemberDayStatMutation
}

// Where appends a list predicates to the MemberDayStatDelete builder.
func (_d *MemberDayStatDelete) Where(ps ...predicate.MemberDayStat) *MemberDayStatDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MemberDayStatDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemberDayStatDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MemberDayStatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(memberdaystat.Table, sqlgraph.NewFieldSpec(memberdaystat.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MemberDayStatDeleteOne is the builder for deleting a single MemberDayStat entity.
type MemberDayStatDeleteOne struct {
	_d *MemberDayStatDelete
}

// Where appends a list predicates to the MemberDayStatDelete builder.
func (_d *MemberDayStatDeleteOne) Where(ps ...predicate.MemberDayStat) *MemberDayStatDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MemberDayStatDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{memberdaystat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemberDayStatDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
