// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberyearstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
)

// MemberYearStatDelete is the builder for deleting a MemberYearStat entity.
type MemberYearStatDelete struct {
	config
	hooks    []Hook
	mutation *MemberYearStatMutation
}

// Where appends a list predicates to the MemberYearStatDelete builder.
func (_d *MemberYearStatDelete) Where(ps ...predicate.MemberYearStat) *MemberYearStatDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MemberYearStatDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemberYearStatDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MemberYearStatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(memberyearstat.Table, sqlgraph.NewFieldSpec(memberyearstat.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MemberYearStatDeleteOne is the builder for deleting a single MemberYearStat entity.
type MemberYearStatDeleteOne struct {
	_d *MemberYearStatDelete
}

// Where appends a list predicates to the MemberYearStatDelete builder.
func (_d *MemberYearStatDeleteOne) Where(ps ...predicate.MemberYearStat) *MemberYearStatDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MemberYearStatDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{memberyearstat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemberYearStatDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
