// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberyearstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// MemberYearStatUpdate is the builder for updating MemberYearStat entities.
type MemberYearStatUpdate struct {
	config
	hooks    []Hook
	mutation *MemberYearStatMutation
}

// Where appends a list predicates to the MemberYearStatUpdate builder.
func (_u *MemberYearStatUpdate) Where(ps ...predicate.MemberYearStat) *MemberYearStatUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLogin sets the "login" field.
func (_u *MemberYearStatUpdate) SetLogin(v string) *MemberYearStatUpdate {
	_u.mutation.SetLogin(v)
	return _u
}

// SetNillableLogin sets the "login" field if the given value is not nil.
func (_u *MemberYearStatUpdate) SetNillableLogin(v *string) *MemberYearStatUpdate {
	if v != nil {
		_u.SetLogin(*v)
	}
	return _u
}

// SetYear sets the "year" field.
func (_u *MemberYearStatUpdate) SetYear(v int) *MemberYearStatUpdate {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *MemberYearStatUpdate) SetNillableYear(v *int) *MemberYearStatUpdate {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *MemberYearStatUpdate) AddYear(v int) *MemberYearStatUpdate {
	_u.mutation.AddYear(v)
	return _u
}

// SetCommitCount sets the "commit_count" field.
func (_u *MemberYearStatUpdate) SetCommitCount(v int) *MemberYearStatUpdate {
	_u.mutation.ResetCommitCount()
	_u.mutation.SetCommitCount(v)
	return _u
}

// SetNillableCommitCount sets the "commit_count" field if the given value is not nil.
func (_u *MemberYearStatUpdate) SetNillableCommitCount(v *int) *MemberYearStatUpdate {
	if v != nil {
		_u.SetCommitCount(*v)
	}
	return _u
}

// AddCommitCount adds value to the "commit_count" field.
func (_u *MemberYearStatUpdate) AddCommitCount(v int) *MemberYearStatUpdate {
	_u.mutation.AddCommitCount(v)
	return _u
}

// SetPrCreated sets the "pr_created" field.
func (_u *MemberYearStatUpdate) SetPrCreated(v int) *MemberYearStatUpdate {
	_u.mutation.ResetPrCreated()
	_u.mutation.SetPrCreated(v)
	return _u
}

// SetNillablePrCreated sets the "pr_created" field if the given value is not nil.
func (_u *MemberYearStatUpdate) SetNillablePrCreated(v *int) *MemberYearStatUpdate {
	if v != nil {
		_u.SetPrCreated(*v)
	}
	return _u
}

// AddPrCreated adds value to the "pr_created" field.
func (_u *MemberYearStatUpdate) AddPrCreated(v int) *MemberYearStatUpdate {
	_u.mutation.AddPrCreated(v)
	return _u
}

// SetPrMerged sets the "pr_merged" field.
func (_u *MemberYearStatUpdate) SetPrMerged(v int) *MemberYearStatUpdate {
	_u.mutation.ResetPrMerged()
	_u.mutation.SetPrMerged(v)
	return _u
}

// SetNillablePrMerged sets the "pr_merged" field if the given value is not nil.
func (_u *MemberYearStatUpdate) SetNillablePrMerged(v *int) *MemberYearStatUpdate {
	if v != nil {
		_u.SetPrMerged(*v)
	}
	return _u
}

// AddPrMerged adds value to the "pr_merged" field.
func (_u *MemberYearStatUpdate) AddPrMerged(v int) *MemberYearStatUpdate {
	_u.mutation.AddPrMerged(v)
	return _u
}

// SetIssueCount sets the "issue_count" field.
func (_u *MemberYearStatUpdate) SetIssueCount(v int) *MemberYearStatUpdate {
	_u.mutation.ResetIssueCount()
	_u.mutation.SetIssueCount(v)
	return _u
}

// SetNillableIssueCount sets the "issue_count" field if the given value is not nil.
func (_u *MemberYearStatUpdate) SetNillableIssueCount(v *int) *MemberYearStatUpdate {
	if v != nil {
		_u.SetIssueCount(*v)
	}
	return _u
}

// AddIssueCount adds value to the "issue_count" field.
func (_u *MemberYearStatUpdate) AddIssueCount(v int) *MemberYearStatUpdate {
	_u.mutation.AddIssueCount(v)
	return _u
}

// SetReviewCount sets the "review_count" field.
func (_u *MemberYearStatUpdate) SetReviewCount(v int) *MemberYearStatUpdate {
	_u.mutation.ResetReviewCount()
	_u.mutation.SetReviewCount(v)
	return _u
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_u *MemberYearStatUpdate) SetNillableReviewCount(v *int) *MemberYearStatUpdate {
	if v != nil {
		_u.SetReviewCount(*v)
	}
	return _u
}

// AddReviewCount adds value to the "review_count" field.
func (_u *MemberYearStatUpdate) AddReviewCount(v int) *MemberYearStatUpdate {
	_u.mutation.AddReviewCount(v)
	return _u
}

// SetAdditions sets the "additions" field.
func (_u *MemberYearStatUpdate) SetAdditions(v int) *MemberYearStatUpdate {
	_u.mutation.ResetAdditions()
	_u.mutation.SetAdditions(v)
	return _u
}

// SetNillableAdditions sets the "additions" field if the given value is not nil.
func (_u *MemberYearStatUpdate) SetNillableAdditions(v *int) *MemberYearStatUpdate {
	if v != nil {
		_u.SetAdditions(*v)
	}
	return _u
}

// AddAdditions adds value to the "additions" field.
func (_u *MemberYearStatUpdate) AddAdditions(v int) *MemberYearStatUpdate {
	_u.mutation.AddAdditions(v)
	return _u
}

// SetDeletions sets the "deletions" field.
func (_u *MemberYearStatUpdate) SetDeletions(v int) *MemberYearStatUpdate {
	_u.mutation.ResetDeletions()
	_u.mutation.SetDeletions(v)
	return _u
}

// SetNillableDeletions sets the "deletions" field if the given value is not nil.
func (_u *MemberYearStatUpdate) SetNillableDeletions(v *int) *MemberYearStatUpdate {
	if v != nil {
		_u.SetDeletions(*v)
	}
	return _u
}

// AddDeletions adds value to the "deletions" field.
func (_u *MemberYearStatUpdate) AddDeletions(v int) *MemberYearStatUpdate {
	_u.mutation.AddDeletions(v)
	return _u
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_u *MemberYearStatUpdate) SetSnapshotID(id int) *MemberYearStatUpdate {
	_u.mutation.SetSnapshotID(id)
	return _u
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_u *MemberYearStatUpdate) SetSnapshot(v *Snapshot) *MemberYearStatUpdate {
	return _u.SetSnapshotID(v.ID)
}

// Mutation returns the MemberYearStatMutation object of the builder.
func (_u *MemberYearStatUpdate) Mutation() *MemberYearStatMutation {
	return _u.mutation
}

// ClearSnapshot clears the "snapshot" edge to the Snapshot entity.
func (_u *MemberYearStatUpdate) ClearSnapshot() *MemberYearStatUpdate {
	_u.mutation.ClearSnapshot()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MemberYearStatUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberYearStatUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MemberYearStatUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberYearStatUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberYearStatUpdate) check() error {
	if v, ok := _u.mutation.Login(); ok {
		if err := memberyearstat.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "MemberYearStat.login": %w`, err)}
		}
	}
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberYearStat.snapshot"`)
	}
	return nil
}

func (_u *MemberYearStatUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberyearstat.Table, memberyearstat.Columns, sqlgraph.NewFieldSpec(memberyearstat.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Login(); ok {
		_spec.SetField(memberyearstat.FieldLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(memberyearstat.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(memberyearstat.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommitCount(); ok {
		_spec.SetField(memberyearstat.FieldCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommitCount(); ok {
		_spec.AddField(memberyearstat.FieldCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrCreated(); ok {
		_spec.SetField(memberyearstat.FieldPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrCreated(); ok {
		_spec.AddField(memberyearstat.FieldPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrMerged(); ok {
		_spec.SetField(memberyearstat.FieldPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrMerged(); ok {
		_spec.AddField(memberyearstat.FieldPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IssueCount(); ok {
		_spec.SetField(memberyearstat.FieldIssueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIssueCount(); ok {
		_spec.AddField(memberyearstat.FieldIssueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReviewCount(); ok {
		_spec.SetField(memberyearstat.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewCount(); ok {
		_spec.AddField(memberyearstat.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Additions(); ok {
		_spec.SetField(memberyearstat.FieldAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdditions(); ok {
		_spec.AddField(memberyearstat.FieldAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Deletions(); ok {
		_spec.SetField(memberyearstat.FieldDeletions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletions(); ok {
		_spec.AddField(memberyearstat.FieldDeletions, field.TypeInt, value)
	}
	if _u.mutation.SnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberyearstat.SnapshotTable,
			Columns: []string{memberyearstat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberyearstat.SnapshotTable,
			Columns: []string{memberyearstat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberyearstat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MemberYearStatUpdateOne is the builder for updating a single MemberYearStat entity.
type MemberYearStatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemberYearStatMutation
}

// SetLogin sets the "login" field.
func (_u *MemberYearStatUpdateOne) SetLogin(v string) *MemberYearStatUpdateOne {
	_u.mutation.SetLogin(v)
	return _u
}

// SetNillableLogin sets the "login" field if the given value is not nil.
func (_u *MemberYearStatUpdateOne) SetNillableLogin(v *string) *MemberYearStatUpdateOne {
	if v != nil {
		_u.SetLogin(*v)
	}
	return _u
}

// SetYear sets the "year" field.
func (_u *MemberYearStatUpdateOne) SetYear(v int) *MemberYearStatUpdateOne {
	_u.mutation.ResetYear()
	_u.mutation.SetYear(v)
	return _u
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (_u *MemberYearStatUpdateOne) SetNillableYear(v *int) *MemberYearStatUpdateOne {
	if v != nil {
		_u.SetYear(*v)
	}
	return _u
}

// AddYear adds value to the "year" field.
func (_u *MemberYearStatUpdateOne) AddYear(v int) *MemberYearStatUpdateOne {
	_u.mutation.AddYear(v)
	return _u
}

// SetCommitCount sets the "commit_count" field.
func (_u *MemberYearStatUpdateOne) SetCommitCount(v int) *MemberYearStatUpdateOne {
	_u.mutation.ResetCommitCount()
	_u.mutation.SetCommitCount(v)
	return _u
}

// SetNillableCommitCount sets the "commit_count" field if the given value is not nil.
func (_u *MemberYearStatUpdateOne) SetNillableCommitCount(v *int) *MemberYearStatUpdateOne {
	if v != nil {
		_u.SetCommitCount(*v)
	}
	return _u
}

// AddCommitCount adds value to the "commit_count" field.
func (_u *MemberYearStatUpdateOne) AddCommitCount(v int) *MemberYearStatUpdateOne {
	_u.mutation.AddCommitCount(v)
	return _u
}

// SetPrCreated sets the "pr_created" field.
func (_u *MemberYearStatUpdateOne) SetPrCreated(v int) *MemberYearStatUpdateOne {
	_u.mutation.ResetPrCreated()
	_u.mutation.SetPrCreated(v)
	return _u
}

// SetNillablePrCreated sets the "pr_created" field if the given value is not nil.
func (_u *MemberYearStatUpdateOne) SetNillablePrCreated(v *int) *MemberYearStatUpdateOne {
	if v != nil {
		_u.SetPrCreated(*v)
	}
	return _u
}

// AddPrCreated adds value to the "pr_created" field.
func (_u *MemberYearStatUpdateOne) AddPrCreated(v int) *MemberYearStatUpdateOne {
	_u.mutation.AddPrCreated(v)
	return _u
}

// SetPrMerged sets the "pr_merged" field.
func (_u *MemberYearStatUpdateOne) SetPrMerged(v int) *MemberYearStatUpdateOne {
	_u.mutation.ResetPrMerged()
	_u.mutation.SetPrMerged(v)
	return _u
}

// SetNillablePrMerged sets the "pr_merged" field if the given value is not nil.
func (_u *MemberYearStatUpdateOne) SetNillablePrMerged(v *int) *MemberYearStatUpdateOne {
	if v != nil {
		_u.SetPrMerged(*v)
	}
	return _u
}

// AddPrMerged adds value to the "pr_merged" field.
func (_u *MemberYearStatUpdateOne) AddPrMerged(v int) *MemberYearStatUpdateOne {
	_u.mutation.AddPrMerged(v)
	return _u
}

// SetIssueCount sets the "issue_count" field.
func (_u *MemberYearStatUpdateOne) SetIssueCount(v int) *MemberYearStatUpdateOne {
	_u.mutation.ResetIssueCount()
	_u.mutation.SetIssueCount(v)
	return _u
}

// SetNillableIssueCount sets the "issue_count" field if the given value is not nil.
func (_u *MemberYearStatUpdateOne) SetNillableIssueCount(v *int) *MemberYearStatUpdateOne {
	if v != nil {
		_u.SetIssueCount(*v)
	}
	return _u
}

// AddIssueCount adds value to the "issue_count" field.
func (_u *MemberYearStatUpdateOne) AddIssueCount(v int) *MemberYearStatUpdateOne {
	_u.mutation.AddIssueCount(v)
	return _u
}

// SetReviewCount sets the "review_count" field.
func (_u *MemberYearStatUpdateOne) SetReviewCount(v int) *MemberYearStatUpdateOne {
	_u.mutation.ResetReviewCount()
	_u.mutation.SetReviewCount(v)
	return _u
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_u *MemberYearStatUpdateOne) SetNillableReviewCount(v *int) *MemberYearStatUpdateOne {
	if v != nil {
		_u.SetReviewCount(*v)
	}
	return _u
}

// AddReviewCount adds value to the "review_count" field.
func (_u *MemberYearStatUpdateOne) AddReviewCount(v int) *MemberYearStatUpdateOne {
	_u.mutation.AddReviewCount(v)
	return _u
}

// SetAdditions sets the "additions" field.
func (_u *MemberYearStatUpdateOne) SetAdditions(v int) *MemberYearStatUpdateOne {
	_u.mutation.ResetAdditions()
	_u.mutation.SetAdditions(v)
	return _u
}

// SetNillableAdditions sets the "additions" field if the given value is not nil.
func (_u *MemberYearStatUpdateOne) SetNillableAdditions(v *int) *MemberYearStatUpdateOne {
	if v != nil {
		_u.SetAdditions(*v)
	}
	return _u
}

// AddAdditions adds value to the "additions" field.
func (_u *MemberYearStatUpdateOne) AddAdditions(v int) *MemberYearStatUpdateOne {
	_u.mutation.AddAdditions(v)
	return _u
}

// SetDeletions sets the "deletions" field.
func (_u *MemberYearStatUpdateOne) SetDeletions(v int) *MemberYearStatUpdateOne {
	_u.mutation.ResetDeletions()
	_u.mutation.SetDeletions(v)
	return _u
}

// SetNillableDeletions sets the "deletions" field if the given value is not nil.
func (_u *MemberYearStatUpdateOne) SetNillableDeletions(v *int) *MemberYearStatUpdateOne {
	if v != nil {
		_u.SetDeletions(*v)
	}
	return _u
}

// AddDeletions adds value to the "deletions" field.
func (_u *MemberYearStatUpdateOne) AddDeletions(v int) *MemberYearStatUpdateOne {
	_u.mutation.AddDeletions(v)
	return _u
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_u *MemberYearStatUpdateOne) SetSnapshotID(id int) *MemberYearStatUpdateOne {
	_u.mutation.SetSnapshotID(id)
	return _u
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_u *MemberYearStatUpdateOne) SetSnapshot(v *Snapshot) *MemberYearStatUpdateOne {
	return _u.SetSnapshotID(v.ID)
}

// Mutation returns the MemberYearStatMutation object of the builder.
func (_u *MemberYearStatUpdateOne) Mutation() *MemberYearStatMutation {
	return _u.mutation
}

// ClearSnapshot clears the "snapshot" edge to the Snapshot entity.
func (_u *MemberYearStatUpdateOne) ClearSnapshot() *MemberYearStatUpdateOne {
	_u.mutation.ClearSnapshot()
	return _u
}

// Where appends a list predicates to the MemberYearStatUpdate builder.
func (_u *MemberYearStatUpdateOne) Where(ps ...predicate.MemberYearStat) *MemberYearStatUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MemberYearStatUpdateOne) Select(field string, fields ...string) *MemberYearStatUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MemberYearStat entity.
func (_u *MemberYearStatUpdateOne) Save(ctx context.Context) (*MemberYearStat, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MemberYearStatUpdateOne) SaveX(ctx context.Context) *MemberYearStat {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MemberYearStatUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MemberYearStatUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MemberYearStatUpdateOne) check() error {
	if v, ok := _u.mutation.Login(); ok {
		if err := memberyearstat.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "MemberYearStat.login": %w`, err)}
		}
	}
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MemberYearStat.snapshot"`)
	}
	return nil
}

func (_u *MemberYearStatUpdateOne) sqlSave(ctx context.Context) (_node *MemberYearStat, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberyearstat.Table, memberyearstat.Columns, sqlgraph.NewFieldSpec(memberyearstat.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemberYearStat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberyearstat.FieldID)
		for _, f := range fields {
			if !memberyearstat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memberyearstat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Login(); ok {
		_spec.SetField(memberyearstat.FieldLogin, field.TypeString, value)
	}
	if value, ok := _u.mutation.Year(); ok {
		_spec.SetField(memberyearstat.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedYear(); ok {
		_spec.AddField(memberyearstat.FieldYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommitCount(); ok {
		_spec.SetField(memberyearstat.FieldCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommitCount(); ok {
		_spec.AddField(memberyearstat.FieldCommitCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrCreated(); ok {
		_spec.SetField(memberyearstat.FieldPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrCreated(); ok {
		_spec.AddField(memberyearstat.FieldPrCreated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PrMerged(); ok {
		_spec.SetField(memberyearstat.FieldPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPrMerged(); ok {
		_spec.AddField(memberyearstat.FieldPrMerged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IssueCount(); ok {
		_spec.SetField(memberyearstat.FieldIssueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIssueCount(); ok {
		_spec.AddField(memberyearstat.FieldIssueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ReviewCount(); ok {
		_spec.SetField(memberyearstat.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReviewCount(); ok {
		_spec.AddField(memberyearstat.FieldReviewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Additions(); ok {
		_spec.SetField(memberyearstat.FieldAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdditions(); ok {
		_spec.AddField(memberyearstat.FieldAdditions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Deletions(); ok {
		_spec.SetField(memberyearstat.FieldDeletions, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletions(); ok {
		_spec.AddField(memberyearstat.FieldDeletions, field.TypeInt, value)
	}
	if _u.mutation.SnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberyearstat.SnapshotTable,
			Columns: []string{memberyearstat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberyearstat.SnapshotTable,
			Columns: []string{memberyearstat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MemberYearStat{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberyearstat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
