// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberrepostat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// MemberRepoStatCreate is the builder for creating a MemberRepoStat entity.
type MemberRepoStatCreate struct {
	config
	mutation *MemberRepoStatMutation
	hooks    []Hook
}

// SetLogin sets the "login" field.
func (_c *MemberRepoStatCreate) SetLogin(v string) *MemberRepoStatCreate {
	_c.mutation.SetLogin(v)
	return _c
}

// SetNameWithOwner sets the "name_with_owner" field.
func (_c *MemberRepoStatCreate) SetNameWithOwner(v string) *MemberRepoStatCreate {
	_c.mutation.SetNameWithOwner(v)
	return _c
}

// SetCommitCount sets the "commit_count" field.
func (_c *MemberRepoStatCreate) SetCommitCount(v int) *MemberRepoStatCreate {
	_c.mutation.SetCommitCount(v)
	return _c
}

// SetNillableCommitCount sets the "commit_count" field if the given value is not nil.
func (_c *MemberRepoStatCreate) SetNillableCommitCount(v *int) *MemberRepoStatCreate {
	if v != nil {
		_c.SetCommitCount(*v)
	}
	return _c
}

// SetPrCreated sets the "pr_created" field.
func (_c *MemberRepoStatCreate) SetPrCreated(v int) *MemberRepoStatCreate {
	_c.mutation.SetPrCreated(v)
	return _c
}

// SetNillablePrCreated sets the "pr_created" field if the given value is not nil.
func (_c *MemberRepoStatCreate) SetNillablePrCreated(v *int) *MemberRepoStatCreate {
	if v != nil {
		_c.SetPrCreated(*v)
	}
	return _c
}

// SetPrMerged sets the "pr_merged" field.
func (_c *MemberRepoStatCreate) SetPrMerged(v int) *MemberRepoStatCreate {
	_c.mutation.SetPrMerged(v)
	return _c
}

// SetNillablePrMerged sets the "pr_merged" field if the given value is not nil.
func (_c *MemberRepoStatCreate) SetNillablePrMerged(v *int) *MemberRepoStatCreate {
	if v != nil {
		_c.SetPrMerged(*v)
	}
	return _c
}

// SetIssueCount sets the "issue_count" field.
func (_c *MemberRepoStatCreate) SetIssueCount(v int) *MemberRepoStatCreate {
	_c.mutation.SetIssueCount(v)
	return _c
}

// SetNillableIssueCount sets the "issue_count" field if the given value is not nil.
func (_c *MemberRepoStatCreate) SetNillableIssueCount(v *int) *MemberRepoStatCreate {
	if v != nil {
		_c.SetIssueCount(*v)
	}
	return _c
}

// SetReviewCount sets the "review_count" field.
func (_c *MemberRepoStatCreate) SetReviewCount(v int) *MemberRepoStatCreate {
	_c.mutation.SetReviewCount(v)
	return _c
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_c *MemberRepoStatCreate) SetNillableReviewCount(v *int) *MemberRepoStatCreate {
	if v != nil {
		_c.SetReviewCount(*v)
	}
	return _c
}

// SetAdditions sets the "additions" field.
func (_c *MemberRepoStatCreate) SetAdditions(v int) *MemberRepoStatCreate {
	_c.mutation.SetAdditions(v)
	return _c
}

// SetNillableAdditions sets the "additions" field if the given value is not nil.
func (_c *MemberRepoStatCreate) SetNillableAdditions(v *int) *MemberRepoStatCreate {
	if v != nil {
		_c.SetAdditions(*v)
	}
	return _c
}

// SetDeletions sets the "deletions" field.
func (_c *MemberRepoStatCreate) SetDeletions(v int) *MemberRepoStatCreate {
	_c.mutation.SetDeletions(v)
	return _c
}

// SetNillableDeletions sets the "deletions" field if the given value is not nil.
func (_c *MemberRepoStatCreate) SetNillableDeletions(v *int) *MemberRepoStatCreate {
	if v != nil {
		_c.SetDeletions(*v)
	}
	return _c
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_c *MemberRepoStatCreate) SetSnapshotID(id int) *MemberRepoStatCreate {
	_c.mutation.SetSnapshotID(id)
	return _c
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_c *MemberRepoStatCreate) SetSnapshot(v *Snapshot) *MemberRepoStatCreate {
	return _c.SetSnapshotID(v.ID)
}

// Mutation returns the MemberRepoStatMutation object of the builder.
func (_c *MemberRepoStatCreate) Mutation() *MemberRepoStatMutation {
	return _c.mutation
}

// Save creates the MemberRepoStat in the database.
func (_c *MemberRepoStatCreate) Save(ctx context.Context) (*MemberRepoStat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemberRepoStatCreate) SaveX(ctx context.Context) *MemberRepoStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberRepoStatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberRepoStatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemberRepoStatCreate) defaults() {
	if _, ok := _c.mutation.CommitCount(); !ok {
		v := memberrepostat.DefaultCommitCount
		_c.mutation.SetCommitCount(v)
	}
	if _, ok := _c.mutation.PrCreated(); !ok {
		v := memberrepostat.DefaultPrCreated
		_c.mutation.SetPrCreated(v)
	}
	if _, ok := _c.mutation.PrMerged(); !ok {
		v := memberrepostat.DefaultPrMerged
		_c.mutation.SetPrMerged(v)
	}
	if _, ok := _c.mutation.IssueCount(); !ok {
		v := memberrepostat.DefaultIssueCount
		_c.mutation.SetIssueCount(v)
	}
	if _, ok := _c.mutation.ReviewCount(); !ok {
		v := memberrepostat.DefaultReviewCount
		_c.mutation.SetReviewCount(v)
	}
	if _, ok := _c.mutation.Additions(); !ok {
		v := memberrepostat.DefaultAdditions
		_c.mutation.SetAdditions(v)
	}
	if _, ok := _c.mutation.Deletions(); !ok {
		v := memberrepostat.DefaultDeletions
		_c.mutation.SetDeletions(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemberRepoStatCreate) check() error {
	if _, ok := _c.mutation.Login(); !ok {
		return &ValidationError{Name: "login", err: errors.New(`ent: missing required field "MemberRepoStat.login"`)}
	}
	if v, ok := _c.mutation.Login(); ok {
		if err := memberrepostat.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "MemberRepoStat.login": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameWithOwner(); !ok {
		return &ValidationError{Name: "name_with_owner", err: errors.New(`ent: missing required field "MemberRepoStat.name_with_owner"`)}
	}
	if v, ok := _c.mutation.NameWithOwner(); ok {
		if err := memberrepostat.NameWithOwnerValidator(v); err != nil {
			return &ValidationError{Name: "name_with_owner", err: fmt.Errorf(`ent: validator failed for field "MemberRepoStat.name_with_owner": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CommitCount(); !ok {
		return &ValidationError{Name: "commit_count", err: errors.New(`ent: missing required field "MemberRepoStat.commit_count"`)}
	}
	if _, ok := _c.mutation.PrCreated(); !ok {
		return &ValidationError{Name: "pr_created", err: errors.New(`ent: missing required field "MemberRepoStat.pr_created"`)}
	}
	if _, ok := _c.mutation.PrMerged(); !ok {
		return &ValidationError{Name: "pr_merged", err: errors.New(`ent: missing required field "MemberRepoStat.pr_merged"`)}
	}
	if _, ok := _c.mutation.IssueCount(); !ok {
		return &ValidationError{Name: "issue_count", err: errors.New(`ent: missing required field "MemberRepoStat.issue_count"`)}
	}
	if _, ok := _c.mutation.ReviewCount(); !ok {
		return &ValidationError{Name: "review_count", err: errors.New(`ent: missing required field "MemberRepoStat.review_count"`)}
	}
	if _, ok := _c.mutation.Additions(); !ok {
		return &ValidationError{Name: "additions", err: errors.New(`ent: missing required field "MemberRepoStat.additions"`)}
	}
	if _, ok := _c.mutation.Deletions(); !ok {
		return &ValidationError{Name: "deletions", err: errors.New(`ent: missing required field "MemberRepoStat.deletions"`)}
	}
	if len(_c.mutation.SnapshotIDs()) == 0 {
		return &ValidationError{Name: "snapshot", err: errors.New(`ent: missing required edge "MemberRepoStat.snapshot"`)}
	}
	return nil
}

func (_c *MemberRepoStatCreate) sqlSave(ctx context.Context) (*MemberRepoStat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemberRepoStatCreate) createSpec() (*MemberRepoStat, *sqlgraph.CreateSpec) {
	var (
		_node = &MemberRepoStat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memberrepostat.Table, sqlgraph.NewFieldSpec(memberrepostat.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Login(); ok {
		_spec.SetField(memberrepostat.FieldLogin, field.TypeString, value)
		_node.Login = value
	}
	if value, ok := _c.mutation.NameWithOwner(); ok {
		_spec.SetField(memberrepostat.FieldNameWithOwner, field.TypeString, value)
		_node.NameWithOwner = value
	}
	if value, ok := _c.mutation.CommitCount(); ok {
		_spec.SetField(memberrepostat.FieldCommitCount, field.TypeInt, value)
		_node.CommitCount = value
	}
	if value, ok := _c.mutation.PrCreated(); ok {
		_spec.SetField(memberrepostat.FieldPrCreated, field.TypeInt, value)
		_node.PrCreated = value
	}
	if value, ok := _c.mutation.PrMerged(); ok {
		_spec.SetField(memberrepostat.FieldPrMerged, field.TypeInt, value)
		_node.PrMerged = value
	}
	if value, ok := _c.mutation.IssueCount(); ok {
		_spec.SetField(memberrepostat.FieldIssueCount, field.TypeInt, value)
		_node.IssueCount = value
	}
	if value, ok := _c.mutation.ReviewCount(); ok {
		_spec.SetField(memberrepostat.FieldReviewCount, field.TypeInt, value)
		_node.ReviewCount = value
	}
	if value, ok := _c.mutation.Additions(); ok {
		_spec.SetField(memberrepostat.FieldAdditions, field.TypeInt, value)
		_node.Additions = value
	}
	if value, ok := _c.mutation.Deletions(); ok {
		_spec.SetField(memberrepostat.FieldDeletions, field.TypeInt, value)
		_node.Deletions = value
	}
	if nodes := _c.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberrepostat.SnapshotTable,
			Columns: []string{memberrepostat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.snapshot_member_repo_stats = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemberRepoStatCreateBulk is the builder for creating many MemberRepoStat entities in bulk.
type MemberRepoStatCreateBulk struct {
	config
	err      error
	builders []*MemberRepoStatCreate
}

// Save creates the MemberRepoStat entities in the database.
func (_c *MemberRepoStatCreateBulk) Save(ctx context.Context) ([]*MemberRepoStat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemberRepoStat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberRepoStatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemberRepoStatCreateBulk) SaveX(ctx context.Context) []*MemberRepoStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberRepoStatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberRepoStatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
