// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberrepostat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
)

// MemberRepoStatDelete is the builder for deleting a MemberRepoStat entity.
type MemberRepoStatDelete struct {
	config
	hooks    []Hook
	mutation *MemberRepoStatMutation
}

// Where appends a list predicates to the MemberRepoStatDelete builder.
func (_d *MemberRepoStatDelete) Where(ps ...predicate.MemberRepoStat) *MemberRepoStatDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MemberRepoStatDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemberRepoStatDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MemberRepoStatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(memberrepostat.Table, sqlgraph.NewFieldSpec(memberrepostat.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MemberRepoStatDeleteOne is the builder for deleting a single MemberRepoStat entity.
type MemberRepoStatDeleteOne struct {
	_d *MemberRepoStatDelete
}

// Where appends a list predicates to the MemberRepoStatDelete builder.
func (_d *MemberRepoStatDeleteOne) Where(ps ...predicate.MemberRepoStat) *MemberRepoStatDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MemberRepoStatDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{memberrepostat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MemberRepoStatDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
