// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// MemberStatCreate is the builder for creating a MemberStat entity.
type MemberStatCreate struct {
	config
	mutation *MemberStatMutation
	hooks    []Hook
}

// SetLogin sets the "login" field.
func (_c *MemberStatCreate) SetLogin(v string) *MemberStatCreate {
	_c.mutation.SetLogin(v)
	return _c
}

// SetTotalCommits sets the "total_commits" field.
func (_c *MemberStatCreate) SetTotalCommits(v int) *MemberStatCreate {
	_c.mutation.SetTotalCommits(v)
	return _c
}

// SetNillableTotalCommits sets the "total_commits" field if the given value is not nil.
func (_c *MemberStatCreate) SetNillableTotalCommits(v *int) *MemberStatCreate {
	if v != nil {
		_c.SetTotalCommits(*v)
	}
	return _c
}

// SetTotalPrCreated sets the "total_pr_created" field.
func (_c *MemberStatCreate) SetTotalPrCreated(v int) *MemberStatCreate {
	_c.mutation.SetTotalPrCreated(v)
	return _c
}

// SetNillableTotalPrCreated sets the "total_pr_created" field if the given value is not nil.
func (_c *MemberStatCreate) SetNillableTotalPrCreated(v *int) *MemberStatCreate {
	if v != nil {
		_c.SetTotalPrCreated(*v)
	}
	return _c
}

// SetTotalPrMerged sets the "total_pr_merged" field.
func (_c *MemberStatCreate) SetTotalPrMerged(v int) *MemberStatCreate {
	_c.mutation.SetTotalPrMerged(v)
	return _c
}

// SetNillableTotalPrMerged sets the "total_pr_merged" field if the given value is not nil.
func (_c *MemberStatCreate) SetNillableTotalPrMerged(v *int) *MemberStatCreate {
	if v != nil {
		_c.SetTotalPrMerged(*v)
	}
	return _c
}

// SetTotalIssues sets the "total_issues" field.
func (_c *MemberStatCreate) SetTotalIssues(v int) *MemberStatCreate {
	_c.mutation.SetTotalIssues(v)
	return _c
}

// SetNillableTotalIssues sets the "total_issues" field if the given value is not nil.
func (_c *MemberStatCreate) SetNillableTotalIssues(v *int) *MemberStatCreate {
	if v != nil {
		_c.SetTotalIssues(*v)
	}
	return _c
}

// SetTotalReviews sets the "total_reviews" field.
func (_c *MemberStatCreate) SetTotalReviews(v int) *MemberStatCreate {
	_c.mutation.SetTotalReviews(v)
	return _c
}

// SetNillableTotalReviews sets the "total_reviews" field if the given value is not nil.
func (_c *MemberStatCreate) SetNillableTotalReviews(v *int) *MemberStatCreate {
	if v != nil {
		_c.SetTotalReviews(*v)
	}
	return _c
}

// SetTotalAdditions sets the "total_additions" field.
func (_c *MemberStatCreate) SetTotalAdditions(v int) *MemberStatCreate {
	_c.mutation.SetTotalAdditions(v)
	return _c
}

// SetNillableTotalAdditions sets the "total_additions" field if the given value is not nil.
func (_c *MemberStatCreate) SetNillableTotalAdditions(v *int) *MemberStatCreate {
	if v != nil {
		_c.SetTotalAdditions(*v)
	}
	return _c
}

// SetTotalDeletions sets the "total_deletions" field.
func (_c *MemberStatCreate) SetTotalDeletions(v int) *MemberStatCreate {
	_c.mutation.SetTotalDeletions(v)
	return _c
}

// SetNillableTotalDeletions sets the "total_deletions" field if the given value is not nil.
func (_c *MemberStatCreate) SetNillableTotalDeletions(v *int) *MemberStatCreate {
	if v != nil {
		_c.SetTotalDeletions(*v)
	}
	return _c
}

// SetFirstActivityYear sets the "first_activity_year" field.
func (_c *MemberStatCreate) SetFirstActivityYear(v int) *MemberStatCreate {
	_c.mutation.SetFirstActivityYear(v)
	return _c
}

// SetNillableFirstActivityYear sets the "first_activity_year" field if the given value is not nil.
func (_c *MemberStatCreate) SetNillableFirstActivityYear(v *int) *MemberStatCreate {
	if v != nil {
		_c.SetFirstActivityYear(*v)
	}
	return _c
}

// SetPeakActivityYear sets the "peak_activity_year" field.
func (_c *MemberStatCreate) SetPeakActivityYear(v int) *MemberStatCreate {
	_c.mutation.SetPeakActivityYear(v)
	return _c
}

// SetNillablePeakActivityYear sets the "peak_activity_year" field if the given value is not nil.
func (_c *MemberStatCreate) SetNillablePeakActivityYear(v *int) *MemberStatCreate {
	if v != nil {
		_c.SetPeakActivityYear(*v)
	}
	return _c
}

// SetPeakActivityCommits sets the "peak_activity_commits" field.
func (_c *MemberStatCreate) SetPeakActivityCommits(v int) *MemberStatCreate {
	_c.mutation.SetPeakActivityCommits(v)
	return _c
}

// SetNillablePeakActivityCommits sets the "peak_activity_commits" field if the given value is not nil.
func (_c *MemberStatCreate) SetNillablePeakActivityCommits(v *int) *MemberStatCreate {
	if v != nil {
		_c.SetPeakActivityCommits(*v)
	}
	return _c
}

// SetPrToReviewRatio sets the "pr_to_review_ratio" field.
func (_c *MemberStatCreate) SetPrToReviewRatio(v float64) *MemberStatCreate {
	_c.mutation.SetPrToReviewRatio(v)
	return _c
}

// SetNillablePrToReviewRatio sets the "pr_to_review_ratio" field if the given value is not nil.
func (_c *MemberStatCreate) SetNillablePrToReviewRatio(v *float64) *MemberStatCreate {
	if v != nil {
		_c.SetPrToReviewRatio(*v)
	}
	return _c
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_c *MemberStatCreate) SetSnapshotID(id int) *MemberStatCreate {
	_c.mutation.SetSnapshotID(id)
	return _c
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_c *MemberStatCreate) SetSnapshot(v *Snapshot) *MemberStatCreate {
	return _c.SetSnapshotID(v.ID)
}

// Mutation returns the MemberStatMutation object of the builder.
func (_c *MemberStatCreate) Mutation() *MemberStatMutation {
	return _c.mutation
}

// Save creates the MemberStat in the database.
func (_c *MemberStatCreate) Save(ctx context.Context) (*MemberStat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemberStatCreate) SaveX(ctx context.Context) *MemberStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberStatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberStatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemberStatCreate) defaults() {
	if _, ok := _c.mutation.TotalCommits(); !ok {
		v := memberstat.DefaultTotalCommits
		_c.mutation.SetTotalCommits(v)
	}
	if _, ok := _c.mutation.TotalPrCreated(); !ok {
		v := memberstat.DefaultTotalPrCreated
		_c.mutation.SetTotalPrCreated(v)
	}
	if _, ok := _c.mutation.TotalPrMerged(); !ok {
		v := memberstat.DefaultTotalPrMerged
		_c.mutation.SetTotalPrMerged(v)
	}
	if _, ok := _c.mutation.TotalIssues(); !ok {
		v := memberstat.DefaultTotalIssues
		_c.mutation.SetTotalIssues(v)
	}
	if _, ok := _c.mutation.TotalReviews(); !ok {
		v := memberstat.DefaultTotalReviews
		_c.mutation.SetTotalReviews(v)
	}
	if _, ok := _c.mutation.TotalAdditions(); !ok {
		v := memberstat.DefaultTotalAdditions
		_c.mutation.SetTotalAdditions(v)
	}
	if _, ok := _c.mutation.TotalDeletions(); !ok {
		v := memberstat.DefaultTotalDeletions
		_c.mutation.SetTotalDeletions(v)
	}
	if _, ok := _c.mutation.FirstActivityYear(); !ok {
		v := memberstat.DefaultFirstActivityYear
		_c.mutation.SetFirstActivityYear(v)
	}
	if _, ok := _c.mutation.PeakActivityYear(); !ok {
		v := memberstat.DefaultPeakActivityYear
		_c.mutation.SetPeakActivityYear(v)
	}
	if _, ok := _c.mutation.PeakActivityCommits(); !ok {
		v := memberstat.DefaultPeakActivityCommits
		_c.mutation.SetPeakActivityCommits(v)
	}
	if _, ok := _c.mutation.PrToReviewRatio(); !ok {
		v := memberstat.DefaultPrToReviewRatio
		_c.mutation.SetPrToReviewRatio(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemberStatCreate) check() error {
	if _, ok := _c.mutation.Login(); !ok {
		return &ValidationError{Name: "login", err: errors.New(`ent: missing required field "MemberStat.login"`)}
	}
	if v, ok := _c.mutation.Login(); ok {
		if err := memberstat.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "MemberStat.login": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalCommits(); !ok {
		return &ValidationError{Name: "total_commits", err: errors.New(`ent: missing required field "MemberStat.total_commits"`)}
	}
	if _, ok := _c.mutation.TotalPrCreated(); !ok {
		return &ValidationError{Name: "total_pr_created", err: errors.New(`ent: missing required field "MemberStat.total_pr_created"`)}
	}
	if _, ok := _c.mutation.TotalPrMerged(); !ok {
		return &ValidationError{Name: "total_pr_merged", err: errors.New(`ent: missing required field "MemberStat.total_pr_merged"`)}
	}
	if _, ok := _c.mutation.TotalIssues(); !ok {
		return &ValidationError{Name: "total_issues", err: errors.New(`ent: missing required field "MemberStat.total_issues"`)}
	}
	if _, ok := _c.mutation.TotalReviews(); !ok {
		return &ValidationError{Name: "total_reviews", err: errors.New(`ent: missing required field "MemberStat.total_reviews"`)}
	}
	if _, ok := _c.mutation.TotalAdditions(); !ok {
		return &ValidationError{Name: "total_additions", err: errors.New(`ent: missing required field "MemberStat.total_additions"`)}
	}
	if _, ok := _c.mutation.TotalDeletions(); !ok {
		return &ValidationError{Name: "total_deletions", err: errors.New(`ent: missing required field "MemberStat.total_deletions"`)}
	}
	if _, ok := _c.mutation.FirstActivityYear(); !ok {
		return &ValidationError{Name: "first_activity_year", err: errors.New(`ent: missing required field "MemberStat.first_activity_year"`)}
	}
	if _, ok := _c.mutation.PeakActivityYear(); !ok {
		return &ValidationError{Name: "peak_activity_year", err: errors.New(`ent: missing required field "MemberStat.peak_activity_year"`)}
	}
	if _, ok := _c.mutation.PeakActivityCommits(); !ok {
		return &ValidationError{Name: "peak_activity_commits", err: errors.New(`ent: missing required field "MemberStat.peak_activity_commits"`)}
	}
	if _, ok := _c.mutation.PrToReviewRatio(); !ok {
		return &ValidationError{Name: "pr_to_review_ratio", err: errors.New(`ent: missing required field "MemberStat.pr_to_review_ratio"`)}
	}
	if len(_c.mutation.SnapshotIDs()) == 0 {
		return &ValidationError{Name: "snapshot", err: errors.New(`ent: missing required edge "MemberStat.snapshot"`)}
	}
	return nil
}

func (_c *MemberStatCreate) sqlSave(ctx context.Context) (*MemberStat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemberStatCreate) createSpec() (*MemberStat, *sqlgraph.CreateSpec) {
	var (
		_node = &MemberStat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memberstat.Table, sqlgraph.NewFieldSpec(memberstat.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Login(); ok {
		_spec.SetField(memberstat.FieldLogin, field.TypeString, value)
		_node.Login = value
	}
	if value, ok := _c.mutation.TotalCommits(); ok {
		_spec.SetField(memberstat.FieldTotalCommits, field.TypeInt, value)
		_node.TotalCommits = value
	}
	if value, ok := _c.mutation.TotalPrCreated(); ok {
		_spec.SetField(memberstat.FieldTotalPrCreated, field.TypeInt, value)
		_node.TotalPrCreated = value
	}
	if value, ok := _c.mutation.TotalPrMerged(); ok {
		_spec.SetField(memberstat.FieldTotalPrMerged, field.TypeInt, value)
		_node.TotalPrMerged = value
	}
	if value, ok := _c.mutation.TotalIssues(); ok {
		_spec.SetField(memberstat.FieldTotalIssues, field.TypeInt, value)
		_node.TotalIssues = value
	}
	if value, ok := _c.mutation.TotalReviews(); ok {
		_spec.SetField(memberstat.FieldTotalReviews, field.TypeInt, value)
		_node.TotalReviews = value
	}
	if value, ok := _c.mutation.TotalAdditions(); ok {
		_spec.SetField(memberstat.FieldTotalAdditions, field.TypeInt, value)
		_node.TotalAdditions = value
	}
	if value, ok := _c.mutation.TotalDeletions(); ok {
		_spec.SetField(memberstat.FieldTotalDeletions, field.TypeInt, value)
		_node.TotalDeletions = value
	}
	if value, ok := _c.mutation.FirstActivityYear(); ok {
		_spec.SetField(memberstat.FieldFirstActivityYear, field.TypeInt, value)
		_node.FirstActivityYear = value
	}
	if value, ok := _c.mutation.PeakActivityYear(); ok {
		_spec.SetField(memberstat.FieldPeakActivityYear, field.TypeInt, value)
		_node.PeakActivityYear = value
	}
	if value, ok := _c.mutation.PeakActivityCommits(); ok {
		_spec.SetField(memberstat.FieldPeakActivityCommits, field.TypeInt, value)
		_node.PeakActivityCommits = value
	}
	if value, ok := _c.mutation.PrToReviewRatio(); ok {
		_spec.SetField(memberstat.FieldPrToReviewRatio, field.TypeFloat64, value)
		_node.PrToReviewRatio = value
	}
	if nodes := _c.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberstat.SnapshotTable,
			Columns: []string{memberstat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.snapshot_member_stats = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemberStatCreateBulk is the builder for creating many MemberStat entities in bulk.
type MemberStatCreateBulk struct {
	config
	err      error
	builders []*MemberStatCreate
}

// Save creates the MemberStat entities in the database.
func (_c *MemberStatCreateBulk) Save(ctx context.Context) ([]*MemberStat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemberStat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberStatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemberStatCreateBulk) SaveX(ctx context.Context) []*MemberStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberStatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberStatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
