// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberrepodaystat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// MemberRepoDayStatCreate is the builder for creating a MemberRepoDayStat entity.
type MemberRepoDayStatCreate struct {
	config
	mutation *MemberRepoDayStatMutation
	hooks    []Hook
}

// SetLogin sets the "login" field.
func (_c *MemberRepoDayStatCreate) SetLogin(v string) *MemberRepoDayStatCreate {
	_c.mutation.SetLogin(v)
	return _c
}

// SetNameWithOwner sets the "name_with_owner" field.
func (_c *MemberRepoDayStatCreate) SetNameWithOwner(v string) *MemberRepoDayStatCreate {
	_c.mutation.SetNameWithOwner(v)
	return _c
}

// SetDay sets the "day" field.
func (_c *MemberRepoDayStatCreate) SetDay(v string) *MemberRepoDayStatCreate {
	_c.mutation.SetDay(v)
	return _c
}

// SetCommitCount sets the "commit_count" field.
func (_c *MemberRepoDayStatCreate) SetCommitCount(v int) *MemberRepoDayStatCreate {
	_c.mutation.SetCommitCount(v)
	return _c
}

// SetNillableCommitCount sets the "commit_count" field if the given value is not nil.
func (_c *MemberRepoDayStatCreate) SetNillableCommitCount(v *int) *MemberRepoDayStatCreate {
	if v != nil {
		_c.SetCommitCount(*v)
	}
	return _c
}

// SetPrCreated sets the "pr_created" field.
func (_c *MemberRepoDayStatCreate) SetPrCreated(v int) *MemberRepoDayStatCreate {
	_c.mutation.SetPrCreated(v)
	return _c
}

// SetNillablePrCreated sets the "pr_created" field if the given value is not nil.
func (_c *MemberRepoDayStatCreate) SetNillablePrCreated(v *int) *MemberRepoDayStatCreate {
	if v != nil {
		_c.SetPrCreated(*v)
	}
	return _c
}

// SetPrMerged sets the "pr_merged" field.
func (_c *MemberRepoDayStatCreate) SetPrMerged(v int) *MemberRepoDayStatCreate {
	_c.mutation.SetPrMerged(v)
	return _c
}

// SetNillablePrMerged sets the "pr_merged" field if the given value is not nil.
func (_c *MemberRepoDayStatCreate) SetNillablePrMerged(v *int) *MemberRepoDayStatCreate {
	if v != nil {
		_c.SetPrMerged(*v)
	}
	return _c
}

// SetIssueCount sets the "issue_count" field.
func (_c *MemberRepoDayStatCreate) SetIssueCount(v int) *MemberRepoDayStatCreate {
	_c.mutation.SetIssueCount(v)
	return _c
}

// SetNillableIssueCount sets the "issue_count" field if the given value is not nil.
func (_c *MemberRepoDayStatCreate) SetNillableIssueCount(v *int) *MemberRepoDayStatCreate {
	if v != nil {
		_c.SetIssueCount(*v)
	}
	return _c
}

// SetReviewCount sets the "review_count" field.
func (_c *MemberRepoDayStatCreate) SetReviewCount(v int) *MemberRepoDayStatCreate {
	_c.mutation.SetReviewCount(v)
	return _c
}

// SetNillableReviewCount sets the "review_count" field if the given value is not nil.
func (_c *MemberRepoDayStatCreate) SetNillableReviewCount(v *int) *MemberRepoDayStatCreate {
	if v != nil {
		_c.SetReviewCount(*v)
	}
	return _c
}

// SetAdditions sets the "additions" field.
func (_c *MemberRepoDayStatCreate) SetAdditions(v int) *MemberRepoDayStatCreate {
	_c.mutation.SetAdditions(v)
	return _c
}

// SetNillableAdditions sets the "additions" field if the given value is not nil.
func (_c *MemberRepoDayStatCreate) SetNillableAdditions(v *int) *MemberRepoDayStatCreate {
	if v != nil {
		_c.SetAdditions(*v)
	}
	return _c
}

// SetDeletions sets the "deletions" field.
func (_c *MemberRepoDayStatCreate) SetDeletions(v int) *MemberRepoDayStatCreate {
	_c.mutation.SetDeletions(v)
	return _c
}

// SetNillableDeletions sets the "deletions" field if the given value is not nil.
func (_c *MemberRepoDayStatCreate) SetNillableDeletions(v *int) *MemberRepoDayStatCreate {
	if v != nil {
		_c.SetDeletions(*v)
	}
	return _c
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_c *MemberRepoDayStatCreate) SetSnapshotID(id int) *MemberRepoDayStatCreate {
	_c.mutation.SetSnapshotID(id)
	return _c
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_c *MemberRepoDayStatCreate) SetSnapshot(v *Snapshot) *MemberRepoDayStatCreate {
	return _c.SetSnapshotID(v.ID)
}

// Mutation returns the MemberRepoDayStatMutation object of the builder.
func (_c *MemberRepoDayStatCreate) Mutation() *MemberRepoDayStatMutation {
	return _c.mutation
}

// Save creates the MemberRepoDayStat in the database.
func (_c *MemberRepoDayStatCreate) Save(ctx context.Context) (*MemberRepoDayStat, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemberRepoDayStatCreate) SaveX(ctx context.Context) *MemberRepoDayStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberRepoDayStatCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberRepoDayStatCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemberRepoDayStatCreate) defaults() {
	if _, ok := _c.mutation.CommitCount(); !ok {
		v := memberrepodaystat.DefaultCommitCount
		_c.mutation.SetCommitCount(v)
	}
	if _, ok := _c.mutation.PrCreated(); !ok {
		v := memberrepodaystat.DefaultPrCreated
		_c.mutation.SetPrCreated(v)
	}
	if _, ok := _c.mutation.PrMerged(); !ok {
		v := memberrepodaystat.DefaultPrMerged
		_c.mutation.SetPrMerged(v)
	}
	if _, ok := _c.mutation.IssueCount(); !ok {
		v := memberrepodaystat.DefaultIssueCount
		_c.mutation.SetIssueCount(v)
	}
	if _, ok := _c.mutation.ReviewCount(); !ok {
		v := memberrepodaystat.DefaultReviewCount
		_c.mutation.SetReviewCount(v)
	}
	if _, ok := _c.mutation.Additions(); !ok {
		v := memberrepodaystat.DefaultAdditions
		_c.mutation.SetAdditions(v)
	}
	if _, ok := _c.mutation.Deletions(); !ok {
		v := memberrepodaystat.DefaultDeletions
		_c.mutation.SetDeletions(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemberRepoDayStatCreate) check() error {
	if _, ok := _c.mutation.Login(); !ok {
		return &ValidationError{Name: "login", err: errors.New(`ent: missing required field "MemberRepoDayStat.login"`)}
	}
	if v, ok := _c.mutation.Login(); ok {
		if err := memberrepodaystat.LoginValidator(v); err != nil {
			return &ValidationError{Name: "login", err: fmt.Errorf(`ent: validator failed for field "MemberRepoDayStat.login": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NameWithOwner(); !ok {
		return &ValidationError{Name: "name_with_owner", err: errors.New(`ent: missing required field "MemberRepoDayStat.name_with_owner"`)}
	}
	if v, ok := _c.mutation.NameWithOwner(); ok {
		if err := memberrepodaystat.NameWithOwnerValidator(v); err != nil {
			return &ValidationError{Name: "name_with_owner", err: fmt.Errorf(`ent: validator failed for field "MemberRepoDayStat.name_with_owner": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Day(); !ok {
		return &ValidationError{Name: "day", err: errors.New(`ent: missing required field "MemberRepoDayStat.day"`)}
	}
	if v, ok := _c.mutation.Day(); ok {
		if err := memberrepodaystat.DayValidator(v); err != nil {
			return &ValidationError{Name: "day", err: fmt.Errorf(`ent: validator failed for field "MemberRepoDayStat.day": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CommitCount(); !ok {
		return &ValidationError{Name: "commit_count", err: errors.New(`ent: missing required field "MemberRepoDayStat.commit_count"`)}
	}
	if _, ok := _c.mutation.PrCreated(); !ok {
		return &ValidationError{Name: "pr_created", err: errors.New(`ent: missing required field "MemberRepoDayStat.pr_created"`)}
	}
	if _, ok := _c.mutation.PrMerged(); !ok {
		return &ValidationError{Name: "pr_merged", err: errors.New(`ent: missing required field "MemberRepoDayStat.pr_merged"`)}
	}
	if _, ok := _c.mutation.IssueCount(); !ok {
		return &ValidationError{Name: "issue_count", err: errors.New(`ent: missing required field "MemberRepoDayStat.issue_count"`)}
	}
	if _, ok := _c.mutation.ReviewCount(); !ok {
		return &ValidationError{Name: "review_count", err: errors.New(`ent: missing required field "MemberRepoDayStat.review_count"`)}
	}
	if _, ok := _c.mutation.Additions(); !ok {
		return &ValidationError{Name: "additions", err: errors.New(`ent: missing required field "MemberRepoDayStat.additions"`)}
	}
	if _, ok := _c.mutation.Deletions(); !ok {
		return &ValidationError{Name: "deletions", err: errors.New(`ent: missing required field "MemberRepoDayStat.deletions"`)}
	}
	if len(_c.mutation.SnapshotIDs()) == 0 {
		return &ValidationError{Name: "snapshot", err: errors.New(`ent: missing required edge "MemberRepoDayStat.snapshot"`)}
	}
	return nil
}

func (_c *MemberRepoDayStatCreate) sqlSave(ctx context.Context) (*MemberRepoDayStat, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemberRepoDayStatCreate) createSpec() (*MemberRepoDayStat, *sqlgraph.CreateSpec) {
	var (
		_node = &MemberRepoDayStat{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memberrepodaystat.Table, sqlgraph.NewFieldSpec(memberrepodaystat.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Login(); ok {
		_spec.SetField(memberrepodaystat.FieldLogin, field.TypeString, value)
		_node.Login = value
	}
	if value, ok := _c.mutation.NameWithOwner(); ok {
		_spec.SetField(memberrepodaystat.FieldNameWithOwner, field.TypeString, value)
		_node.NameWithOwner = value
	}
	if value, ok := _c.mutation.Day(); ok {
		_spec.SetField(memberrepodaystat.FieldDay, field.TypeString, value)
		_node.Day = value
	}
	if value, ok := _c.mutation.CommitCount(); ok {
		_spec.SetField(memberrepodaystat.FieldCommitCount, field.TypeInt, value)
		_node.CommitCount = value
	}
	if value, ok := _c.mutation.PrCreated(); ok {
		_spec.SetField(memberrepodaystat.FieldPrCreated, field.TypeInt, value)
		_node.PrCreated = value
	}
	if value, ok := _c.mutation.PrMerged(); ok {
		_spec.SetField(memberrepodaystat.FieldPrMerged, field.TypeInt, value)
		_node.PrMerged = value
	}
	if value, ok := _c.mutation.IssueCount(); ok {
		_spec.SetField(memberrepodaystat.FieldIssueCount, field.TypeInt, value)
		_node.IssueCount = value
	}
	if value, ok := _c.mutation.ReviewCount(); ok {
		_spec.SetField(memberrepodaystat.FieldReviewCount, field.TypeInt, value)
		_node.ReviewCount = value
	}
	if value, ok := _c.mutation.Additions(); ok {
		_spec.SetField(memberrepodaystat.FieldAdditions, field.TypeInt, value)
		_node.Additions = value
	}
	if value, ok := _c.mutation.Deletions(); ok {
		_spec.SetField(memberrepodaystat.FieldDeletions, field.TypeInt, value)
		_node.Deletions = value
	}
	if nodes := _c.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   memberrepodaystat.SnapshotTable,
			Columns: []string{memberrepodaystat.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.snapshot_member_repo_day_stats = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemberRepoDayStatCreateBulk is the builder for creating many MemberRepoDayStat entities in bulk.
type MemberRepoDayStatCreateBulk struct {
	config
	err      error
	builders []*MemberRepoDayStatCreate
}

// Save creates the MemberRepoDayStat entities in the database.
func (_c *MemberRepoDayStatCreateBulk) Save(ctx context.Context) ([]*MemberRepoDayStat, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MemberRepoDayStat, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemberRepoDayStatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemberRepoDayStatCreateBulk) SaveX(ctx context.Context) []*MemberRepoDayStat {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemberRepoDayStatCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemberRepoDayStatCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
