// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Tattsum/github-analytics/infrastructure/ent/repometa"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// RepoMeta is the model entity for the RepoMeta schema.
type RepoMeta struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// NameWithOwner holds the value of the "name_with_owner" field.
	NameWithOwner string `json:"name_with_owner,omitempty"`
	// Owner holds the value of the "owner" field.
	Owner string `json:"owner,omitempty"`
	// OwnerType holds the value of the "owner_type" field.
	OwnerType string `json:"owner_type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RepoMetaQuery when eager-loading is set.
	Edges               RepoMetaEdges `json:"edges"`
	snapshot_repo_metas *int
	selectValues        sql.SelectValues
}

// RepoMetaEdges holds the relations/edges for other nodes in the graph.
type RepoMetaEdges struct {
	// Snapshot holds the value of the snapshot edge.
	Snapshot *Snapshot `json:"snapshot,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SnapshotOrErr returns the Snapshot value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RepoMetaEdges) SnapshotOrErr() (*Snapshot, error) {
	if e.Snapshot != nil {
		return e.Snapshot, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: snapshot.Label}
	}
	return nil, &NotLoadedError{edge: "snapshot"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RepoMeta) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case repometa.FieldID:
			values[i] = new(sql.NullInt64)
		case repometa.FieldNameWithOwner, repometa.FieldOwner, repometa.FieldOwnerType:
			values[i] = new(sql.NullString)
		case repometa.ForeignKeys[0]: // snapshot_repo_metas
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RepoMeta fields.
func (_m *RepoMeta) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case repometa.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case repometa.FieldNameWithOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name_with_owner", values[i])
			} else if value.Valid {
				_m.NameWithOwner = value.String
			}
		case repometa.FieldOwner:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner", values[i])
			} else if value.Valid {
				_m.Owner = value.String
			}
		case repometa.FieldOwnerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_type", values[i])
			} else if value.Valid {
				_m.OwnerType = value.String
			}
		case repometa.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field snapshot_repo_metas", value)
			} else if value.Valid {
				_m.snapshot_repo_metas = new(int)
				*_m.snapshot_repo_metas = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RepoMeta.
// This includes values selected through modifiers, order, etc.
func (_m *RepoMeta) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySnapshot queries the "snapshot" edge of the RepoMeta entity.
func (_m *RepoMeta) QuerySnapshot() *SnapshotQuery {
	return NewRepoMetaClient(_m.config).QuerySnapshot(_m)
}

// Update returns a builder for updating this RepoMeta.
// Note that you need to call RepoMeta.Unwrap() before calling this method if this RepoMeta
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RepoMeta) Update() *RepoMetaUpdateOne {
	return NewRepoMetaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RepoMeta entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RepoMeta) Unwrap() *RepoMeta {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RepoMeta is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RepoMeta) String() string {
	var builder strings.Builder
	builder.WriteString("RepoMeta(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name_with_owner=")
	builder.WriteString(_m.NameWithOwner)
	builder.WriteString(", ")
	builder.WriteString("owner=")
	builder.WriteString(_m.Owner)
	builder.WriteString(", ")
	builder.WriteString("owner_type=")
	builder.WriteString(_m.OwnerType)
	builder.WriteByte(')')
	return builder.String()
}

// RepoMetaSlice is a parsable slice of RepoMeta.
type RepoMetaSlice []*RepoMeta
