// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
	"github.com/Tattsum/github-analytics/infrastructure/ent/repometa"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// RepoMetaUpdate is the builder for updating RepoMeta entities.
type RepoMetaUpdate struct {
	config
	hooks    []Hook
	mutation *RepoMetaMutation
}

// Where appends a list predicates to the RepoMetaUpdate builder.
func (_u *RepoMetaUpdate) Where(ps ...predicate.RepoMeta) *RepoMetaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNameWithOwner sets the "name_with_owner" field.
func (_u *RepoMetaUpdate) SetNameWithOwner(v string) *RepoMetaUpdate {
	_u.mutation.SetNameWithOwner(v)
	return _u
}

// SetNillableNameWithOwner sets the "name_with_owner" field if the given value is not nil.
func (_u *RepoMetaUpdate) SetNillableNameWithOwner(v *string) *RepoMetaUpdate {
	if v != nil {
		_u.SetNameWithOwner(*v)
	}
	return _u
}

// SetOwner sets the "owner" field.
func (_u *RepoMetaUpdate) SetOwner(v string) *RepoMetaUpdate {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepoMetaUpdate) SetNillableOwner(v *string) *RepoMetaUpdate {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetOwnerType sets the "owner_type" field.
func (_u *RepoMetaUpdate) SetOwnerType(v string) *RepoMetaUpdate {
	_u.mutation.SetOwnerType(v)
	return _u
}

// SetNillableOwnerType sets the "owner_type" field if the given value is not nil.
func (_u *RepoMetaUpdate) SetNillableOwnerType(v *string) *RepoMetaUpdate {
	if v != nil {
		_u.SetOwnerType(*v)
	}
	return _u
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_u *RepoMetaUpdate) SetSnapshotID(id int) *RepoMetaUpdate {
	_u.mutation.SetSnapshotID(id)
	return _u
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_u *RepoMetaUpdate) SetSnapshot(v *Snapshot) *RepoMetaUpdate {
	return _u.SetSnapshotID(v.ID)
}

// Mutation returns the RepoMetaMutation object of the builder.
func (_u *RepoMetaUpdate) Mutation() *RepoMetaMutation {
	return _u.mutation
}

// ClearSnapshot clears the "snapshot" edge to the Snapshot entity.
func (_u *RepoMetaUpdate) ClearSnapshot() *RepoMetaUpdate {
	_u.mutation.ClearSnapshot()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RepoMetaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepoMetaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RepoMetaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepoMetaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepoMetaUpdate) check() error {
	if v, ok := _u.mutation.NameWithOwner(); ok {
		if err := repometa.NameWithOwnerValidator(v); err != nil {
			return &ValidationError{Name: "name_with_owner", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.name_with_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Owner(); ok {
		if err := repometa.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.owner": %w`, err)}
		}
	}
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RepoMeta.snapshot"`)
	}
	return nil
}

func (_u *RepoMetaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repometa.Table, repometa.Columns, sqlgraph.NewFieldSpec(repometa.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NameWithOwner(); ok {
		_spec.SetField(repometa.FieldNameWithOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repometa.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerType(); ok {
		_spec.SetField(repometa.FieldOwnerType, field.TypeString, value)
	}
	if _u.mutation.SnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repometa.SnapshotTable,
			Columns: []string{repometa.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repometa.SnapshotTable,
			Columns: []string{repometa.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repometa.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RepoMetaUpdateOne is the builder for updating a single RepoMeta entity.
type RepoMetaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepoMetaMutation
}

// SetNameWithOwner sets the "name_with_owner" field.
func (_u *RepoMetaUpdateOne) SetNameWithOwner(v string) *RepoMetaUpdateOne {
	_u.mutation.SetNameWithOwner(v)
	return _u
}

// SetNillableNameWithOwner sets the "name_with_owner" field if the given value is not nil.
func (_u *RepoMetaUpdateOne) SetNillableNameWithOwner(v *string) *RepoMetaUpdateOne {
	if v != nil {
		_u.SetNameWithOwner(*v)
	}
	return _u
}

// SetOwner sets the "owner" field.
func (_u *RepoMetaUpdateOne) SetOwner(v string) *RepoMetaUpdateOne {
	_u.mutation.SetOwner(v)
	return _u
}

// SetNillableOwner sets the "owner" field if the given value is not nil.
func (_u *RepoMetaUpdateOne) SetNillableOwner(v *string) *RepoMetaUpdateOne {
	if v != nil {
		_u.SetOwner(*v)
	}
	return _u
}

// SetOwnerType sets the "owner_type" field.
func (_u *RepoMetaUpdateOne) SetOwnerType(v string) *RepoMetaUpdateOne {
	_u.mutation.SetOwnerType(v)
	return _u
}

// SetNillableOwnerType sets the "owner_type" field if the given value is not nil.
func (_u *RepoMetaUpdateOne) SetNillableOwnerType(v *string) *RepoMetaUpdateOne {
	if v != nil {
		_u.SetOwnerType(*v)
	}
	return _u
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_u *RepoMetaUpdateOne) SetSnapshotID(id int) *RepoMetaUpdateOne {
	_u.mutation.SetSnapshotID(id)
	return _u
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_u *RepoMetaUpdateOne) SetSnapshot(v *Snapshot) *RepoMetaUpdateOne {
	return _u.SetSnapshotID(v.ID)
}

// Mutation returns the RepoMetaMutation object of the builder.
func (_u *RepoMetaUpdateOne) Mutation() *RepoMetaMutation {
	return _u.mutation
}

// ClearSnapshot clears the "snapshot" edge to the Snapshot entity.
func (_u *RepoMetaUpdateOne) ClearSnapshot() *RepoMetaUpdateOne {
	_u.mutation.ClearSnapshot()
	return _u
}

// Where appends a list predicates to the RepoMetaUpdate builder.
func (_u *RepoMetaUpdateOne) Where(ps ...predicate.RepoMeta) *RepoMetaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RepoMetaUpdateOne) Select(field string, fields ...string) *RepoMetaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RepoMeta entity.
func (_u *RepoMetaUpdateOne) Save(ctx context.Context) (*RepoMeta, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepoMetaUpdateOne) SaveX(ctx context.Context) *RepoMeta {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RepoMetaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepoMetaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepoMetaUpdateOne) check() error {
	if v, ok := _u.mutation.NameWithOwner(); ok {
		if err := repometa.NameWithOwnerValidator(v); err != nil {
			return &ValidationError{Name: "name_with_owner", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.name_with_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Owner(); ok {
		if err := repometa.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.owner": %w`, err)}
		}
	}
	if _u.mutation.SnapshotCleared() && len(_u.mutation.SnapshotIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RepoMeta.snapshot"`)
	}
	return nil
}

func (_u *RepoMetaUpdateOne) sqlSave(ctx context.Context) (_node *RepoMeta, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repometa.Table, repometa.Columns, sqlgraph.NewFieldSpec(repometa.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RepoMeta.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repometa.FieldID)
		for _, f := range fields {
			if !repometa.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repometa.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NameWithOwner(); ok {
		_spec.SetField(repometa.FieldNameWithOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.Owner(); ok {
		_spec.SetField(repometa.FieldOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.OwnerType(); ok {
		_spec.SetField(repometa.FieldOwnerType, field.TypeString, value)
	}
	if _u.mutation.SnapshotCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repometa.SnapshotTable,
			Columns: []string{repometa.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repometa.SnapshotTable,
			Columns: []string{repometa.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RepoMeta{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repometa.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
