// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/repometa"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// RepoMetaCreate is the builder for creating a RepoMeta entity.
type RepoMetaCreate struct {
	config
	mutation *RepoMetaMutation
	hooks    []Hook
}

// SetNameWithOwner sets the "name_with_owner" field.
func (_c *RepoMetaCreate) SetNameWithOwner(v string) *RepoMetaCreate {
	_c.mutation.SetNameWithOwner(v)
	return _c
}

// SetOwner sets the "owner" field.
func (_c *RepoMetaCreate) SetOwner(v string) *RepoMetaCreate {
	_c.mutation.SetOwner(v)
	return _c
}

// SetOwnerType sets the "owner_type" field.
func (_c *RepoMetaCreate) SetOwnerType(v string) *RepoMetaCreate {
	_c.mutation.SetOwnerType(v)
	return _c
}

// SetNillableOwnerType sets the "owner_type" field if the given value is not nil.
func (_c *RepoMetaCreate) SetNillableOwnerType(v *string) *RepoMetaCreate {
	if v != nil {
		_c.SetOwnerType(*v)
	}
	return _c
}

// SetSnapshotID sets the "snapshot" edge to the Snapshot entity by ID.
func (_c *RepoMetaCreate) SetSnapshotID(id int) *RepoMetaCreate {
	_c.mutation.SetSnapshotID(id)
	return _c
}

// SetSnapshot sets the "snapshot" edge to the Snapshot entity.
func (_c *RepoMetaCreate) SetSnapshot(v *Snapshot) *RepoMetaCreate {
	return _c.SetSnapshotID(v.ID)
}

// Mutation returns the RepoMetaMutation object of the builder.
func (_c *RepoMetaCreate) Mutation() *RepoMetaMutation {
	return _c.mutation
}

// Save creates the RepoMeta in the database.
func (_c *RepoMetaCreate) Save(ctx context.Context) (*RepoMeta, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RepoMetaCreate) SaveX(ctx context.Context) *RepoMeta {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepoMetaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepoMetaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RepoMetaCreate) defaults() {
	if _, ok := _c.mutation.OwnerType(); !ok {
		v := repometa.DefaultOwnerType
		_c.mutation.SetOwnerType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RepoMetaCreate) check() error {
	if _, ok := _c.mutation.NameWithOwner(); !ok {
		return &ValidationError{Name: "name_with_owner", err: errors.New(`ent: missing required field "RepoMeta.name_with_owner"`)}
	}
	if v, ok := _c.mutation.NameWithOwner(); ok {
		if err := repometa.NameWithOwnerValidator(v); err != nil {
			return &ValidationError{Name: "name_with_owner", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.name_with_owner": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Owner(); !ok {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required field "RepoMeta.owner"`)}
	}
	if v, ok := _c.mutation.Owner(); ok {
		if err := repometa.OwnerValidator(v); err != nil {
			return &ValidationError{Name: "owner", err: fmt.Errorf(`ent: validator failed for field "RepoMeta.owner": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OwnerType(); !ok {
		return &ValidationError{Name: "owner_type", err: errors.New(`ent: missing required field "RepoMeta.owner_type"`)}
	}
	if len(_c.mutation.SnapshotIDs()) == 0 {
		return &ValidationError{Name: "snapshot", err: errors.New(`ent: missing required edge "RepoMeta.snapshot"`)}
	}
	return nil
}

func (_c *RepoMetaCreate) sqlSave(ctx context.Context) (*RepoMeta, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RepoMetaCreate) createSpec() (*RepoMeta, *sqlgraph.CreateSpec) {
	var (
		_node = &RepoMeta{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(repometa.Table, sqlgraph.NewFieldSpec(repometa.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.NameWithOwner(); ok {
		_spec.SetField(repometa.FieldNameWithOwner, field.TypeString, value)
		_node.NameWithOwner = value
	}
	if value, ok := _c.mutation.Owner(); ok {
		_spec.SetField(repometa.FieldOwner, field.TypeString, value)
		_node.Owner = value
	}
	if value, ok := _c.mutation.OwnerType(); ok {
		_spec.SetField(repometa.FieldOwnerType, field.TypeString, value)
		_node.OwnerType = value
	}
	if nodes := _c.mutation.SnapshotIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   repometa.SnapshotTable,
			Columns: []string{repometa.SnapshotColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.snapshot_repo_metas = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RepoMetaCreateBulk is the builder for creating many RepoMeta entities in bulk.
type RepoMetaCreateBulk struct {
	config
	err      error
	builders []*RepoMetaCreate
}

// Save creates the RepoMeta entities in the database.
func (_c *RepoMetaCreateBulk) Save(ctx context.Context) ([]*RepoMeta, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RepoMeta, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RepoMetaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RepoMetaCreateBulk) SaveX(ctx context.Context) []*RepoMeta {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RepoMetaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RepoMetaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
