// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/Tattsum/github-analytics/infrastructure/ent/memberdaystat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberrepodaystat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberrepostat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberyearstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/repometa"
	"github.com/Tattsum/github-analytics/infrastructure/ent/schema"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memberdaystatFields := schema.MemberDayStat{}.Fields()
	_ = memberdaystatFields
	// memberdaystatDescLogin is the schema descriptor for login field.
	memberdaystatDescLogin := memberdaystatFields[0].Descriptor()
	// memberdaystat.LoginValidator is a validator for the "login" field. It is called by the builders before save.
	memberdaystat.LoginValidator = memberdaystatDescLogin.Validators[0].(func(string) error)
	// memberdaystatDescDay is the schema descriptor for day field.
	memberdaystatDescDay := memberdaystatFields[1].Descriptor()
	// memberdaystat.DayValidator is a validator for the "day" field. It is called by the builders before save.
	memberdaystat.DayValidator = memberdaystatDescDay.Validators[0].(func(string) error)
	// memberdaystatDescCommitCount is the schema descriptor for commit_count field.
	memberdaystatDescCommitCount := memberdaystatFields[2].Descriptor()
	// memberdaystat.DefaultCommitCount holds the default value on creation for the commit_count field.
	memberdaystat.DefaultCommitCount = memberdaystatDescCommitCount.Default.(int)
	// memberdaystatDescPrCreated is the schema descriptor for pr_created field.
	memberdaystatDescPrCreated := memberdaystatFields[3].Descriptor()
	// memberdaystat.DefaultPrCreated holds the default value on creation for the pr_created field.
	memberdaystat.DefaultPrCreated = memberdaystatDescPrCreated.Default.(int)
	// memberdaystatDescPrMerged is the schema descriptor for pr_merged field.
	memberdaystatDescPrMerged := memberdaystatFields[4].Descriptor()
	// memberdaystat.DefaultPrMerged holds the default value on creation for the pr_merged field.
	memberdaystat.DefaultPrMerged = memberdaystatDescPrMerged.Default.(int)
	// memberdaystatDescIssueCount is the schema descriptor for issue_count field.
	memberdaystatDescIssueCount := memberdaystatFields[5].Descriptor()
	// memberdaystat.DefaultIssueCount holds the default value on creation for the issue_count field.
	memberdaystat.DefaultIssueCount = memberdaystatDescIssueCount.Default.(int)
	// memberdaystatDescReviewCount is the schema descriptor for review_count field.
	memberdaystatDescReviewCount := memberdaystatFields[6].Descriptor()
	// memberdaystat.DefaultReviewCount holds the default value on creation for the review_count field.
	memberdaystat.DefaultReviewCount = memberdaystatDescReviewCount.Default.(int)
	// memberdaystatDescAdditions is the schema descriptor for additions field.
	memberdaystatDescAdditions := memberdaystatFields[7].Descriptor()
	// memberdaystat.DefaultAdditions holds the default value on creation for the additions field.
	memberdaystat.DefaultAdditions = memberdaystatDescAdditions.Default.(int)
	// memberdaystatDescDeletions is the schema descriptor for deletions field.
	memberdaystatDescDeletions := memberdaystatFields[8].Descriptor()
	// memberdaystat.DefaultDeletions holds the default value on creation for the deletions field.
	memberdaystat.DefaultDeletions = memberdaystatDescDeletions.Default.(int)
	memberrepodaystatFields := schema.MemberRepoDayStat{}.Fields()
	_ = memberrepodaystatFields
	// memberrepodaystatDescLogin is the schema descriptor for login field.
	memberrepodaystatDescLogin := memberrepodaystatFields[0].Descriptor()
	// memberrepodaystat.LoginValidator is a validator for the "login" field. It is called by the builders before save.
	memberrepodaystat.LoginValidator = memberrepodaystatDescLogin.Validators[0].(func(string) error)
	// memberrepodaystatDescNameWithOwner is the schema descriptor for name_with_owner field.
	memberrepodaystatDescNameWithOwner := memberrepodaystatFields[1].Descriptor()
	// memberrepodaystat.NameWithOwnerValidator is a validator for the "name_with_owner" field. It is called by the builders before save.
	memberrepodaystat.NameWithOwnerValidator = memberrepodaystatDescNameWithOwner.Validators[0].(func(string) error)
	// memberrepodaystatDescDay is the schema descriptor for day field.
	memberrepodaystatDescDay := memberrepodaystatFields[2].Descriptor()
	// memberrepodaystat.DayValidator is a validator for the "day" field. It is called by the builders before save.
	memberrepodaystat.DayValidator = memberrepodaystatDescDay.Validators[0].(func(string) error)
	// memberrepodaystatDescCommitCount is the schema descriptor for commit_count field.
	memberrepodaystatDescCommitCount := memberrepodaystatFields[3].Descriptor()
	// memberrepodaystat.DefaultCommitCount holds the default value on creation for the commit_count field.
	memberrepodaystat.DefaultCommitCount = memberrepodaystatDescCommitCount.Default.(int)
	// memberrepodaystatDescPrCreated is the schema descriptor for pr_created field.
	memberrepodaystatDescPrCreated := memberrepodaystatFields[4].Descriptor()
	// memberrepodaystat.DefaultPrCreated holds the default value on creation for the pr_created field.
	memberrepodaystat.DefaultPrCreated = memberrepodaystatDescPrCreated.Default.(int)
	// memberrepodaystatDescPrMerged is the schema descriptor for pr_merged field.
	memberrepodaystatDescPrMerged := memberrepodaystatFields[5].Descriptor()
	// memberrepodaystat.DefaultPrMerged holds the default value on creation for the pr_merged field.
	memberrepodaystat.DefaultPrMerged = memberrepodaystatDescPrMerged.Default.(int)
	// memberrepodaystatDescIssueCount is the schema descriptor for issue_count field.
	memberrepodaystatDescIssueCount := memberrepodaystatFields[6].Descriptor()
	// memberrepodaystat.DefaultIssueCount holds the default value on creation for the issue_count field.
	memberrepodaystat.DefaultIssueCount = memberrepodaystatDescIssueCount.Default.(int)
	// memberrepodaystatDescReviewCount is the schema descriptor for review_count field.
	memberrepodaystatDescReviewCount := memberrepodaystatFields[7].Descriptor()
	// memberrepodaystat.DefaultReviewCount holds the default value on creation for the review_count field.
	memberrepodaystat.DefaultReviewCount = memberrepodaystatDescReviewCount.Default.(int)
	// memberrepodaystatDescAdditions is the schema descriptor for additions field.
	memberrepodaystatDescAdditions := memberrepodaystatFields[8].Descriptor()
	// memberrepodaystat.DefaultAdditions holds the default value on creation for the additions field.
	memberrepodaystat.DefaultAdditions = memberrepodaystatDescAdditions.Default.(int)
	// memberrepodaystatDescDeletions is the schema descriptor for deletions field.
	memberrepodaystatDescDeletions := memberrepodaystatFields[9].Descriptor()
	// memberrepodaystat.DefaultDeletions holds the default value on creation for the deletions field.
	memberrepodaystat.DefaultDeletions = memberrepodaystatDescDeletions.Default.(int)
	memberrepostatFields := schema.MemberRepoStat{}.Fields()
	_ = memberrepostatFields
	// memberrepostatDescLogin is the schema descriptor for login field.
	memberrepostatDescLogin := memberrepostatFields[0].Descriptor()
	// memberrepostat.LoginValidator is a validator for the "login" field. It is called by the builders before save.
	memberrepostat.LoginValidator = memberrepostatDescLogin.Validators[0].(func(string) error)
	// memberrepostatDescNameWithOwner is the schema descriptor for name_with_owner field.
	memberrepostatDescNameWithOwner := memberrepostatFields[1].Descriptor()
	// memberrepostat.NameWithOwnerValidator is a validator for the "name_with_owner" field. It is called by the builders before save.
	memberrepostat.NameWithOwnerValidator = memberrepostatDescNameWithOwner.Validators[0].(func(string) error)
	// memberrepostatDescCommitCount is the schema descriptor for commit_count field.
	memberrepostatDescCommitCount := memberrepostatFields[2].Descriptor()
	// memberrepostat.DefaultCommitCount holds the default value on creation for the commit_count field.
	memberrepostat.DefaultCommitCount = memberrepostatDescCommitCount.Default.(int)
	// memberrepostatDescPrCreated is the schema descriptor for pr_created field.
	memberrepostatDescPrCreated := memberrepostatFields[3].Descriptor()
	// memberrepostat.DefaultPrCreated holds the default value on creation for the pr_created field.
	memberrepostat.DefaultPrCreated = memberrepostatDescPrCreated.Default.(int)
	// memberrepostatDescPrMerged is the schema descriptor for pr_merged field.
	memberrepostatDescPrMerged := memberrepostatFields[4].Descriptor()
	// memberrepostat.DefaultPrMerged holds the default value on creation for the pr_merged field.
	memberrepostat.DefaultPrMerged = memberrepostatDescPrMerged.Default.(int)
	// memberrepostatDescIssueCount is the schema descriptor for issue_count field.
	memberrepostatDescIssueCount := memberrepostatFields[5].Descriptor()
	// memberrepostat.DefaultIssueCount holds the default value on creation for the issue_count field.
	memberrepostat.DefaultIssueCount = memberrepostatDescIssueCount.Default.(int)
	// memberrepostatDescReviewCount is the schema descriptor for review_count field.
	memberrepostatDescReviewCount := memberrepostatFields[6].Descriptor()
	// memberrepostat.DefaultReviewCount holds the default value on creation for the review_count field.
	memberrepostat.DefaultReviewCount = memberrepostatDescReviewCount.Default.(int)
	// memberrepostatDescAdditions is the schema descriptor for additions field.
	memberrepostatDescAdditions := memberrepostatFields[7].Descriptor()
	// memberrepostat.DefaultAdditions holds the default value on creation for the additions field.
	memberrepostat.DefaultAdditions = memberrepostatDescAdditions.Default.(int)
	// memberrepostatDescDeletions is the schema descriptor for deletions field.
	memberrepostatDescDeletions := memberrepostatFields[8].Descriptor()
	// memberrepostat.DefaultDeletions holds the default value on creation for the deletions field.
	memberrepostat.DefaultDeletions = memberrepostatDescDeletions.Default.(int)
	memberstatFields := schema.MemberStat{}.Fields()
	_ = memberstatFields
	// memberstatDescLogin is the schema descriptor for login field.
	memberstatDescLogin := memberstatFields[0].Descriptor()
	// memberstat.LoginValidator is a validator for the "login" field. It is called by the builders before save.
	memberstat.LoginValidator = memberstatDescLogin.Validators[0].(func(string) error)
	// memberstatDescTotalCommits is the schema descriptor for total_commits field.
	memberstatDescTotalCommits := memberstatFields[1].Descriptor()
	// memberstat.DefaultTotalCommits holds the default value on creation for the total_commits field.
	memberstat.DefaultTotalCommits = memberstatDescTotalCommits.Default.(int)
	// memberstatDescTotalPrCreated is the schema descriptor for total_pr_created field.
	memberstatDescTotalPrCreated := memberstatFields[2].Descriptor()
	// memberstat.DefaultTotalPrCreated holds the default value on creation for the total_pr_created field.
	memberstat.DefaultTotalPrCreated = memberstatDescTotalPrCreated.Default.(int)
	// memberstatDescTotalPrMerged is the schema descriptor for total_pr_merged field.
	memberstatDescTotalPrMerged := memberstatFields[3].Descriptor()
	// memberstat.DefaultTotalPrMerged holds the default value on creation for the total_pr_merged field.
	memberstat.DefaultTotalPrMerged = memberstatDescTotalPrMerged.Default.(int)
	// memberstatDescTotalIssues is the schema descriptor for total_issues field.
	memberstatDescTotalIssues := memberstatFields[4].Descriptor()
	// memberstat.DefaultTotalIssues holds the default value on creation for the total_issues field.
	memberstat.DefaultTotalIssues = memberstatDescTotalIssues.Default.(int)
	// memberstatDescTotalReviews is the schema descriptor for total_reviews field.
	memberstatDescTotalReviews := memberstatFields[5].Descriptor()
	// memberstat.DefaultTotalReviews holds the default value on creation for the total_reviews field.
	memberstat.DefaultTotalReviews = memberstatDescTotalReviews.Default.(int)
	// memberstatDescTotalAdditions is the schema descriptor for total_additions field.
	memberstatDescTotalAdditions := memberstatFields[6].Descriptor()
	// memberstat.DefaultTotalAdditions holds the default value on creation for the total_additions field.
	memberstat.DefaultTotalAdditions = memberstatDescTotalAdditions.Default.(int)
	// memberstatDescTotalDeletions is the schema descriptor for total_deletions field.
	memberstatDescTotalDeletions := memberstatFields[7].Descriptor()
	// memberstat.DefaultTotalDeletions holds the default value on creation for the total_deletions field.
	memberstat.DefaultTotalDeletions = memberstatDescTotalDeletions.Default.(int)
	// memberstatDescFirstActivityYear is the schema descriptor for first_activity_year field.
	memberstatDescFirstActivityYear := memberstatFields[8].Descriptor()
	// memberstat.DefaultFirstActivityYear holds the default value on creation for the first_activity_year field.
	memberstat.DefaultFirstActivityYear = memberstatDescFirstActivityYear.Default.(int)
	// memberstatDescPeakActivityYear is the schema descriptor for peak_activity_year field.
	memberstatDescPeakActivityYear := memberstatFields[9].Descriptor()
	// memberstat.DefaultPeakActivityYear holds the default value on creation for the peak_activity_year field.
	memberstat.DefaultPeakActivityYear = memberstatDescPeakActivityYear.Default.(int)
	// memberstatDescPeakActivityCommits is the schema descriptor for peak_activity_commits field.
	memberstatDescPeakActivityCommits := memberstatFields[10].Descriptor()
	// memberstat.DefaultPeakActivityCommits holds the default value on creation for the peak_activity_commits field.
	memberstat.DefaultPeakActivityCommits = memberstatDescPeakActivityCommits.Default.(int)
	// memberstatDescPrToReviewRatio is the schema descriptor for pr_to_review_ratio field.
	memberstatDescPrToReviewRatio := memberstatFields[11].Descriptor()
	// memberstat.DefaultPrToReviewRatio holds the default value on creation for the pr_to_review_ratio field.
	memberstat.DefaultPrToReviewRatio = memberstatDescPrToReviewRatio.Default.(float64)
	memberyearstatFields := schema.MemberYearStat{}.Fields()
	_ = memberyearstatFields
	// memberyearstatDescLogin is the schema descriptor for login field.
	memberyearstatDescLogin := memberyearstatFields[0].Descriptor()
	// memberyearstat.LoginValidator is a validator for the "login" field. It is called by the builders before save.
	memberyearstat.LoginValidator = memberyearstatDescLogin.Validators[0].(func(string) error)
	// memberyearstatDescCommitCount is the schema descriptor for commit_count field.
	memberyearstatDescCommitCount := memberyearstatFields[2].Descriptor()
	// memberyearstat.DefaultCommitCount holds the default value on creation for the commit_count field.
	memberyearstat.DefaultCommitCount = memberyearstatDescCommitCount.Default.(int)
	// memberyearstatDescPrCreated is the schema descriptor for pr_created field.
	memberyearstatDescPrCreated := memberyearstatFields[3].Descriptor()
	// memberyearstat.DefaultPrCreated holds the default value on creation for the pr_created field.
	memberyearstat.DefaultPrCreated = memberyearstatDescPrCreated.Default.(int)
	// memberyearstatDescPrMerged is the schema descriptor for pr_merged field.
	memberyearstatDescPrMerged := memberyearstatFields[4].Descriptor()
	// memberyearstat.DefaultPrMerged holds the default value on creation for the pr_merged field.
	memberyearstat.DefaultPrMerged = memberyearstatDescPrMerged.Default.(int)
	// memberyearstatDescIssueCount is the schema descriptor for issue_count field.
	memberyearstatDescIssueCount := memberyearstatFields[5].Descriptor()
	// memberyearstat.DefaultIssueCount holds the default value on creation for the issue_count field.
	memberyearstat.DefaultIssueCount = memberyearstatDescIssueCount.Default.(int)
	// memberyearstatDescReviewCount is the schema descriptor for review_count field.
	memberyearstatDescReviewCount := memberyearstatFields[6].Descriptor()
	// memberyearstat.DefaultReviewCount holds the default value on creation for the review_count field.
	memberyearstat.DefaultReviewCount = memberyearstatDescReviewCount.Default.(int)
	// memberyearstatDescAdditions is the schema descriptor for additions field.
	memberyearstatDescAdditions := memberyearstatFields[7].Descriptor()
	// memberyearstat.DefaultAdditions holds the default value on creation for the additions field.
	memberyearstat.DefaultAdditions = memberyearstatDescAdditions.Default.(int)
	// memberyearstatDescDeletions is the schema descriptor for deletions field.
	memberyearstatDescDeletions := memberyearstatFields[8].Descriptor()
	// memberyearstat.DefaultDeletions holds the default value on creation for the deletions field.
	memberyearstat.DefaultDeletions = memberyearstatDescDeletions.Default.(int)
	repometaFields := schema.RepoMeta{}.Fields()
	_ = repometaFields
	// repometaDescNameWithOwner is the schema descriptor for name_with_owner field.
	repometaDescNameWithOwner := repometaFields[0].Descriptor()
	// repometa.NameWithOwnerValidator is a validator for the "name_with_owner" field. It is called by the builders before save.
	repometa.NameWithOwnerValidator = repometaDescNameWithOwner.Validators[0].(func(string) error)
	// repometaDescOwner is the schema descriptor for owner field.
	repometaDescOwner := repometaFields[1].Descriptor()
	// repometa.OwnerValidator is a validator for the "owner" field. It is called by the builders before save.
	repometa.OwnerValidator = repometaDescOwner.Validators[0].(func(string) error)
	// repometaDescOwnerType is the schema descriptor for owner_type field.
	repometaDescOwnerType := repometaFields[2].Descriptor()
	// repometa.DefaultOwnerType holds the default value on creation for the owner_type field.
	repometa.DefaultOwnerType = repometaDescOwnerType.Default.(string)
	snapshotFields := schema.Snapshot{}.Fields()
	_ = snapshotFields
	// snapshotDescCapturedAt is the schema descriptor for captured_at field.
	snapshotDescCapturedAt := snapshotFields[0].Descriptor()
	// snapshot.DefaultCapturedAt holds the default value on creation for the captured_at field.
	snapshot.DefaultCapturedAt = snapshotDescCapturedAt.Default.(func() time.Time)
}
