// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberdaystat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberrepostat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberyearstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/predicate"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// SnapshotUpdate is the builder for updating Snapshot entities.
type SnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *SnapshotMutation
}

// Where appends a list predicates to the SnapshotUpdate builder.
func (_u *SnapshotUpdate) Where(ps ...predicate.Snapshot) *SnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// AddMemberStatIDs adds the "member_stats" edge to the MemberStat entity by IDs.
func (_u *SnapshotUpdate) AddMemberStatIDs(ids ...int) *SnapshotUpdate {
	_u.mutation.AddMemberStatIDs(ids...)
	return _u
}

// AddMemberStats adds the "member_stats" edges to the MemberStat entity.
func (_u *SnapshotUpdate) AddMemberStats(v ...*MemberStat) *SnapshotUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberStatIDs(ids...)
}

// AddMemberYearStatIDs adds the "member_year_stats" edge to the MemberYearStat entity by IDs.
func (_u *SnapshotUpdate) AddMemberYearStatIDs(ids ...int) *SnapshotUpdate {
	_u.mutation.AddMemberYearStatIDs(ids...)
	return _u
}

// AddMemberYearStats adds the "member_year_stats" edges to the MemberYearStat entity.
func (_u *SnapshotUpdate) AddMemberYearStats(v ...*MemberYearStat) *SnapshotUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberYearStatIDs(ids...)
}

// AddMemberDayStatIDs adds the "member_day_stats" edge to the MemberDayStat entity by IDs.
func (_u *SnapshotUpdate) AddMemberDayStatIDs(ids ...int) *SnapshotUpdate {
	_u.mutation.AddMemberDayStatIDs(ids...)
	return _u
}

// AddMemberDayStats adds the "member_day_stats" edges to the MemberDayStat entity.
func (_u *SnapshotUpdate) AddMemberDayStats(v ...*MemberDayStat) *SnapshotUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberDayStatIDs(ids...)
}

// AddMemberRepoStatIDs adds the "member_repo_stats" edge to the MemberRepoStat entity by IDs.
func (_u *SnapshotUpdate) AddMemberRepoStatIDs(ids ...int) *SnapshotUpdate {
	_u.mutation.AddMemberRepoStatIDs(ids...)
	return _u
}

// AddMemberRepoStats adds the "member_repo_stats" edges to the MemberRepoStat entity.
func (_u *SnapshotUpdate) AddMemberRepoStats(v ...*MemberRepoStat) *SnapshotUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberRepoStatIDs(ids...)
}

// Mutation returns the SnapshotMutation object of the builder.
func (_u *SnapshotUpdate) Mutation() *SnapshotMutation {
	return _u.mutation
}

// ClearMemberStats clears all "member_stats" edges to the MemberStat entity.
func (_u *SnapshotUpdate) ClearMemberStats() *SnapshotUpdate {
	_u.mutation.ClearMemberStats()
	return _u
}

// RemoveMemberStatIDs removes the "member_stats" edge to MemberStat entities by IDs.
func (_u *SnapshotUpdate) RemoveMemberStatIDs(ids ...int) *SnapshotUpdate {
	_u.mutation.RemoveMemberStatIDs(ids...)
	return _u
}

// RemoveMemberStats removes "member_stats" edges to MemberStat entities.
func (_u *SnapshotUpdate) RemoveMemberStats(v ...*MemberStat) *SnapshotUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberStatIDs(ids...)
}

// ClearMemberYearStats clears all "member_year_stats" edges to the MemberYearStat entity.
func (_u *SnapshotUpdate) ClearMemberYearStats() *SnapshotUpdate {
	_u.mutation.ClearMemberYearStats()
	return _u
}

// RemoveMemberYearStatIDs removes the "member_year_stats" edge to MemberYearStat entities by IDs.
func (_u *SnapshotUpdate) RemoveMemberYearStatIDs(ids ...int) *SnapshotUpdate {
	_u.mutation.RemoveMemberYearStatIDs(ids...)
	return _u
}

// RemoveMemberYearStats removes "member_year_stats" edges to MemberYearStat entities.
func (_u *SnapshotUpdate) RemoveMemberYearStats(v ...*MemberYearStat) *SnapshotUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberYearStatIDs(ids...)
}

// ClearMemberDayStats clears all "member_day_stats" edges to the MemberDayStat entity.
func (_u *SnapshotUpdate) ClearMemberDayStats() *SnapshotUpdate {
	_u.mutation.ClearMemberDayStats()
	return _u
}

// RemoveMemberDayStatIDs removes the "member_day_stats" edge to MemberDayStat entities by IDs.
func (_u *SnapshotUpdate) RemoveMemberDayStatIDs(ids ...int) *SnapshotUpdate {
	_u.mutation.RemoveMemberDayStatIDs(ids...)
	return _u
}

// RemoveMemberDayStats removes "member_day_stats" edges to MemberDayStat entities.
func (_u *SnapshotUpdate) RemoveMemberDayStats(v ...*MemberDayStat) *SnapshotUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberDayStatIDs(ids...)
}

// ClearMemberRepoStats clears all "member_repo_stats" edges to the MemberRepoStat entity.
func (_u *SnapshotUpdate) ClearMemberRepoStats() *SnapshotUpdate {
	_u.mutation.ClearMemberRepoStats()
	return _u
}

// RemoveMemberRepoStatIDs removes the "member_repo_stats" edge to MemberRepoStat entities by IDs.
func (_u *SnapshotUpdate) RemoveMemberRepoStatIDs(ids ...int) *SnapshotUpdate {
	_u.mutation.RemoveMemberRepoStatIDs(ids...)
	return _u
}

// RemoveMemberRepoStats removes "member_repo_stats" edges to MemberRepoStat entities.
func (_u *SnapshotUpdate) RemoveMemberRepoStats(v ...*MemberRepoStat) *SnapshotUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberRepoStatIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(snapshot.Table, snapshot.Columns, sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.MemberStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberStatsTable,
			Columns: []string{snapshot.MemberStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberstat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberStatsIDs(); len(nodes) > 0 && !_u.mutation.MemberStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberStatsTable,
			Columns: []string{snapshot.MemberStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberStatsTable,
			Columns: []string{snapshot.MemberStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberYearStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberYearStatsTable,
			Columns: []string{snapshot.MemberYearStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberyearstat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberYearStatsIDs(); len(nodes) > 0 && !_u.mutation.MemberYearStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberYearStatsTable,
			Columns: []string{snapshot.MemberYearStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberyearstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberYearStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberYearStatsTable,
			Columns: []string{snapshot.MemberYearStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberyearstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberDayStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberDayStatsTable,
			Columns: []string{snapshot.MemberDayStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberdaystat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberDayStatsIDs(); len(nodes) > 0 && !_u.mutation.MemberDayStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberDayStatsTable,
			Columns: []string{snapshot.MemberDayStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberdaystat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberDayStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberDayStatsTable,
			Columns: []string{snapshot.MemberDayStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberdaystat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberRepoStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberRepoStatsTable,
			Columns: []string{snapshot.MemberRepoStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberrepostat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberRepoStatsIDs(); len(nodes) > 0 && !_u.mutation.MemberRepoStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberRepoStatsTable,
			Columns: []string{snapshot.MemberRepoStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberrepostat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberRepoStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberRepoStatsTable,
			Columns: []string{snapshot.MemberRepoStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberrepostat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SnapshotUpdateOne is the builder for updating a single Snapshot entity.
type SnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SnapshotMutation
}

// AddMemberStatIDs adds the "member_stats" edge to the MemberStat entity by IDs.
func (_u *SnapshotUpdateOne) AddMemberStatIDs(ids ...int) *SnapshotUpdateOne {
	_u.mutation.AddMemberStatIDs(ids...)
	return _u
}

// AddMemberStats adds the "member_stats" edges to the MemberStat entity.
func (_u *SnapshotUpdateOne) AddMemberStats(v ...*MemberStat) *SnapshotUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberStatIDs(ids...)
}

// AddMemberYearStatIDs adds the "member_year_stats" edge to the MemberYearStat entity by IDs.
func (_u *SnapshotUpdateOne) AddMemberYearStatIDs(ids ...int) *SnapshotUpdateOne {
	_u.mutation.AddMemberYearStatIDs(ids...)
	return _u
}

// AddMemberYearStats adds the "member_year_stats" edges to the MemberYearStat entity.
func (_u *SnapshotUpdateOne) AddMemberYearStats(v ...*MemberYearStat) *SnapshotUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberYearStatIDs(ids...)
}

// AddMemberDayStatIDs adds the "member_day_stats" edge to the MemberDayStat entity by IDs.
func (_u *SnapshotUpdateOne) AddMemberDayStatIDs(ids ...int) *SnapshotUpdateOne {
	_u.mutation.AddMemberDayStatIDs(ids...)
	return _u
}

// AddMemberDayStats adds the "member_day_stats" edges to the MemberDayStat entity.
func (_u *SnapshotUpdateOne) AddMemberDayStats(v ...*MemberDayStat) *SnapshotUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberDayStatIDs(ids...)
}

// AddMemberRepoStatIDs adds the "member_repo_stats" edge to the MemberRepoStat entity by IDs.
func (_u *SnapshotUpdateOne) AddMemberRepoStatIDs(ids ...int) *SnapshotUpdateOne {
	_u.mutation.AddMemberRepoStatIDs(ids...)
	return _u
}

// AddMemberRepoStats adds the "member_repo_stats" edges to the MemberRepoStat entity.
func (_u *SnapshotUpdateOne) AddMemberRepoStats(v ...*MemberRepoStat) *SnapshotUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberRepoStatIDs(ids...)
}

// Mutation returns the SnapshotMutation object of the builder.
func (_u *SnapshotUpdateOne) Mutation() *SnapshotMutation {
	return _u.mutation
}

// ClearMemberStats clears all "member_stats" edges to the MemberStat entity.
func (_u *SnapshotUpdateOne) ClearMemberStats() *SnapshotUpdateOne {
	_u.mutation.ClearMemberStats()
	return _u
}

// RemoveMemberStatIDs removes the "member_stats" edge to MemberStat entities by IDs.
func (_u *SnapshotUpdateOne) RemoveMemberStatIDs(ids ...int) *SnapshotUpdateOne {
	_u.mutation.RemoveMemberStatIDs(ids...)
	return _u
}

// RemoveMemberStats removes "member_stats" edges to MemberStat entities.
func (_u *SnapshotUpdateOne) RemoveMemberStats(v ...*MemberStat) *SnapshotUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberStatIDs(ids...)
}

// ClearMemberYearStats clears all "member_year_stats" edges to the MemberYearStat entity.
func (_u *SnapshotUpdateOne) ClearMemberYearStats() *SnapshotUpdateOne {
	_u.mutation.ClearMemberYearStats()
	return _u
}

// RemoveMemberYearStatIDs removes the "member_year_stats" edge to MemberYearStat entities by IDs.
func (_u *SnapshotUpdateOne) RemoveMemberYearStatIDs(ids ...int) *SnapshotUpdateOne {
	_u.mutation.RemoveMemberYearStatIDs(ids...)
	return _u
}

// RemoveMemberYearStats removes "member_year_stats" edges to MemberYearStat entities.
func (_u *SnapshotUpdateOne) RemoveMemberYearStats(v ...*MemberYearStat) *SnapshotUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberYearStatIDs(ids...)
}

// ClearMemberDayStats clears all "member_day_stats" edges to the MemberDayStat entity.
func (_u *SnapshotUpdateOne) ClearMemberDayStats() *SnapshotUpdateOne {
	_u.mutation.ClearMemberDayStats()
	return _u
}

// RemoveMemberDayStatIDs removes the "member_day_stats" edge to MemberDayStat entities by IDs.
func (_u *SnapshotUpdateOne) RemoveMemberDayStatIDs(ids ...int) *SnapshotUpdateOne {
	_u.mutation.RemoveMemberDayStatIDs(ids...)
	return _u
}

// RemoveMemberDayStats removes "member_day_stats" edges to MemberDayStat entities.
func (_u *SnapshotUpdateOne) RemoveMemberDayStats(v ...*MemberDayStat) *SnapshotUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberDayStatIDs(ids...)
}

// ClearMemberRepoStats clears all "member_repo_stats" edges to the MemberRepoStat entity.
func (_u *SnapshotUpdateOne) ClearMemberRepoStats() *SnapshotUpdateOne {
	_u.mutation.ClearMemberRepoStats()
	return _u
}

// RemoveMemberRepoStatIDs removes the "member_repo_stats" edge to MemberRepoStat entities by IDs.
func (_u *SnapshotUpdateOne) RemoveMemberRepoStatIDs(ids ...int) *SnapshotUpdateOne {
	_u.mutation.RemoveMemberRepoStatIDs(ids...)
	return _u
}

// RemoveMemberRepoStats removes "member_repo_stats" edges to MemberRepoStat entities.
func (_u *SnapshotUpdateOne) RemoveMemberRepoStats(v ...*MemberRepoStat) *SnapshotUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberRepoStatIDs(ids...)
}

// Where appends a list predicates to the SnapshotUpdate builder.
func (_u *SnapshotUpdateOne) Where(ps ...predicate.Snapshot) *SnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SnapshotUpdateOne) Select(field string, fields ...string) *SnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Snapshot entity.
func (_u *SnapshotUpdateOne) Save(ctx context.Context) (*Snapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SnapshotUpdateOne) SaveX(ctx context.Context) *Snapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SnapshotUpdateOne) sqlSave(ctx context.Context) (_node *Snapshot, err error) {
	_spec := sqlgraph.NewUpdateSpec(snapshot.Table, snapshot.Columns, sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Snapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, snapshot.FieldID)
		for _, f := range fields {
			if !snapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != snapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.MemberStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberStatsTable,
			Columns: []string{snapshot.MemberStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberstat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberStatsIDs(); len(nodes) > 0 && !_u.mutation.MemberStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberStatsTable,
			Columns: []string{snapshot.MemberStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberStatsTable,
			Columns: []string{snapshot.MemberStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberYearStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberYearStatsTable,
			Columns: []string{snapshot.MemberYearStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberyearstat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberYearStatsIDs(); len(nodes) > 0 && !_u.mutation.MemberYearStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberYearStatsTable,
			Columns: []string{snapshot.MemberYearStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberyearstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberYearStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberYearStatsTable,
			Columns: []string{snapshot.MemberYearStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberyearstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberDayStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberDayStatsTable,
			Columns: []string{snapshot.MemberDayStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberdaystat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberDayStatsIDs(); len(nodes) > 0 && !_u.mutation.MemberDayStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberDayStatsTable,
			Columns: []string{snapshot.MemberDayStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberdaystat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberDayStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberDayStatsTable,
			Columns: []string{snapshot.MemberDayStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberdaystat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MemberRepoStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberRepoStatsTable,
			Columns: []string{snapshot.MemberRepoStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberrepostat.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMemberRepoStatsIDs(); len(nodes) > 0 && !_u.mutation.MemberRepoStatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberRepoStatsTable,
			Columns: []string{snapshot.MemberRepoStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberrepostat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberRepoStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberRepoStatsTable,
			Columns: []string{snapshot.MemberRepoStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberrepostat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Snapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
