// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// Snapshot is the model entity for the Snapshot schema.
type Snapshot struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CapturedAt holds the value of the "captured_at" field.
	CapturedAt time.Time `json:"captured_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SnapshotQuery when eager-loading is set.
	Edges        SnapshotEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SnapshotEdges holds the relations/edges for other nodes in the graph.
type SnapshotEdges struct {
	// MemberStats holds the value of the member_stats edge.
	MemberStats []*MemberStat `json:"member_stats,omitempty"`
	// MemberYearStats holds the value of the member_year_stats edge.
	MemberYearStats []*MemberYearStat `json:"member_year_stats,omitempty"`
	// MemberRepoStats holds the value of the member_repo_stats edge.
	MemberRepoStats []*MemberRepoStat `json:"member_repo_stats,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// MemberStatsOrErr returns the MemberStats value or an error if the edge
// was not loaded in eager-loading.
func (e SnapshotEdges) MemberStatsOrErr() ([]*MemberStat, error) {
	if e.loadedTypes[0] {
		return e.MemberStats, nil
	}
	return nil, &NotLoadedError{edge: "member_stats"}
}

// MemberYearStatsOrErr returns the MemberYearStats value or an error if the edge
// was not loaded in eager-loading.
func (e SnapshotEdges) MemberYearStatsOrErr() ([]*MemberYearStat, error) {
	if e.loadedTypes[1] {
		return e.MemberYearStats, nil
	}
	return nil, &NotLoadedError{edge: "member_year_stats"}
}

// MemberRepoStatsOrErr returns the MemberRepoStats value or an error if the edge
// was not loaded in eager-loading.
func (e SnapshotEdges) MemberRepoStatsOrErr() ([]*MemberRepoStat, error) {
	if e.loadedTypes[2] {
		return e.MemberRepoStats, nil
	}
	return nil, &NotLoadedError{edge: "member_repo_stats"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Snapshot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case snapshot.FieldID:
			values[i] = new(sql.NullInt64)
		case snapshot.FieldCapturedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Snapshot fields.
func (_m *Snapshot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case snapshot.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case snapshot.FieldCapturedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field captured_at", values[i])
			} else if value.Valid {
				_m.CapturedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Snapshot.
// This includes values selected through modifiers, order, etc.
func (_m *Snapshot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMemberStats queries the "member_stats" edge of the Snapshot entity.
func (_m *Snapshot) QueryMemberStats() *MemberStatQuery {
	return NewSnapshotClient(_m.config).QueryMemberStats(_m)
}

// QueryMemberYearStats queries the "member_year_stats" edge of the Snapshot entity.
func (_m *Snapshot) QueryMemberYearStats() *MemberYearStatQuery {
	return NewSnapshotClient(_m.config).QueryMemberYearStats(_m)
}

// QueryMemberRepoStats queries the "member_repo_stats" edge of the Snapshot entity.
func (_m *Snapshot) QueryMemberRepoStats() *MemberRepoStatQuery {
	return NewSnapshotClient(_m.config).QueryMemberRepoStats(_m)
}

// Update returns a builder for updating this Snapshot.
// Note that you need to call Snapshot.Unwrap() before calling this method if this Snapshot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Snapshot) Update() *SnapshotUpdateOne {
	return NewSnapshotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Snapshot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Snapshot) Unwrap() *Snapshot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Snapshot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Snapshot) String() string {
	var builder strings.Builder
	builder.WriteString("Snapshot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("captured_at=")
	builder.WriteString(_m.CapturedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Snapshots is a parsable slice of Snapshot.
type Snapshots []*Snapshot
