// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberrepostat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/memberyearstat"
	"github.com/Tattsum/github-analytics/infrastructure/ent/snapshot"
)

// SnapshotCreate is the builder for creating a Snapshot entity.
type SnapshotCreate struct {
	config
	mutation *SnapshotMutation
	hooks    []Hook
}

// SetCapturedAt sets the "captured_at" field.
func (_c *SnapshotCreate) SetCapturedAt(v time.Time) *SnapshotCreate {
	_c.mutation.SetCapturedAt(v)
	return _c
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_c *SnapshotCreate) SetNillableCapturedAt(v *time.Time) *SnapshotCreate {
	if v != nil {
		_c.SetCapturedAt(*v)
	}
	return _c
}

// AddMemberStatIDs adds the "member_stats" edge to the MemberStat entity by IDs.
func (_c *SnapshotCreate) AddMemberStatIDs(ids ...int) *SnapshotCreate {
	_c.mutation.AddMemberStatIDs(ids...)
	return _c
}

// AddMemberStats adds the "member_stats" edges to the MemberStat entity.
func (_c *SnapshotCreate) AddMemberStats(v ...*MemberStat) *SnapshotCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberStatIDs(ids...)
}

// AddMemberYearStatIDs adds the "member_year_stats" edge to the MemberYearStat entity by IDs.
func (_c *SnapshotCreate) AddMemberYearStatIDs(ids ...int) *SnapshotCreate {
	_c.mutation.AddMemberYearStatIDs(ids...)
	return _c
}

// AddMemberYearStats adds the "member_year_stats" edges to the MemberYearStat entity.
func (_c *SnapshotCreate) AddMemberYearStats(v ...*MemberYearStat) *SnapshotCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberYearStatIDs(ids...)
}

// AddMemberRepoStatIDs adds the "member_repo_stats" edge to the MemberRepoStat entity by IDs.
func (_c *SnapshotCreate) AddMemberRepoStatIDs(ids ...int) *SnapshotCreate {
	_c.mutation.AddMemberRepoStatIDs(ids...)
	return _c
}

// AddMemberRepoStats adds the "member_repo_stats" edges to the MemberRepoStat entity.
func (_c *SnapshotCreate) AddMemberRepoStats(v ...*MemberRepoStat) *SnapshotCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMemberRepoStatIDs(ids...)
}

// Mutation returns the SnapshotMutation object of the builder.
func (_c *SnapshotCreate) Mutation() *SnapshotMutation {
	return _c.mutation
}

// Save creates the Snapshot in the database.
func (_c *SnapshotCreate) Save(ctx context.Context) (*Snapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SnapshotCreate) SaveX(ctx context.Context) *Snapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SnapshotCreate) defaults() {
	if _, ok := _c.mutation.CapturedAt(); !ok {
		v := snapshot.DefaultCapturedAt()
		_c.mutation.SetCapturedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SnapshotCreate) check() error {
	if _, ok := _c.mutation.CapturedAt(); !ok {
		return &ValidationError{Name: "captured_at", err: errors.New(`ent: missing required field "Snapshot.captured_at"`)}
	}
	return nil
}

func (_c *SnapshotCreate) sqlSave(ctx context.Context) (*Snapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SnapshotCreate) createSpec() (*Snapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &Snapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(snapshot.Table, sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CapturedAt(); ok {
		_spec.SetField(snapshot.FieldCapturedAt, field.TypeTime, value)
		_node.CapturedAt = value
	}
	if nodes := _c.mutation.MemberStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberStatsTable,
			Columns: []string{snapshot.MemberStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MemberYearStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberYearStatsTable,
			Columns: []string{snapshot.MemberYearStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberyearstat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MemberRepoStatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   snapshot.MemberRepoStatsTable,
			Columns: []string{snapshot.MemberRepoStatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memberrepostat.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SnapshotCreateBulk is the builder for creating many Snapshot entities in bulk.
type SnapshotCreateBulk struct {
	config
	err      error
	builders []*SnapshotCreate
}

// Save creates the Snapshot entities in the database.
func (_c *SnapshotCreateBulk) Save(ctx context.Context) ([]*Snapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Snapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SnapshotCreateBulk) SaveX(ctx context.Context) []*Snapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
