// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MemberDayStatsColumns holds the columns for the "member_day_stats" table.
	MemberDayStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "login", Type: field.TypeString},
		{Name: "day", Type: field.TypeString},
		{Name: "commit_count", Type: field.TypeInt, Default: 0},
		{Name: "pr_created", Type: field.TypeInt, Default: 0},
		{Name: "pr_merged", Type: field.TypeInt, Default: 0},
		{Name: "issue_count", Type: field.TypeInt, Default: 0},
		{Name: "review_count", Type: field.TypeInt, Default: 0},
		{Name: "additions", Type: field.TypeInt, Default: 0},
		{Name: "deletions", Type: field.TypeInt, Default: 0},
		{Name: "snapshot_member_day_stats", Type: field.TypeInt},
	}
	// MemberDayStatsTable holds the schema information for the "member_day_stats" table.
	MemberDayStatsTable = &schema.Table{
		Name:       "member_day_stats",
		Columns:    MemberDayStatsColumns,
		PrimaryKey: []*schema.Column{MemberDayStatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "member_day_stats_snapshots_member_day_stats",
				Columns:    []*schema.Column{MemberDayStatsColumns[10]},
				RefColumns: []*schema.Column{SnapshotsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "memberdaystat_login_day_snapshot_member_day_stats",
				Unique:  true,
				Columns: []*schema.Column{MemberDayStatsColumns[1], MemberDayStatsColumns[2], MemberDayStatsColumns[10]},
			},
		},
	}
	// MemberRepoDayStatsColumns holds the columns for the "member_repo_day_stats" table.
	MemberRepoDayStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "login", Type: field.TypeString},
		{Name: "name_with_owner", Type: field.TypeString},
		{Name: "day", Type: field.TypeString},
		{Name: "commit_count", Type: field.TypeInt, Default: 0},
		{Name: "pr_created", Type: field.TypeInt, Default: 0},
		{Name: "pr_merged", Type: field.TypeInt, Default: 0},
		{Name: "issue_count", Type: field.TypeInt, Default: 0},
		{Name: "review_count", Type: field.TypeInt, Default: 0},
		{Name: "additions", Type: field.TypeInt, Default: 0},
		{Name: "deletions", Type: field.TypeInt, Default: 0},
		{Name: "snapshot_member_repo_day_stats", Type: field.TypeInt},
	}
	// MemberRepoDayStatsTable holds the schema information for the "member_repo_day_stats" table.
	MemberRepoDayStatsTable = &schema.Table{
		Name:       "member_repo_day_stats",
		Columns:    MemberRepoDayStatsColumns,
		PrimaryKey: []*schema.Column{MemberRepoDayStatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "member_repo_day_stats_snapshots_member_repo_day_stats",
				Columns:    []*schema.Column{MemberRepoDayStatsColumns[11]},
				RefColumns: []*schema.Column{SnapshotsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "memberrepodaystat_login_name_with_owner_day_snapshot_member_repo_day_stats",
				Unique:  true,
				Columns: []*schema.Column{MemberRepoDayStatsColumns[1], MemberRepoDayStatsColumns[2], MemberRepoDayStatsColumns[3], MemberRepoDayStatsColumns[11]},
			},
			{
				Name:    "memberrepodaystat_name_with_owner_snapshot_member_repo_day_stats",
				Unique:  false,
				Columns: []*schema.Column{MemberRepoDayStatsColumns[2], MemberRepoDayStatsColumns[11]},
			},
		},
	}
	// MemberRepoStatsColumns holds the columns for the "member_repo_stats" table.
	MemberRepoStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "login", Type: field.TypeString},
		{Name: "name_with_owner", Type: field.TypeString},
		{Name: "commit_count", Type: field.TypeInt, Default: 0},
		{Name: "pr_created", Type: field.TypeInt, Default: 0},
		{Name: "pr_merged", Type: field.TypeInt, Default: 0},
		{Name: "issue_count", Type: field.TypeInt, Default: 0},
		{Name: "review_count", Type: field.TypeInt, Default: 0},
		{Name: "additions", Type: field.TypeInt, Default: 0},
		{Name: "deletions", Type: field.TypeInt, Default: 0},
		{Name: "snapshot_member_repo_stats", Type: field.TypeInt},
	}
	// MemberRepoStatsTable holds the schema information for the "member_repo_stats" table.
	MemberRepoStatsTable = &schema.Table{
		Name:       "member_repo_stats",
		Columns:    MemberRepoStatsColumns,
		PrimaryKey: []*schema.Column{MemberRepoStatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "member_repo_stats_snapshots_member_repo_stats",
				Columns:    []*schema.Column{MemberRepoStatsColumns[10]},
				RefColumns: []*schema.Column{SnapshotsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "memberrepostat_login_name_with_owner_snapshot_member_repo_stats",
				Unique:  true,
				Columns: []*schema.Column{MemberRepoStatsColumns[1], MemberRepoStatsColumns[2], MemberRepoStatsColumns[10]},
			},
			{
				Name:    "memberrepostat_name_with_owner_snapshot_member_repo_stats",
				Unique:  false,
				Columns: []*schema.Column{MemberRepoStatsColumns[2], MemberRepoStatsColumns[10]},
			},
		},
	}
	// MemberStatsColumns holds the columns for the "member_stats" table.
	MemberStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "login", Type: field.TypeString},
		{Name: "total_commits", Type: field.TypeInt, Default: 0},
		{Name: "total_pr_created", Type: field.TypeInt, Default: 0},
		{Name: "total_pr_merged", Type: field.TypeInt, Default: 0},
		{Name: "total_issues", Type: field.TypeInt, Default: 0},
		{Name: "total_reviews", Type: field.TypeInt, Default: 0},
		{Name: "total_additions", Type: field.TypeInt, Default: 0},
		{Name: "total_deletions", Type: field.TypeInt, Default: 0},
		{Name: "first_activity_year", Type: field.TypeInt, Default: 0},
		{Name: "peak_activity_year", Type: field.TypeInt, Default: 0},
		{Name: "peak_activity_commits", Type: field.TypeInt, Default: 0},
		{Name: "pr_to_review_ratio", Type: field.TypeFloat64, Default: 0},
		{Name: "snapshot_member_stats", Type: field.TypeInt},
	}
	// MemberStatsTable holds the schema information for the "member_stats" table.
	MemberStatsTable = &schema.Table{
		Name:       "member_stats",
		Columns:    MemberStatsColumns,
		PrimaryKey: []*schema.Column{MemberStatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "member_stats_snapshots_member_stats",
				Columns:    []*schema.Column{MemberStatsColumns[13]},
				RefColumns: []*schema.Column{SnapshotsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "memberstat_login_snapshot_member_stats",
				Unique:  true,
				Columns: []*schema.Column{MemberStatsColumns[1], MemberStatsColumns[13]},
			},
		},
	}
	// MemberYearStatsColumns holds the columns for the "member_year_stats" table.
	MemberYearStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "login", Type: field.TypeString},
		{Name: "year", Type: field.TypeInt},
		{Name: "commit_count", Type: field.TypeInt, Default: 0},
		{Name: "pr_created", Type: field.TypeInt, Default: 0},
		{Name: "pr_merged", Type: field.TypeInt, Default: 0},
		{Name: "issue_count", Type: field.TypeInt, Default: 0},
		{Name: "review_count", Type: field.TypeInt, Default: 0},
		{Name: "additions", Type: field.TypeInt, Default: 0},
		{Name: "deletions", Type: field.TypeInt, Default: 0},
		{Name: "snapshot_member_year_stats", Type: field.TypeInt},
	}
	// MemberYearStatsTable holds the schema information for the "member_year_stats" table.
	MemberYearStatsTable = &schema.Table{
		Name:       "member_year_stats",
		Columns:    MemberYearStatsColumns,
		PrimaryKey: []*schema.Column{MemberYearStatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "member_year_stats_snapshots_member_year_stats",
				Columns:    []*schema.Column{MemberYearStatsColumns[10]},
				RefColumns: []*schema.Column{SnapshotsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "memberyearstat_login_year_snapshot_member_year_stats",
				Unique:  true,
				Columns: []*schema.Column{MemberYearStatsColumns[1], MemberYearStatsColumns[2], MemberYearStatsColumns[10]},
			},
		},
	}
	// RepoMetaColumns holds the columns for the "repo_meta" table.
	RepoMetaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name_with_owner", Type: field.TypeString},
		{Name: "owner", Type: field.TypeString},
		{Name: "owner_type", Type: field.TypeString, Default: ""},
		{Name: "snapshot_repo_metas", Type: field.TypeInt},
	}
	// RepoMetaTable holds the schema information for the "repo_meta" table.
	RepoMetaTable = &schema.Table{
		Name:       "repo_meta",
		Columns:    RepoMetaColumns,
		PrimaryKey: []*schema.Column{RepoMetaColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "repo_meta_snapshots_repo_metas",
				Columns:    []*schema.Column{RepoMetaColumns[4]},
				RefColumns: []*schema.Column{SnapshotsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "repometa_name_with_owner_snapshot_repo_metas",
				Unique:  true,
				Columns: []*schema.Column{RepoMetaColumns[1], RepoMetaColumns[4]},
			},
		},
	}
	// SnapshotsColumns holds the columns for the "snapshots" table.
	SnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "captured_at", Type: field.TypeTime},
	}
	// SnapshotsTable holds the schema information for the "snapshots" table.
	SnapshotsTable = &schema.Table{
		Name:       "snapshots",
		Columns:    SnapshotsColumns,
		PrimaryKey: []*schema.Column{SnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "snapshot_captured_at",
				Unique:  false,
				Columns: []*schema.Column{SnapshotsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MemberDayStatsTable,
		MemberRepoDayStatsTable,
		MemberRepoStatsTable,
		MemberStatsTable,
		MemberYearStatsTable,
		RepoMetaTable,
		SnapshotsTable,
	}
)

func init() {
	MemberDayStatsTable.ForeignKeys[0].RefTable = SnapshotsTable
	MemberRepoDayStatsTable.ForeignKeys[0].RefTable = SnapshotsTable
	MemberRepoStatsTable.ForeignKeys[0].RefTable = SnapshotsTable
	MemberStatsTable.ForeignKeys[0].RefTable = SnapshotsTable
	MemberYearStatsTable.ForeignKeys[0].RefTable = SnapshotsTable
	RepoMetaTable.ForeignKeys[0].RefTable = SnapshotsTable
}
