// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MemberRepoStatsColumns holds the columns for the "member_repo_stats" table.
	MemberRepoStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "login", Type: field.TypeString},
		{Name: "name_with_owner", Type: field.TypeString},
		{Name: "commit_count", Type: field.TypeInt, Default: 0},
		{Name: "pr_created", Type: field.TypeInt, Default: 0},
		{Name: "pr_merged", Type: field.TypeInt, Default: 0},
		{Name: "issue_count", Type: field.TypeInt, Default: 0},
		{Name: "review_count", Type: field.TypeInt, Default: 0},
		{Name: "additions", Type: field.TypeInt, Default: 0},
		{Name: "deletions", Type: field.TypeInt, Default: 0},
		{Name: "snapshot_member_repo_stats", Type: field.TypeInt},
	}
	// MemberRepoStatsTable holds the schema information for the "member_repo_stats" table.
	MemberRepoStatsTable = &schema.Table{
		Name:       "member_repo_stats",
		Columns:    MemberRepoStatsColumns,
		PrimaryKey: []*schema.Column{MemberRepoStatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "member_repo_stats_snapshots_member_repo_stats",
				Columns:    []*schema.Column{MemberRepoStatsColumns[10]},
				RefColumns: []*schema.Column{SnapshotsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "memberrepostat_login_name_with_owner_snapshot_member_repo_stats",
				Unique:  true,
				Columns: []*schema.Column{MemberRepoStatsColumns[1], MemberRepoStatsColumns[2], MemberRepoStatsColumns[10]},
			},
			{
				Name:    "memberrepostat_name_with_owner_snapshot_member_repo_stats",
				Unique:  false,
				Columns: []*schema.Column{MemberRepoStatsColumns[2], MemberRepoStatsColumns[10]},
			},
		},
	}
	// MemberStatsColumns holds the columns for the "member_stats" table.
	MemberStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "login", Type: field.TypeString},
		{Name: "total_commits", Type: field.TypeInt, Default: 0},
		{Name: "total_pr_created", Type: field.TypeInt, Default: 0},
		{Name: "total_pr_merged", Type: field.TypeInt, Default: 0},
		{Name: "total_issues", Type: field.TypeInt, Default: 0},
		{Name: "total_reviews", Type: field.TypeInt, Default: 0},
		{Name: "total_additions", Type: field.TypeInt, Default: 0},
		{Name: "total_deletions", Type: field.TypeInt, Default: 0},
		{Name: "first_activity_year", Type: field.TypeInt, Default: 0},
		{Name: "peak_activity_year", Type: field.TypeInt, Default: 0},
		{Name: "peak_activity_commits", Type: field.TypeInt, Default: 0},
		{Name: "pr_to_review_ratio", Type: field.TypeFloat64, Default: 0},
		{Name: "snapshot_member_stats", Type: field.TypeInt},
	}
	// MemberStatsTable holds the schema information for the "member_stats" table.
	MemberStatsTable = &schema.Table{
		Name:       "member_stats",
		Columns:    MemberStatsColumns,
		PrimaryKey: []*schema.Column{MemberStatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "member_stats_snapshots_member_stats",
				Columns:    []*schema.Column{MemberStatsColumns[13]},
				RefColumns: []*schema.Column{SnapshotsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "memberstat_login_snapshot_member_stats",
				Unique:  true,
				Columns: []*schema.Column{MemberStatsColumns[1], MemberStatsColumns[13]},
			},
		},
	}
	// MemberYearStatsColumns holds the columns for the "member_year_stats" table.
	MemberYearStatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "login", Type: field.TypeString},
		{Name: "year", Type: field.TypeInt},
		{Name: "commit_count", Type: field.TypeInt, Default: 0},
		{Name: "pr_created", Type: field.TypeInt, Default: 0},
		{Name: "pr_merged", Type: field.TypeInt, Default: 0},
		{Name: "issue_count", Type: field.TypeInt, Default: 0},
		{Name: "review_count", Type: field.TypeInt, Default: 0},
		{Name: "additions", Type: field.TypeInt, Default: 0},
		{Name: "deletions", Type: field.TypeInt, Default: 0},
		{Name: "snapshot_member_year_stats", Type: field.TypeInt},
	}
	// MemberYearStatsTable holds the schema information for the "member_year_stats" table.
	MemberYearStatsTable = &schema.Table{
		Name:       "member_year_stats",
		Columns:    MemberYearStatsColumns,
		PrimaryKey: []*schema.Column{MemberYearStatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "member_year_stats_snapshots_member_year_stats",
				Columns:    []*schema.Column{MemberYearStatsColumns[10]},
				RefColumns: []*schema.Column{SnapshotsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "memberyearstat_login_year_snapshot_member_year_stats",
				Unique:  true,
				Columns: []*schema.Column{MemberYearStatsColumns[1], MemberYearStatsColumns[2], MemberYearStatsColumns[10]},
			},
		},
	}
	// SnapshotsColumns holds the columns for the "snapshots" table.
	SnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "captured_at", Type: field.TypeTime},
	}
	// SnapshotsTable holds the schema information for the "snapshots" table.
	SnapshotsTable = &schema.Table{
		Name:       "snapshots",
		Columns:    SnapshotsColumns,
		PrimaryKey: []*schema.Column{SnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "snapshot_captured_at",
				Unique:  false,
				Columns: []*schema.Column{SnapshotsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MemberRepoStatsTable,
		MemberStatsTable,
		MemberYearStatsTable,
		SnapshotsTable,
	}
)

func init() {
	MemberRepoStatsTable.ForeignKeys[0].RefTable = SnapshotsTable
	MemberStatsTable.ForeignKeys[0].RefTable = SnapshotsTable
	MemberYearStatsTable.ForeignKeys[0].RefTable = SnapshotsTable
}
