// Code generated by ent, DO NOT EDIT.

package memberdaystat

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the memberdaystat type in the database.
	Label = "member_day_stat"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLogin holds the string denoting the login field in the database.
	FieldLogin = "login"
	// FieldDay holds the string denoting the day field in the database.
	FieldDay = "day"
	// FieldCommitCount holds the string denoting the commit_count field in the database.
	FieldCommitCount = "commit_count"
	// FieldPrCreated holds the string denoting the pr_created field in the database.
	FieldPrCreated = "pr_created"
	// FieldPrMerged holds the string denoting the pr_merged field in the database.
	FieldPrMerged = "pr_merged"
	// FieldIssueCount holds the string denoting the issue_count field in the database.
	FieldIssueCount = "issue_count"
	// FieldReviewCount holds the string denoting the review_count field in the database.
	FieldReviewCount = "review_count"
	// FieldAdditions holds the string denoting the additions field in the database.
	FieldAdditions = "additions"
	// FieldDeletions holds the string denoting the deletions field in the database.
	FieldDeletions = "deletions"
	// EdgeSnapshot holds the string denoting the snapshot edge name in mutations.
	EdgeSnapshot = "snapshot"
	// Table holds the table name of the memberdaystat in the database.
	Table = "member_day_stats"
	// SnapshotTable is the table that holds the snapshot relation/edge.
	SnapshotTable = "member_day_stats"
	// SnapshotInverseTable is the table name for the Snapshot entity.
	// It exists in this package in order to avoid circular dependency with the "snapshot" package.
	SnapshotInverseTable = "snapshots"
	// SnapshotColumn is the table column denoting the snapshot relation/edge.
	SnapshotColumn = "snapshot_member_day_stats"
)

// Columns holds all SQL columns for memberdaystat fields.
var Columns = []string{
	FieldID,
	FieldLogin,
	FieldDay,
	FieldCommitCount,
	FieldPrCreated,
	FieldPrMerged,
	FieldIssueCount,
	FieldReviewCount,
	FieldAdditions,
	FieldDeletions,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "member_day_stats"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"snapshot_member_day_stats",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// LoginValidator is a validator for the "login" field. It is called by the builders before save.
	LoginValidator func(string) error
	// DayValidator is a validator for the "day" field. It is called by the builders before save.
	DayValidator func(string) error
	// DefaultCommitCount holds the default value on creation for the "commit_count" field.
	DefaultCommitCount int
	// DefaultPrCreated holds the default value on creation for the "pr_created" field.
	DefaultPrCreated int
	// DefaultPrMerged holds the default value on creation for the "pr_merged" field.
	DefaultPrMerged int
	// DefaultIssueCount holds the default value on creation for the "issue_count" field.
	DefaultIssueCount int
	// DefaultReviewCount holds the default value on creation for the "review_count" field.
	DefaultReviewCount int
	// DefaultAdditions holds the default value on creation for the "additions" field.
	DefaultAdditions int
	// DefaultDeletions holds the default value on creation for the "deletions" field.
	DefaultDeletions int
)

// OrderOption defines the ordering options for the MemberDayStat queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLogin orders the results by the login field.
func ByLogin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogin, opts...).ToFunc()
}

// ByDay orders the results by the day field.
func ByDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDay, opts...).ToFunc()
}

// ByCommitCount orders the results by the commit_count field.
func ByCommitCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommitCount, opts...).ToFunc()
}

// ByPrCreated orders the results by the pr_created field.
func ByPrCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrCreated, opts...).ToFunc()
}

// ByPrMerged orders the results by the pr_merged field.
func ByPrMerged(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrMerged, opts...).ToFunc()
}

// ByIssueCount orders the results by the issue_count field.
func ByIssueCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssueCount, opts...).ToFunc()
}

// ByReviewCount orders the results by the review_count field.
func ByReviewCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewCount, opts...).ToFunc()
}

// ByAdditions orders the results by the additions field.
func ByAdditions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdditions, opts...).ToFunc()
}

// ByDeletions orders the results by the deletions field.
func ByDeletions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletions, opts...).ToFunc()
}

// BySnapshotField orders the results by snapshot field.
func BySnapshotField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSnapshotStep(), sql.OrderByField(field, opts...))
	}
}
func newSnapshotStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SnapshotInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SnapshotTable, SnapshotColumn),
	)
}
